// Year 7 Chapter 2: Angles. One 4-page lesson per exercise in Test Yourself 2.
const lesson = require('../../lib/lesson');
const D = require('../../lib/diagrams');

const draw = (label = '', h = 26) => `<div class="template-card">${D.drawSpace({ label, w: 80, h })}</div>`;
const blank = (h = 34) => `<div class="template-card">${D.drawSpace({ ray: false, w: 80, h })}</div>`;
const ang = (deg, labels, o = {}) => D.angle({ deg, labels, w: 30, h: 20, ...o });
// A straight line with a ray: the known angle and the unknown on either side.
const straight = (a, la, lb) => D.rays({ rays: [0, a, 180], arcs: [{ from: 0, to: a, label: la }, { from: a, to: 180, label: lb, r: 6 }], w: 44, h: 24, cy: 19, R: 16 });
const rightSplit = (a, la, lb) => D.rays({ rays: [0, a, 90], arcs: [{ from: 0, to: a, label: la }, { from: a, to: 90, label: lb, r: 7 }], w: 34, h: 30, cx: 8, cy: 25, R: 20 });
const vert = (a, la, lb) => D.rays({ rays: [a, 180 + a, 180 - a + 0, 360 - a], arcs: [{ from: 360 - a, to: a + 360, label: la }, { from: 180 - a, to: 180 + a, label: lb }], w: 44, h: 30 });
const pll = (tilt, marks, o = {}) => D.parallel({ tilt, marks, w: 38, h: 26, ...o });

module.exports = {
  year: 7, stage: 4, number: 2, title: 'Angles', accent: '#e67e22',
  fileName: 'Year7-Ch02-Angles',
  goals: ['measure and draw angles with a protractor', 'classify angles by size', 'find complementary, supplementary and vertically opposite angles',
    'construct parallel and perpendicular lines', 'find corresponding, alternate and co-interior angles on parallel lines', 'prove that two lines are parallel'],
  syllabus: 'NSW Mathematics K–10 Syllabus (2022), Stage 4 Measurement and space: MA4-ANG-C-01 applies angle relationships to solve problems, including those related to transversals on sets of parallel lines.',
  lessons: [
    lesson({
      code: '2.01', title: 'Naming angles',
      li: ['name an angle using three letters', 'identify adjacent angles'],
      sc: ['name an angle with the <b>vertex</b> in the middle', 'draw an angle from its name', 'name an <b>adjacent</b> angle'],
      terms: ['Vertex', 'Arm', 'Adjacent angles'],
      we: [{ t: 'Name this angle in two ways.', fig: ang(55, ['A', 'B', 'C']) }, { t: 'Draw and label ∠BKT.', draw: draw('') },
        { t: 'Name the angle adjacent to ∠POQ.', fig: D.rays({ rays: [0, 50, 120], ends: ['Q', 'R', 'P'], centre: 'O', w: 44, h: 28, cy: 22, R: 16 }) },
        { t: 'Name all 3 angles at O.', fig: D.rays({ rays: [0, 50, 120], ends: ['Q', 'R', 'P'], centre: 'O', w: 44, h: 28, cy: 22, R: 16 }) },
        { t: 'Name the angle marked with a •.', fig: D.polygon({ pts: [[6, 26], [40, 26], [30, 6]], vlabels: ['L', 'O', 'N'], w: 48, h: 32 }) + '<p style="font-size:8pt">The • is at O.</p>' }, 'Why is it wrong to call an angle “∠B” when three lines meet at B?'],
      a: { text: 'Name each angle using three letters.', kind: 'work', cols: 3, items: [{ t: '', fig: ang(40, ['P', 'Q', 'R']) }, { t: '', fig: ang(110, ['D', 'E', 'F']) }, { t: '', fig: ang(70, ['X', 'Y', 'Z']) },
        { t: '', fig: ang(135, ['M', 'N', 'K']) }, { t: '', fig: ang(90, ['S', 'T', 'U']) }, { t: '', fig: ang(25, ['G', 'H', 'J']) }] },
      b: { text: 'Draw and label each angle. Put the vertex at the dot.', kind: 'work', cols: 2, items: [{ t: '∠FPR', draw: draw('P', 22) }, { t: '∠MZQ', draw: draw('Z', 22) }] },
      c: { text: 'Use the diagram.', kind: 'short', keepShort: true, fig: D.rays({ rays: [0, 40, 100, 160], ends: ['C', 'D', 'E', 'A'], centre: 'B', w: 60, h: 30, cy: 25, R: 20 }),
        items: ['Name the angle adjacent to ∠ABE on the other side of BE.', 'Name the angle adjacent to ∠CBD.', 'Name the largest angle in the diagram.', 'How many angles are at B in total?', 'Which angle is made of ∠DBE and ∠EBA?', 'Name the angle between arms BC and BE.'] },
      d: { text: 'Name the marked angle in each diagram.', kind: 'work', items: [{ t: 'The angle at vertex M in △LMN.', fig: D.polygon({ pts: [[5, 24], [38, 24], [18, 5]], vlabels: ['L', 'M', 'N'], angles: ['', '•', ''], w: 46, h: 30 }) },
        { t: 'The angle at R in quadrilateral PQRS.', fig: D.polygon({ pts: [[5, 22], [38, 22], [44, 6], [12, 4]], vlabels: ['P', 'Q', 'R', 'S'], angles: ['', '', '•', ''], w: 50, h: 28 }) },
        'Can ∠ABC and ∠CBA be the same angle? Explain.', 'Draw two adjacent angles ∠PQR and ∠RQS.'] },
      tallExamples: true,
      ext: { q: 'Four rays come from point O. How many different angles are there?', steps: ['Count angles using each pair of rays', 'With 4 rays there are 3 + 2 + 1 pairs'], a: '6 angles', qs: ['How many angles are made by 5 rays from one point?', 'Name all the angles made by rays OA, OB, OC and OD.'] },
      summary: { steps: ['An angle has two <b>arms</b> and a <b>vertex</b>.', 'Name it with 3 letters; the vertex goes in the middle.', '∠ABC and ∠CBA are the same angle.', '<b>Adjacent</b> angles share a vertex and an arm.'],
        worked: [['Name the angle', ['Vertex is B, arms go to A and C'], '∠ABC', ang(50, ['A', 'B', 'C'])], ['Draw ∠KLM', ['Vertex L', 'Arms LK and LM'], 'a V shape with L at the point'], ['Adjacent to ∠POQ?', ['Shares arm OQ and vertex O'], '∠QOR'], ['Angles from 4 rays', ['3 + 2 + 1'], '6']] },
      exit: { fig: ang(65, ['T', 'U', 'V'], { w: 40, h: 26 }), qs: ['Name the angle shown.', 'Which letter is the vertex? Why?', 'Draw and label two adjacent angles ∠ABC and ∠CBD.'] },
      ans: { we: ['∠ABC or ∠CBA', 'vertex K in the middle', '∠QOR', '∠QOR, ∠ROP, ∠QOP', '∠LON', 'There are several angles at B, so we need 3 letters'], a: ['∠PQR', '∠DEF', '∠XYZ', '∠MNK', '∠STU', '∠GHJ'], b: ['vertex P, arms PF and PR', 'vertex Z, arms ZM and ZQ'],
        c: ['∠DBE', '∠DBE', '∠CBA', '6', '∠DBA', '∠CBE'], d: ['∠LMN', '∠QRS', 'Yes: the vertex B is in the middle of both', 'e.g. two angles sharing arm QR'], ext: ['10', '∠AOB, ∠AOC, ∠AOD, ∠BOC, ∠BOD, ∠COD'], exit: ['∠TUV', 'U, because it is the point where the arms meet', 'two angles sharing arm BC'] },
    }),

    lesson({
      code: '2.02', title: 'Measuring and drawing angles',
      li: ['use a protractor to measure and draw angles, including reflex angles'],
      sc: ['place the protractor centre on the vertex and 0° on one arm', 'read the correct scale', 'draw a <b>reflex</b> angle by drawing 360° minus the angle'],
      terms: ['Protractor', 'Reflex angle'],
      we: [{ t: 'Measure ∠ABC.', fig: ang(64, ['A', 'B', 'C'], { w: 44, h: 28 }) }, { t: 'Draw ∠JUG = 84°.', draw: draw('U') }, { t: 'Measure this obtuse angle.', fig: ang(128, ['P', 'Q', 'R'], { w: 44, h: 28 }) }, { t: 'Draw ∠QRA = 117°.', draw: draw('R') },
        { t: 'Draw ∠XDW = 210°.', draw: draw('D', 32) }, { t: 'Draw ∠AMP = 300°.', draw: draw('M', 32) }],
      a: { text: 'Measure each angle.', kind: 'work', cols: 3, items: [{ t: '', fig: ang(35, ['D', 'E', 'F']) }, { t: '', fig: ang(72, ['G', 'H', 'I']) }, { t: '', fig: ang(90, ['J', 'K', 'L']) },
        { t: '', fig: ang(105, ['M', 'N', 'O']) }, { t: '', fig: ang(150, ['S', 'T', 'U']) }, { t: '', fig: ang(48, ['X', 'Y', 'Z']) }] },
      b: { text: 'Draw each angle.', kind: 'work', items: [{ t: '∠POT = 41°', draw: draw('O', 22) }, { t: '∠DGE = 150°', draw: draw('G', 22) }] },
      c: { text: 'Draw each angle.', kind: 'work', items: [{ t: '∠SAR = 96°', draw: draw('A') }, { t: '∠KLM = 23°', draw: draw('L') }, { t: '∠VWX = 165°', draw: draw('W') }, { t: '∠BCD = 72°', draw: draw('C') }] },
      d: { text: 'Reflex angles.', kind: 'work', items: [{ t: 'Draw ∠MNB = 195°', draw: draw('N', 32) }, { t: 'Draw ∠PLO = 270°', draw: draw('L', 32) }, { t: 'Measure the reflex angle.', fig: ang(230, ['A', 'B', 'C'], { w: 40, h: 34 }) }, 'An angle is 145°. What size is the reflex angle at the same vertex?'] },
      ext: { q: 'The hands of a clock show 4 o’clock. What is the angle between them? What is the reflex angle?', steps: ['Each hour mark is 360 ÷ 12 = 30°', '4 hours apart: 4 × 30 = 120°', 'Reflex: 360 − 120 = 240°'], a: '120° and reflex 240°', qs: ['Find the angle between the hands at 5 o’clock and at 9 o’clock.', 'At 3:30 the hour hand is halfway between 3 and 4. Find the angle between the hands.'] },
      summary: { steps: ['Centre of the protractor on the vertex.', '0° line along one arm.', 'Count up from 0° on that scale.', 'Reflex: measure the small angle, then 360° − it.'],
        worked: [['Measure a 64° angle', ['Centre on vertex, 0° on arm', 'Read the scale that starts at 0°'], '64°'], ['Draw 117°', ['Draw an arm, mark 117°, join to the vertex'], 'an obtuse angle'], ['Draw 210°', ['360 − 210 = 150', 'Draw 150° the other way'], 'a reflex angle'], ['Angle at 4 o’clock', ['4 × 30°'], '120°']] },
      exit: { fig: ang(58, ['R', 'S', 'T'], { w: 44, h: 28 }), qs: ['Measure ∠RST.', 'Draw ∠ABC = 135°.', 'Draw ∠XYZ = 250°.'] },
      ans: { we: ['64°', 'accurate 84° angle', '128°', 'accurate 117° angle', 'draw 150° on the other side', 'draw 60° on the other side'], a: ['35°', '72°', '90°', '105°', '150°', '48°'], b: ['41° drawn', '150° drawn'], c: ['96° drawn', '23° drawn', '165° drawn', '72° drawn'],
        d: ['360 − 195 = 165° on the other side', 'three-quarter turn', '230°', '215°'], ext: ['150° and 90°', '75°'], exit: ['58°', 'accurate 135°', 'draw 110° the other way'] },
    }),

    lesson({
      code: '2.03', title: 'Classifying angles',
      li: ['classify angles as acute, right, obtuse, straight, reflex or a revolution'],
      sc: ['know the size range for each type of angle', 'classify an angle from its size or a diagram', 'name and classify an angle in a diagram'],
      terms: ['Acute', 'Obtuse', 'Reflex'],
      we: ['Classify: 34°, 90°, 145°, 180°, 250°, 360°', { t: 'Name and classify the angle.', fig: ang(120, ['W', 'I', 'H'], { w: 40, h: 26 }) }, 'Is 90.5° acute, right or obtuse?', 'An angle is 3 times a right angle. Classify it.',
        { t: 'Name and classify both angles at R.', fig: D.rays({ rays: [0, 70, 180], ends: ['D', 'A', 'B'], centre: 'R', w: 44, h: 24, cy: 19, R: 16 }) }, 'Can a triangle have an obtuse angle and a right angle? Explain.'],
      a: { text: 'Classify each angle.', kind: 'short', keepShort: true, items: ['47°', '90°', '160°', '180°', '215°', '12°'] },
      b: { text: 'Classify each angle.', kind: 'short', items: ['89°', '91°', '359°', '360°', '179°', '181°'] },
      c: { text: 'Name each angle with 3 letters, then classify it.', kind: 'work', cols: 3, items: [{ t: '', fig: ang(35, ['G', 'L', 'U']) }, { t: '', fig: ang(140, ['V', 'R', 'P']) }, { t: '', fig: ang(90, ['P', 'N', 'E']) },
        { t: '', fig: ang(240, ['S', 'M', 'A'], { h: 30 }) }, { t: '', fig: ang(180, ['Z', 'X', 'Y']) }, { t: '', fig: ang(75, ['M', 'V', 'T']) }] },
      d: { text: 'Think it through.', kind: 'work', items: ['What angle does a minute hand turn through in 20 minutes? Classify it.', 'Two acute angles are added. Can the answer be obtuse? Give an example.', 'List 3 obtuse angles that are multiples of 25°.', 'How many reflex angles are there between 200° and 220° (whole degrees)?'] },
      ext: { q: 'A wheel turns 1 3/4 revolutions. How many degrees is that?', steps: ['1 revolution = 360°', '¾ of 360° = 270°', '360 + 270'], a: '630°', qs: ['A skater spins 2½ times. How many degrees?', 'A fan turns 1080°. How many revolutions?'] },
      summary: { title: 'Angle types', steps: ['<b>Acute</b>: less than 90°. <b>Right</b>: 90°.', '<b>Obtuse</b>: between 90° and 180°.', '<b>Straight</b>: 180°. <b>Reflex</b>: between 180° and 360°.', '<b>Revolution</b>: 360°.'],
        worked: [['Classify 125°', ['Between 90° and 180°'], 'obtuse'], ['Classify 300°', ['Between 180° and 360°'], 'reflex'], ['Name and classify', ['Vertex I in the middle', 'More than 90°'], '∠WIH, obtuse', ang(120, ['W', 'I', 'H'])], ['1¾ revolutions', ['360 + 270'], '630°']] },
      exit: { qs: ['Classify 88°.', 'Classify 200° and 180°.', 'Name and classify both angles in Example 5 (∠DRA and ∠ARB).'] },
      ans: { we: ['acute, right, obtuse, straight, reflex, revolution', '∠WIH, obtuse', 'obtuse', '270°, reflex', '∠DRA acute (70°), ∠ARB obtuse (110°)', 'No: 90° + more than 90° is already more than 180°'], a: ['acute', 'right', 'obtuse', 'straight', 'reflex', 'acute'], b: ['acute', 'obtuse', 'reflex', 'revolution', 'obtuse', 'reflex'],
        c: ['∠GLU acute', '∠VRP obtuse', '∠PNE right', '∠SMA reflex', '∠ZXY straight', '∠MVT acute'], d: ['120°, obtuse', 'Yes, e.g. 60° + 50° = 110°', '100°, 125°, 150°, 175°', '19 (201° to 219°)'], ext: ['900°', '3 revolutions'], exit: ['acute', 'reflex; straight', '∠DRA acute; ∠ARB obtuse'] },
    }),

    lesson({
      code: '2.04', title: 'Complementary and supplementary angles',
      li: ['find complementary and supplementary angles'],
      sc: ['know complementary angles add to 90°', 'know supplementary angles add to 180°', 'find an unknown angle in a right angle or on a straight line'],
      terms: ['Complementary', 'Supplementary'],
      we: ['Find the complement of 35° and of 78°.', 'Find the supplement of 45° and of 100°.', { t: 'Find the value of <i>m</i>.', fig: rightSplit(28, '28°', 'm°') }, { t: 'Find the value of <i>k</i>.', fig: straight(47, '47°', 'k°') },
        { t: 'Find <i>x</i>.', fig: straight(58, '2x°', '122°') }, 'Two supplementary angles are equal. What size are they?'],
      a: { text: 'Write the complement of each angle.', kind: 'short', items: ['35°', '78°', '4°', '60°', '45°', '89°'] },
      b: { text: 'Write the supplement of each angle.', kind: 'short', items: ['45°', '100°', '178°', '90°', '12°', '135°'] },
      c: { text: 'Find the value of each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: rightSplit(28, '28°', 'm°') }, { t: '', fig: straight(47, '47°', 'k°') }, { t: '', fig: rightSplit(61, '61°', 'a°') },
        { t: '', fig: straight(122, '122°', 'y°') }, { t: '', fig: rightSplit(15, 'p°', '75°') }, { t: '', fig: straight(90, 'b°', 'b°') }] },
      d: { text: 'Harder problems.', kind: 'work', items: ['An angle is 20° more than its complement. Find both angles.', 'The supplement of an angle is 4 times the angle. Find the angle.', 'Find <i>x</i> if 3<i>x</i>° and 60° are supplementary.', 'Can an obtuse angle have a complement? Explain.'] },
      ext: { q: 'Find the angle whose supplement is 3 times its complement.', steps: ['Let the angle be x', '180 − x = 3(90 − x)', '180 − x = 270 − 3x, so 2x = 90'], a: 'x = 45°', qs: ['Find the angle whose supplement is 4 times its complement.', 'Find the complement of the supplement of 130°.'] },
      summary: { steps: ['<b>Complementary</b> angles add to 90°.', '<b>Supplementary</b> angles add to 180°.', 'Right angle split in two → complementary.', 'Straight line split in two → supplementary.'],
        worked: [['Complement of 35°', ['90 − 35'], '55°'], ['Supplement of 100°', ['180 − 100'], '80°'], ['Find k', ['k + 47 = 180'], 'k = 133', straight(47, '47°', 'k°')], ['Supplement = 3 × complement', ['180 − x = 270 − 3x'], '45°']] },
      exit: { qs: ['Find the complement of 62°.', 'Find the supplement of 118°.', 'Two angles on a straight line are x° and 3x°. Find x.'] },
      ans: { we: ['55°; 12°', '135°; 80°', 'm = 62', 'k = 133', 'x = 29', '90° each'], a: ['55°', '12°', '86°', '30°', '45°', '1°'], b: ['135°', '80°', '2°', '90°', '168°', '45°'], c: ['m = 62', 'k = 133', 'a = 29', 'y = 58', 'p = 15', 'b = 90'],
        d: ['55° and 35°', '36°', 'x = 40', 'No: it is already more than 90°'], ext: ['60°', '40°'], exit: ['28°', '62°', 'x = 45'] },
    }),

    lesson({
      code: '2.05', title: 'Angles at a point and vertically opposite angles',
      li: ['find unknown angles using angle rules'],
      sc: ['use angles on a straight line add to 180°', 'use angles at a point add to 360°', 'use vertically opposite angles are equal'],
      terms: ['Angles at a point', 'Vertically opposite'],
      we: [{ t: 'Find <i>a</i>.', fig: straight(70, '70°', 'a°') }, { t: 'Find <i>m</i>.', fig: vert(25, '25°', 'm°') },
        { t: 'Find <i>a</i> (angles at a point).', fig: D.rays({ rays: [0, 100, 230], arcs: [{ from: 0, to: 100, label: '100°' }, { from: 100, to: 230, label: '130°' }, { from: 230, to: 360, label: 'a°' }], w: 44, h: 34 }) },
        { t: 'Find <i>x</i>.', fig: D.rays({ rays: [0, 120, 240], arcs: [{ from: 0, to: 120, label: 'x°' }, { from: 120, to: 240, label: 'x°' }, { from: 240, to: 360, label: 'x°' }], w: 44, h: 34 }) },
        { t: 'Find <i>p</i>.', fig: D.rays({ rays: [0, 140, 215], arcs: [{ from: 0, to: 140, label: '140°' }, { from: 140, to: 215, label: '75°' }, { from: 215, to: 360, label: 'p°' }], w: 44, h: 34 }) },
        { t: 'Find <i>p</i>, <i>q</i> and <i>r</i>.', fig: D.rays({ rays: [25, 180, 205, 0], arcs: [{ from: 0, to: 25, label: '25°' }, { from: 25, to: 180, label: 'p°' }, { from: 180, to: 205, label: 'q°' }, { from: 205, to: 360, label: 'r°' }], w: 44, h: 30 }) }],
      a: { text: 'Angles on a straight line. Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: straight(35, '35°', 'y°') }, { t: '', fig: straight(100, '100°', 'a°') }, { t: '', fig: straight(44, 'm°', '136°') },
        { t: '', fig: straight(82, '82°', 'x°') }, { t: '', fig: straight(155, '155°', 'k°') }, { t: '', fig: straight(90, 'd°', '90°') }] },
      b: { text: 'Vertically opposite angles. Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: vert(35, '35°', 'y°') }, { t: '', fig: vert(40, '80°', 'm°') }, { t: '', fig: vert(30, '60°', 'f°') }] },
      c: { text: 'Angles at a point. Find each variable.', kind: 'work', cols: 3, items: [
        { t: '', fig: D.rays({ rays: [0, 140, 250], arcs: [{ from: 0, to: 140, label: '140°' }, { from: 140, to: 250, label: '110°' }, { from: 250, to: 360, label: 'f°' }], w: 44, h: 34 }) },
        { t: '', fig: D.rays({ rays: [0, 90, 173, 255], arcs: [{ from: 0, to: 90, right: true }, { from: 90, to: 173, label: 't°' }, { from: 173, to: 255, label: '82°' }, { from: 255, to: 360, label: '105°' }], w: 44, h: 34 }) },
        { t: '', fig: D.rays({ rays: [0, 90, 180, 270], arcs: [{ from: 0, to: 90, label: 'x°' }, { from: 90, to: 180, label: 'x°' }, { from: 180, to: 270, label: 'x°' }, { from: 270, to: 360, label: 'x°' }], w: 44, h: 34 }) }] },
      d: { text: 'Find each variable. Give a reason.', kind: 'work', items: [
        { t: 'Find <i>x</i> and <i>y</i>.', fig: D.rays({ rays: [48, 228, 0, 180], arcs: [{ from: 0, to: 48, label: '48°' }, { from: 48, to: 180, label: 'x°' }, { from: 180, to: 228, label: 'y°' }], w: 44, h: 30 }) },
        { t: 'Find <i>t</i>.', fig: D.rays({ rays: [0, 82, 187], arcs: [{ from: 0, to: 82, label: '82°' }, { from: 82, to: 187, label: '105°' }, { from: 187, to: 360, label: 't°' }], w: 44, h: 34 }) },
        'Three equal angles meet at a point. Find each angle.', 'Two lines cross. One angle is 65°. Find the other three angles.'] },
      ext: { q: 'Angles at a point are 2x°, 3x° and 4x°. Find x.', steps: ['Angles at a point add to 360°', '2x + 3x + 4x = 9x = 360'], a: 'x = 40', qs: ['Angles on a straight line are x°, 2x° and 3x°. Find each angle.', 'Two lines cross. One angle is (2x + 10)° and its vertically opposite angle is 70°. Find x.'] },
      summary: { steps: ['Straight line: angles add to <b>180°</b>.', 'At a point: angles add to <b>360°</b>.', '<b>Vertically opposite</b> angles are equal.', 'Always give a reason.'],
        worked: [['Find a', ['a + 70 = 180'], 'a = 110', straight(70, '70°', 'a°')], ['Find m', ['Vertically opposite'], 'm = 25', vert(25, '25°', 'm°')], ['At a point: 140°, 75°, p°', ['p = 360 − 215'], 'p = 145'], ['2x + 3x + 4x = 360', ['9x = 360'], 'x = 40']] },
      exit: { qs: ['Angles on a straight line: 64° and x°. Find x.', 'Two lines cross. One angle is 38°. Find the vertically opposite angle.', 'Angles at a point: 95°, 130° and y°. Find y.'] },
      ans: { we: ['a = 110', 'm = 25', 'a = 130', 'x = 120', 'p = 145', 'p = 155, q = 25, r = 155'], a: ['y = 145', 'a = 80', 'm = 44', 'x = 98', 'k = 25', 'd = 90'], b: ['y = 35', 'm = 80', 'f = 60'], c: ['f = 110', 't = 83', 'x = 90'],
        d: ['x = 132 (straight line), y = 48 (vertically opposite)', 't = 173 (angles at a point)', '120° each', '115°, 65°, 115°'], ext: ['30°, 60°, 90°', 'x = 30'], exit: ['116', '38°', '135'] },
    }),

    lesson({
      code: '2.06', title: 'Parallel and perpendicular lines',
      li: ['identify parallel and perpendicular lines', 'construct parallel and perpendicular lines with compasses'],
      sc: ['use the symbols ∥ and ⊥', 'construct a line through a point parallel to another line', 'construct a line through a point perpendicular to another line'],
      terms: ['Parallel', 'Perpendicular', 'Intersect'],
      we: [{ t: 'Name 2 parallel lines and 2 perpendicular lines.', fig: D.polygon({ pts: [[6, 6], [46, 6], [46, 26], [6, 26]], vlabels: ['A', 'B', 'C', 'D'], right: [0, 1, 2, 3], w: 52, h: 32 }) },
        'What does AB ⊥ CD mean? What does EF ∥ GH mean?', { t: 'Construct a line through P parallel to BC.', draw: blank(36) }, { t: 'Construct a line through X perpendicular to BC (X on BC).', draw: blank(36) },
        { t: 'Construct a line through X perpendicular to BC (X not on BC).', draw: blank(36) }, 'Name everyday examples of parallel and perpendicular lines.'],
      a: { text: 'Use the rectangle ABCD in Example 1.', kind: 'short', keepShort: true, items: ['Name a line parallel to AB.', 'Name a line perpendicular to AB.', 'Name a line parallel to BC.', 'Is AC ⊥ BD? (Draw the diagonals.)', 'Where do AB and BC intersect?', 'Write AD and BC using a symbol.'] },
      b: { text: 'True or false.', kind: 'short', items: ['Parallel lines never meet.', 'Perpendicular lines meet at 90°.', 'Two lines that intersect must be perpendicular.', 'Railway tracks are parallel.'] },
      c: { text: 'Constructions. Use a ruler and compasses.', kind: 'work', items: [{ t: 'Draw a line BC and point P above it. Construct a line through P parallel to BC.', draw: blank(52) }, { t: 'Draw a line BC with X on it. Construct a line through X perpendicular to BC.', draw: blank(52) }] },
      d: { text: 'Constructions.', kind: 'work', items: [{ t: 'Draw a line BC and point X below it. Construct the perpendicular from X to BC.', draw: blank(46) }, { t: 'Construct a square with side 4 cm using perpendicular lines.', draw: blank(46) }] },
      ext: { q: 'Construct the perpendicular bisector of a 6 cm interval AB.', steps: ['Set compasses to more than half of AB', 'Draw arcs above and below AB from A and from B', 'Join the two crossing points'], a: 'a line perpendicular to AB through its midpoint', qs: [{ t: 'Draw a 7 cm interval and construct its perpendicular bisector.', draw: blank(30) }, 'Why does the construction work? (Hint: equal distances.)'] },
      summary: { steps: ['<b>Parallel</b> (∥): same direction, never meet.', '<b>Perpendicular</b> (⊥): meet at 90°.', 'Lines that cross <b>intersect</b>.', 'Constructions use compass arcs of equal radius.'],
        worked: [['Rectangle ABCD', ['Opposite sides'], 'AB ∥ DC, AB ⊥ BC'], ['Parallel through P', ['Copy the angle or use two equal arcs'], 'a line through P that never meets BC'], ['Perpendicular through X on BC', ['Equal arcs either side of X', 'Arcs above from those points'], 'join X to the crossing point'], ['Perpendicular bisector', ['Arcs from both ends'], 'join the crossings']] },
      exit: { qs: ['What symbol means “is parallel to”?', 'Name 2 perpendicular lines in your classroom.', 'Construct a line through a point P perpendicular to a line (draw your own).'] },
      ans: { we: ['AB ∥ DC (or AD ∥ BC); AB ⊥ BC', 'AB is perpendicular to CD; EF is parallel to GH', 'construction', 'construction', 'construction', 'e.g. shelves (∥), wall and floor (⊥)'], a: ['DC', 'BC or AD', 'AD', 'No (not in a rectangle unless it is a square)', 'at B', 'AD ∥ BC'], b: ['True', 'True', 'False', 'True'], c: ['construction', 'construction'], d: ['construction', 'square construction'],
        ext: ['construction', 'every point on it is the same distance from A and B'], exit: ['∥', 'e.g. wall and floor', 'construction'] },
    }),

    lesson({
      code: '2.07', title: 'Corresponding angles',
      li: ['identify corresponding angles on parallel lines'],
      sc: ['find <b>corresponding</b> angles (F shape)', 'know they are equal on parallel lines', 'find unknown angles using them'],
      terms: ['Transversal', 'Corresponding angles'],
      we: [{ t: 'Mark the angle corresponding to the one shown.', fig: pll(60, [{ line: 'top', pos: 'ur', label: '•' }]) }, { t: 'Find <i>a</i>.', fig: pll(65, [{ line: 'top', pos: 'ur', label: '65°' }, { line: 'bottom', pos: 'ur', label: 'a°' }]) },
        { t: 'Find <i>m</i>.', fig: pll(110, [{ line: 'top', pos: 'll', label: '110°' }, { line: 'bottom', pos: 'll', label: 'm°' }]) }, 'Where is the F shape in corresponding angles?',
        { t: 'Find <i>x</i> and <i>y</i>.', fig: pll(55, [{ line: 'top', pos: 'ul', label: '125°' }, { line: 'bottom', pos: 'ul', label: 'x°' }, { line: 'bottom', pos: 'ur', label: 'y°' }]) }, 'Are corresponding angles always equal? Explain.'],
      a: { text: 'Mark the corresponding angle on the diagram.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(60, [{ line: 'top', pos: 'ul', label: '•' }]) }, { t: '', fig: pll(60, [{ line: 'bottom', pos: 'lr', label: '•' }]) }, { t: '', fig: pll(60, [{ line: 'top', pos: 'll', label: '•' }]) },
        { t: '', fig: pll(120, [{ line: 'bottom', pos: 'ur', label: '•' }]) }, { t: '', fig: pll(120, [{ line: 'top', pos: 'lr', label: '•' }]) }, { t: '', fig: pll(120, [{ line: 'bottom', pos: 'ul', label: '•' }]) }] },
      b: { text: 'Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(65, [{ line: 'top', pos: 'ur', label: '65°' }, { line: 'bottom', pos: 'ur', label: 'a°' }]) }, { t: '', fig: pll(50, [{ line: 'top', pos: 'll', label: '50°' }, { line: 'bottom', pos: 'll', label: 'k°' }]) }, { t: '', fig: pll(70, [{ line: 'bottom', pos: 'ul', label: '110°' }, { line: 'top', pos: 'ul', label: 'd°' }]) }] },
      c: { text: 'Find each variable. Give a reason.', kind: 'work', cols: 3, items: [
        { t: '', fig: pll(35, [{ line: 'top', pos: 'ur', label: '35°' }, { line: 'bottom', pos: 'ur', label: 'b°' }]) }, { t: '', fig: pll(115, [{ line: 'top', pos: 'ur', label: '115°' }, { line: 'bottom', pos: 'ur', label: 'm°' }]) },
        { t: '', fig: pll(62, [{ line: 'top', pos: 'ul', label: 'q°' }, { line: 'bottom', pos: 'ur', label: '62°' }]) }, { t: '', fig: pll(58, [{ line: 'top', pos: 'lr', label: '122°' }, { line: 'bottom', pos: 'lr', label: 'x°' }]) },
        { t: '', fig: pll(75, [{ line: 'bottom', pos: 'll', label: 'y°' }, { line: 'top', pos: 'ur', label: '75°' }]) }, { t: '', fig: pll(140, [{ line: 'top', pos: 'll', label: '140°' }, { line: 'bottom', pos: 'll', label: 't°' }]) }] },
      d: { text: 'Think it through.', kind: 'work', items: ['Explain what a transversal is.', 'Draw two parallel lines and a transversal. Mark a pair of corresponding angles.', 'If the lines are not parallel, are corresponding angles equal?', 'In Set C question 3, which angle rule did you use besides corresponding angles?'] },
      ext: { q: 'Corresponding angles are (3x + 5)° and 50°. Find x.', steps: ['Corresponding angles on parallel lines are equal', '3x + 5 = 50', '3x = 45'], a: 'x = 15', qs: ['Corresponding angles are (2y − 10)° and 70°. Find y.', 'Corresponding angles are 4a° and (a + 90)°. Find a.'] },
      summary: { steps: ['A <b>transversal</b> crosses two or more lines.', '<b>Corresponding</b> angles are in matching positions (F shape).', 'On parallel lines they are <b>equal</b>.', 'Reason: “corresponding angles, AB ∥ CD”.'],
        worked: [['Corresponding to top-right?', ['Same position at the other line'], 'bottom-right'], ['Find a', ['Corresponding angles'], 'a = 65', pll(65, [{ line: 'top', pos: 'ur', label: '65°' }, { line: 'bottom', pos: 'ur', label: 'a°' }])], ['Find x then y', ['x = 125 corresponding', 'y = 180 − 125'], 'x = 125, y = 55'], ['3x + 5 = 50', ['3x = 45'], 'x = 15']] },
      exit: { fig: pll(60, [{ line: 'top', pos: 'ur', label: '60°' }, { line: 'bottom', pos: 'ur', label: 'a°' }], { w: 50 }), qs: ['Find a.', 'What shape do corresponding angles make?', 'Corresponding angles are (2x + 20)° and 60°. Find x.'] },
      ans: { we: ['bottom line, upper right', 'a = 65', 'm = 110', 'the angles sit in an F', 'x = 125, y = 55', 'Only when the lines are parallel'], a: ['bottom ul', 'top lr', 'bottom ll', 'top ur', 'bottom lr', 'top ul'], b: ['a = 65', 'k = 50', 'd = 110'],
        c: ['b = 35', 'm = 115', 'q = 118 (corresponding 62°, then straight line)', 'x = 122', 'y = 75 (vertically opposite, then corresponding)', 't = 140'], d: ['a line crossing two or more lines', 'drawing', 'No', 'angles on a straight line'], ext: ['y = 40', 'a = 30'], exit: ['60', 'an F', 'x = 20'] },
    }),

    lesson({
      code: '2.08', title: 'Alternate angles',
      li: ['identify alternate angles on parallel lines'],
      sc: ['find <b>alternate</b> angles (Z shape)', 'know they are equal on parallel lines', 'find unknown angles using them'],
      terms: ['Alternate angles', 'Z shape'],
      we: [{ t: 'Mark the angle alternate to the one shown.', fig: pll(60, [{ line: 'top', pos: 'll', label: '•' }]) }, { t: 'Find <i>x</i>.', fig: pll(60, [{ line: 'top', pos: 'll', label: '60°' }, { line: 'bottom', pos: 'ur', label: 'x°' }]) },
        { t: 'Find <i>k</i>.', fig: pll(65, [{ line: 'top', pos: 'lr', label: '115°' }, { line: 'bottom', pos: 'ul', label: 'k°' }]) }, 'Alternate angles are between the parallel lines. True or false?',
        { t: 'Find <i>a</i> and <i>b</i>.', fig: pll(48, [{ line: 'top', pos: 'll', label: '48°' }, { line: 'bottom', pos: 'ur', label: 'a°' }, { line: 'bottom', pos: 'ul', label: 'b°' }]) }, 'Why is it called a Z shape?'],
      a: { text: 'Mark the alternate angle on the diagram.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(60, [{ line: 'top', pos: 'lr', label: '•' }]) }, { t: '', fig: pll(60, [{ line: 'bottom', pos: 'ur', label: '•' }]) }, { t: '', fig: pll(120, [{ line: 'top', pos: 'll', label: '•' }]) },
        { t: '', fig: pll(120, [{ line: 'bottom', pos: 'ul', label: '•' }]) }, { t: '', fig: pll(45, [{ line: 'top', pos: 'lr', label: '•' }]) }, { t: '', fig: pll(135, [{ line: 'bottom', pos: 'ur', label: '•' }]) }] },
      b: { text: 'Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(70, [{ line: 'top', pos: 'll', label: '70°' }, { line: 'bottom', pos: 'ur', label: 'x°' }]) }, { t: '', fig: pll(55, [{ line: 'top', pos: 'lr', label: '125°' }, { line: 'bottom', pos: 'ul', label: 'p°' }]) }, { t: '', fig: pll(38, [{ line: 'bottom', pos: 'ur', label: '38°' }, { line: 'top', pos: 'll', label: 'w°' }]) }] },
      c: { text: 'Find each variable. Give a reason.', kind: 'work', cols: 3, items: [
        { t: '', fig: pll(65, [{ line: 'top', pos: 'll', label: '65°' }, { line: 'bottom', pos: 'ur', label: 'c°' }]) }, { t: '', fig: pll(68, [{ line: 'top', pos: 'lr', label: '112°' }, { line: 'bottom', pos: 'ul', label: 't°' }]) },
        { t: '', fig: pll(50, [{ line: 'top', pos: 'll', label: '50°' }, { line: 'bottom', pos: 'ul', label: 'd°' }]) }, { t: '', fig: pll(73, [{ line: 'top', pos: 'ur', label: '73°' }, { line: 'bottom', pos: 'ur', label: 'e°' }]) },
        { t: '', fig: pll(40, [{ line: 'bottom', pos: 'ul', label: 'g°' }, { line: 'top', pos: 'lr', label: '140°' }]) }, { t: '', fig: pll(80, [{ line: 'top', pos: 'll', label: '80°' }, { line: 'bottom', pos: 'lr', label: 'h°' }]) }] },
      d: { text: 'Think it through.', kind: 'work', items: ['Draw a Z shape and mark a pair of alternate angles.', 'Alternate angles are (x + 30)° and 75°. Find x.', 'In Set C question 3, what two rules did you use?', 'Two alternate angles are 2y° and 90°. What can you say about the transversal?'] },
      ext: { q: 'Alternate angles are 5x° and (2x + 45)°. Find x and the angle size.', steps: ['Alternate angles are equal', '5x = 2x + 45, so 3x = 45', 'x = 15, angle = 5 × 15'], a: 'x = 15, angle 75°', qs: ['Alternate angles are (4a − 20)° and (2a + 30)°. Find a.', 'Alternate angles are 3m° and (m + 70)°. Find both angles.'] },
      summary: { steps: ['<b>Alternate</b> angles are on opposite sides of the transversal.', 'They are between the parallel lines (Z shape).', 'On parallel lines they are <b>equal</b>.', 'Reason: “alternate angles, AB ∥ CD”.'],
        worked: [['Alternate to top lower-left?', ['Other side, other line, inside'], 'bottom upper-right'], ['Find x', ['Alternate angles'], 'x = 60', pll(60, [{ line: 'top', pos: 'll', label: '60°' }, { line: 'bottom', pos: 'ur', label: 'x°' }])], ['Find a and b', ['a = 48 alternate', 'b = 180 − 48'], 'a = 48, b = 132'], ['5x = 2x + 45', ['3x = 45'], 'x = 15']] },
      exit: { fig: pll(65, [{ line: 'top', pos: 'll', label: '65°' }, { line: 'bottom', pos: 'ur', label: 'y°' }], { w: 50 }), qs: ['Find y.', 'What letter shape do alternate angles make?', 'Alternate angles are (3x − 15)° and 90°. Find x.'] },
      ans: { we: ['bottom line, upper right', 'x = 60', 'k = 115', 'True', 'a = 48, b = 132', 'the angles sit inside a Z'], a: ['bottom ul', 'top ll', 'bottom ur', 'top lr', 'bottom ul', 'top ll'], b: ['x = 70', 'p = 125', 'w = 38'],
        c: ['c = 65', 't = 112', 'd = 130 (alternate 50°, straight line)', 'e = 73 (corresponding)', 'g = 140', 'h = 100 (alternate 80°, then straight line)'], d: ['drawing', 'x = 45', 'alternate angles and angles on a straight line', 'It is perpendicular to both lines (y = 45)'], ext: ['a = 25', 'm = 35; both 105°'], exit: ['65', 'Z', 'x = 35'] },
    }),

    lesson({
      code: '2.09', title: 'Co-interior angles',
      li: ['identify co-interior angles on parallel lines'],
      sc: ['find <b>co-interior</b> angles (C shape)', 'know they add to 180° on parallel lines', 'find unknown angles using them'],
      terms: ['Co-interior angles', 'Supplementary'],
      we: [{ t: 'Mark the angle co-interior to the one shown.', fig: pll(60, [{ line: 'top', pos: 'lr', label: '•' }]) }, { t: 'Find <i>y</i>.', fig: pll(60, [{ line: 'top', pos: 'lr', label: '120°' }, { line: 'bottom', pos: 'ur', label: 'y°' }]) },
        { t: 'Find <i>m</i>.', fig: pll(75, [{ line: 'top', pos: 'll', label: '75°' }, { line: 'bottom', pos: 'ul', label: 'm°' }]) }, 'Are co-interior angles equal? Explain.',
        { t: 'Find <i>p</i> and <i>q</i>.', fig: pll(65, [{ line: 'top', pos: 'lr', label: '115°' }, { line: 'bottom', pos: 'ur', label: 'p°' }, { line: 'bottom', pos: 'ul', label: 'q°' }]) }, 'Name the three angle pairs on parallel lines and their rules.'],
      a: { text: 'Mark the co-interior angle on the diagram.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(60, [{ line: 'top', pos: 'll', label: '•' }]) }, { t: '', fig: pll(60, [{ line: 'bottom', pos: 'ur', label: '•' }]) }, { t: '', fig: pll(120, [{ line: 'top', pos: 'lr', label: '•' }]) },
        { t: '', fig: pll(120, [{ line: 'bottom', pos: 'ul', label: '•' }]) }, { t: '', fig: pll(45, [{ line: 'bottom', pos: 'ur', label: '•' }]) }, { t: '', fig: pll(135, [{ line: 'top', pos: 'll', label: '•' }]) }] },
      b: { text: 'Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(60, [{ line: 'top', pos: 'lr', label: '120°' }, { line: 'bottom', pos: 'ur', label: 'a°' }]) }, { t: '', fig: pll(70, [{ line: 'top', pos: 'll', label: '70°' }, { line: 'bottom', pos: 'ul', label: 'x°' }]) }, { t: '', fig: pll(35, [{ line: 'bottom', pos: 'ur', label: '35°' }, { line: 'top', pos: 'lr', label: 'b°' }]) }] },
      c: { text: 'Find each variable. Give a reason.', kind: 'work', cols: 3, items: [
        { t: '', fig: pll(62, [{ line: 'top', pos: 'lr', label: '118°' }, { line: 'bottom', pos: 'ur', label: 'q°' }]) }, { t: '', fig: pll(100, [{ line: 'top', pos: 'll', label: '100°' }, { line: 'bottom', pos: 'ul', label: 'k°' }]) },
        { t: '', fig: pll(57, [{ line: 'top', pos: 'lr', label: '123°' }, { line: 'bottom', pos: 'lr', label: 'z°' }]) }, { t: '', fig: pll(64, [{ line: 'top', pos: 'll', label: '64°' }, { line: 'bottom', pos: 'll', label: 'm°' }]) },
        { t: '', fig: pll(50, [{ line: 'bottom', pos: 'ul', label: 'x°' }, { line: 'top', pos: 'll', label: '50°' }]) }, { t: '', fig: pll(110, [{ line: 'top', pos: 'ur', label: '110°' }, { line: 'bottom', pos: 'ur', label: 'y°' }]) }] },
      d: { text: 'Think it through.', kind: 'work', items: ['Co-interior angles are x° and 2x°. Find x.', 'Co-interior angles are equal. What size are they? What does this tell you about the transversal?', 'Draw a C shape and mark co-interior angles.', 'Co-interior angles are (x + 40)° and (x + 20)°. Find x.'] },
      ext: { q: 'Co-interior angles are (2x + 10)° and (3x − 30)°. Find x.', steps: ['Co-interior angles add to 180°', '2x + 10 + 3x − 30 = 180', '5x − 20 = 180, 5x = 200'], a: 'x = 40', qs: ['Co-interior angles are 4y° and 5y°. Find both angles.', 'Co-interior angles are (a + 25)° and (2a + 5)°. Find a.'] },
      summary: { steps: ['<b>Co-interior</b> angles are on the same side of the transversal.', 'They are between the parallel lines (C shape).', 'On parallel lines they add to <b>180°</b>.', 'Reason: “co-interior angles, AB ∥ CD”.'],
        worked: [['Co-interior to top lower-right?', ['Same side, inside'], 'bottom upper-right'], ['Find y', ['y + 120 = 180'], 'y = 60', pll(60, [{ line: 'top', pos: 'lr', label: '120°' }, { line: 'bottom', pos: 'ur', label: 'y°' }])], ['p and q', ['p = 180 − 115 = 65', 'q = 180 − 65'], 'p = 65, q = 115'], ['(2x + 10) + (3x − 30) = 180', ['5x = 200'], 'x = 40']] },
      exit: { fig: pll(70, [{ line: 'top', pos: 'lr', label: '110°' }, { line: 'bottom', pos: 'ur', label: 'x°' }], { w: 50 }), qs: ['Find x.', 'What do co-interior angles add to on parallel lines?', 'Co-interior angles are 3y° and 6y°. Find y.'] },
      ans: { we: ['bottom line, upper right', 'y = 60', 'm = 105', 'No: they add to 180° (unless both are 90°)', 'p = 65, q = 115', 'corresponding (equal), alternate (equal), co-interior (add to 180°)'], a: ['bottom ul', 'top lr', 'bottom ur', 'top ll', 'top lr', 'bottom ul'], b: ['a = 60', 'x = 110', 'b = 145'],
        c: ['q = 62', 'k = 80', 'z = 123 (co-interior 57°, then straight line)', 'm = 64 (corresponding)', 'x = 130', 'y = 110 (corresponding)'], d: ['x = 60', '90° each; it is perpendicular to the parallel lines', 'drawing', 'x = 60'], ext: ['80° and 100°', 'a = 50'], exit: ['70', '180°', 'y = 20'] },
    }),

    lesson({
      code: '2.10', title: 'Finding unknown angles on parallel lines',
      li: ['use angle rules to find unknown angles on parallel lines'],
      sc: ['choose the right parallel-line rule', 'combine it with other angle rules', 'give a reason for every step'],
      terms: ['Reason', 'Parallel lines'],
      we: [{ t: 'Find <i>a</i>. Give a reason.', fig: pll(115, [{ line: 'top', pos: 'ur', label: '115°' }, { line: 'bottom', pos: 'ul', label: 'a°' }]) }, { t: 'Find <i>m</i>. Give a reason.', fig: pll(35, [{ line: 'top', pos: 'll', label: '35°' }, { line: 'bottom', pos: 'ur', label: 'm°' }]) },
        { t: 'Find <i>x</i> and <i>y</i>.', fig: pll(37, [{ line: 'top', pos: 'ur', label: '37°' }, { line: 'bottom', pos: 'ur', label: 'x°' }, { line: 'bottom', pos: 'lr', label: 'y°' }]) },
        { t: 'Find <i>k</i>.', fig: pll(115, [{ line: 'top', pos: 'lr', label: 'k°' }, { line: 'bottom', pos: 'ul', label: '65°' }]) },
        { t: 'Find <i>p</i>, <i>m</i> and <i>z</i>.', fig: pll(62, [{ line: 'top', pos: 'ur', label: '62°' }, { line: 'top', pos: 'll', label: 'p°' }, { line: 'bottom', pos: 'ur', label: 'm°' }, { line: 'bottom', pos: 'ul', label: 'z°' }]) }, 'Explain how you would find an angle if no rule gives it directly.'],
      a: { text: 'Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(115, [{ line: 'top', pos: 'ur', label: '115°' }, { line: 'bottom', pos: 'ul', label: 'a°' }]) }, { t: '', fig: pll(35, [{ line: 'top', pos: 'ur', label: '35°' }, { line: 'bottom', pos: 'ur', label: 'b°' }]) }, { t: '', fig: pll(115, [{ line: 'top', pos: 'lr', label: 'k°' }, { line: 'bottom', pos: 'ul', label: '65°' }]) },
        { t: '', fig: pll(55, [{ line: 'top', pos: 'lr', label: '125°' }, { line: 'bottom', pos: 'ul', label: 'd°' }]) }, { t: '', fig: pll(50, [{ line: 'top', pos: 'lr', label: '130°' }, { line: 'bottom', pos: 'ur', label: 'x°' }]) }, { t: '', fig: pll(62, [{ line: 'top', pos: 'ul', label: 'q°' }, { line: 'bottom', pos: 'ul', label: '118°' }]) }] },
      b: { text: 'Find each variable.', kind: 'work', cols: 3, items: [{ t: '', fig: pll(48, [{ line: 'top', pos: 'll', label: '48°' }, { line: 'bottom', pos: 'lr', label: 'y°' }]) }, { t: '', fig: pll(70, [{ line: 'top', pos: 'ul', label: '110°' }, { line: 'bottom', pos: 'lr', label: 't°' }]) }, { t: '', fig: pll(57, [{ line: 'bottom', pos: 'ur', label: '57°' }, { line: 'top', pos: 'ul', label: 'x°' }]) }] },
      c: { text: 'Find all the variables. Give reasons.', kind: 'work', cols: 3, items: [
        { t: '', fig: pll(62, [{ line: 'top', pos: 'ur', label: '62°' }, { line: 'top', pos: 'll', label: 'p°' }, { line: 'bottom', pos: 'ur', label: 'm°' }, { line: 'bottom', pos: 'ul', label: 'z°' }]) },
        { t: '', fig: pll(68, [{ line: 'top', pos: 'lr', label: '112°' }, { line: 'top', pos: 'ur', label: 't°' }, { line: 'bottom', pos: 'ul', label: 'd°' }, { line: 'bottom', pos: 'll', label: 'a°' }]) },
        { t: '', fig: pll(50, [{ line: 'top', pos: 'ul', label: '130°' }, { line: 'bottom', pos: 'ur', label: 'x°' }, { line: 'bottom', pos: 'lr', label: 'y°' }]) }] },
      d: { text: 'Harder diagrams.', kind: 'work', items: ['Two parallel lines are cut by a transversal. One angle is 57°. Find all 8 angles.', 'An angle on parallel lines is 3 times its co-interior angle. Find both angles.', 'Explain why the 4 angles at the top intersection match the 4 at the bottom.', 'Write your own question using alternate angles, with the answer 72°.'] },
      ext: { q: 'Find x if one angle is (5x − 10)° and its co-interior angle is (3x + 30)°.', steps: ['Co-interior angles add to 180°', '8x + 20 = 180', '8x = 160'], a: 'x = 20 (angles 90° and 90°)', qs: ['Alternate angles are (7x − 12)° and (4x + 36)°. Find x.', 'Corresponding angles are (x + 15)° and (2x − 25)°. Find x.'] },
      summary: { steps: ['Corresponding and alternate angles are <b>equal</b>.', 'Co-interior angles add to <b>180°</b>.', 'Use straight lines (180°) and vertically opposite angles too.', 'Give a <b>reason</b> for each step.'],
        worked: [['Find a', ['Top ur 115° → bottom ur 115° (corr.)', 'a = 180 − 115 (straight line)'], 'a = 65'], ['Find m', ['Alternate angles'], 'm = 35'], ['p, m, z', ['p = 62 (vert. opp.)', 'm = 62 (corr.)', 'z = 118 (straight line)'], 'p = 62, m = 62, z = 118'], ['5x − 10 + 3x + 30 = 180', ['8x = 160'], 'x = 20']] },
      exit: { fig: pll(58, [{ line: 'top', pos: 'ur', label: '58°' }, { line: 'bottom', pos: 'll', label: 'x°' }], { w: 50 }), qs: ['Find x.', 'Give the reason you used.', 'Find all 8 angles when one angle is 58°.'] },
      ans: { we: ['a = 65 (corresponding then straight line; or co-interior with 115° pair)', 'm = 35 (alternate)', 'x = 37 (corr.), y = 143 (straight line)', 'k = 65 (alternate)', 'p = 62, m = 62, z = 118', 'use two rules in steps, e.g. vertically opposite then alternate'],
        a: ['a = 65', 'b = 35', 'k = 65', 'd = 125', 'x = 50', 'q = 118'], b: ['y = 132 (alternate, then straight line)', 't = 110', 'x = 123'],
        c: ['p = 62, m = 62, z = 118', 't = 68, d = 112, a = 68', 'x = 130, y = 50'], d: ['four of 57° and four of 123°', '135° and 45°', 'The lines are parallel so each angle has a matching corresponding angle', 'any correct question'], ext: ['x = 16', 'x = 40'], exit: ['58', 'alternate (vertically opposite then corresponding)', 'four 58° and four 122°'] },
    }),

    lesson({
      code: '2.11', title: 'Proving lines are parallel',
      li: ['use angle rules to prove that two lines are parallel'],
      sc: ['check whether corresponding or alternate angles are equal', 'check whether co-interior angles add to 180°', 'write a conclusion: AB ∥ CD with a reason'],
      terms: ['Prove', 'Converse'],
      we: [{ t: 'Is AB ∥ CD? Give a reason.', fig: D.parallel({ tilt: 45, arrows: false, marks: [{ line: 'top', pos: 'll', label: '45°' }, { line: 'bottom', pos: 'ul', label: '135°' }], w: 50, h: 38 }) }, { t: 'Is AB ∥ CD? Give a reason.', fig: D.parallel({ tilt: 70, arrows: false, marks: [{ line: 'top', pos: 'lr', label: '110°' }, { line: 'bottom', pos: 'ur', label: '72°' }], w: 50, h: 38 }) },
        { t: 'Is AB ∥ CD? Give a reason.', fig: D.parallel({ tilt: 74, arrows: false, marks: [{ line: 'top', pos: 'ur', label: '74°' }, { line: 'bottom', pos: 'ur', label: '74°' }], w: 50, h: 38 }) },
        { t: 'Which value of x proves AB ∥ CD?', fig: D.parallel({ tilt: 95, arrows: false, marks: [{ line: 'top', pos: 'lr', label: '85°' }, { line: 'bottom', pos: 'ur', label: 'x°' }], w: 50, h: 38 }) },
        'What are the three tests for parallel lines?', 'Why do we write “converse”?'],
      a: { text: 'Is AB ∥ CD? Write yes or no.', kind: 'short', keepShort: true, items: ['Corresponding angles: 70° and 70°', 'Alternate angles: 55° and 65°', 'Co-interior angles: 120° and 60°', 'Co-interior angles: 100° and 100°', 'Alternate angles: 38° and 38°', 'Corresponding angles: 91° and 89°'] },
      b: { text: 'Is AB ∥ CD? Give a reason.', kind: 'work', cols: 3, items: [{ t: '', fig: D.parallel({ tilt: 60, arrows: false, marks: [{ line: 'top', pos: 'ur', label: '60°' }, { line: 'bottom', pos: 'ur', label: '60°' }], w: 50, h: 38 }) },
        { t: '', fig: D.parallel({ tilt: 50, arrows: false, marks: [{ line: 'top', pos: 'll', label: '50°' }, { line: 'bottom', pos: 'ur', label: '52°' }], w: 50, h: 38 }) }, { t: '', fig: D.parallel({ tilt: 65, arrows: false, marks: [{ line: 'top', pos: 'lr', label: '115°' }, { line: 'bottom', pos: 'ur', label: '65°' }], w: 50, h: 38 }) }] },
      c: { text: 'Find the value of x that makes AB ∥ CD.', kind: 'work', cols: 3, items: [
        { t: 'Corresponding: 112° and x°', fig: '' }, { t: 'Alternate: 47° and x°', fig: '' }, { t: 'Co-interior: 95° and x°', fig: '' }, { t: 'Co-interior: 2x° and 70°', fig: '' }, { t: 'Alternate: (x + 10)° and 80°', fig: '' }, { t: 'Corresponding: 3x° and 111°', fig: '' }] },
      d: { text: 'Write a proof.', kind: 'work', items: ['A transversal cuts two lines. Alternate angles are 64° and 64°. Write a full proof that the lines are parallel.', 'Co-interior angles are 108° and 72°. Prove the lines are parallel.', 'Corresponding angles are 45° and 54°. Are the lines parallel? Explain.', 'Draw a diagram where the lines are NOT parallel and explain how you know.'] },
      tallExamples: true,
      ext: { q: 'A line crosses AB and CD. The vertically opposite angle to an angle on AB is 72°, and the alternate angle on CD is 72°. Is AB ∥ CD?', steps: ['Vertically opposite angles are equal, so the angle on AB is 72°', 'Alternate angles 72° and 72° are equal'], a: 'Yes, AB ∥ CD (alternate angles equal)', qs: ['Angles on a straight line on AB are 48° and x°. The co-interior angle to x° on CD is 48°. Is AB ∥ CD?', 'Why is it not enough to measure the angles with a protractor to prove lines are parallel?'] },
      summary: { title: 'Tests for parallel lines', steps: ['Corresponding angles are <b>equal</b>, or', 'alternate angles are <b>equal</b>, or', 'co-interior angles add to <b>180°</b>.', 'Write: “AB ∥ CD (alternate angles are equal)”.'],
        worked: [['135° and 45° co-interior?', ['135 + 45 = 180'], 'AB ∥ CD'], ['110° and 72° co-interior?', ['110 + 72 = 182 ≠ 180'], 'not parallel'], ['74° and 74° corresponding', ['Equal'], 'AB ∥ CD'], ['Co-interior 85° and x°', ['x = 180 − 85'], 'x = 95']] },
      exit: { qs: ['Alternate angles are 62° and 62°. Are the lines parallel?', 'Co-interior angles are 105° and 85°. Are the lines parallel? Explain.', 'Find x so that corresponding angles (2x + 6)° and 80° make AB ∥ CD.'] },
      ans: { we: ['Yes: co-interior angles 135 + 45 = 180', 'No: 110 + 72 = 182', 'Yes: corresponding angles equal', 'x = 95', 'corresponding equal, alternate equal, co-interior supplementary', 'we use the angle to prove the lines are parallel (the reverse of the rule)'],
        a: ['yes', 'no', 'yes', 'no', 'yes', 'no'], b: ['Yes (corresponding equal)', 'No (alternate 50 ≠ 52)', 'Yes (co-interior 115 + 65 = 180)'], c: ['112', '47', '85', '55', '70', '37'],
        d: ['alternate angles equal, so parallel', '108 + 72 = 180, co-interior supplementary, so parallel', 'No: corresponding angles are not equal', 'e.g. corresponding angles 60° and 70°'], ext: ['x = 132; 132 + 48 = 180, so yes (co-interior)', 'Measurements are never exact: a proof uses the angle rules'], exit: ['Yes', 'No: 105 + 85 = 190, not 180', 'x = 37'] },
    }),
  ],
};
