// Chapter 1 Integers, research-designed lessons (lib/own.js, ../DESIGN.md). Every question is written by hand.
// Lines in a worked example or "Your turn" are the working, one step a line, answer last.
const D = require('../../lib/diagrams');

const line = (min, max, start, moves, done = true) => D.jumps({ min, max, start, moves, done, every: 1 });

module.exports = {
  '1.04': {
    canDo: 'add positive and negative integers',
    doNow: [
      { from: '1.03', q: '−7 ☐ −2&ensp;Write &lt; or &gt;.', a: '−7 &lt; −2' },
      { from: '1.03', q: 'Order smallest to largest: 4, −6, 0, −1', a: '−6, −1, 0, 4' },
      { from: '1.01', q: 'What is the opposite of −9?', a: '9' },
      { from: '1.02', q: 'Start at −4. Move 6 right. Where do you land?', a: '2' },
    ],
    think: { q: 'It is −3°C at 6 am. By noon it is 5°C warmer. What is the temperature at noon?', a: '2°C' },
    words: [
      ['sum:', 'the answer to an addition.'],
      ['−3:', 'say "negative three".'],
      ['zero pair:', '+1 and −1 make 0.'],
    ],
    big: {
      text: '<p>Start at the first number. Adding a <u>positive</u>: move <b>right</b>. Adding a <u>negative</u>: move <b>left</b>.</p>',
      figs: [line(-6, 6, -4, [5]), line(-6, 6, 3, [-5])],
    },
    pairs: [
      { ex: { q: '−5 + 3', fig: line(-7, 3, -5, [3]), lines: ['start at −5, move 3 right', '= −2'] },
        you: { q: '−6 + 4', fig: line(-7, 3, -6, [4], false), lines: ['start at −6, move 4 right', '= −2'] },
        why: { q: 'We moved right. Why?', a: 'We added a positive number (+3), and adding a positive moves right.' } },
      { ex: { q: '2 + (−5)', fig: line(-4, 4, 2, [-5]), lines: ['start at 2, move 5 left', '= −3'] },
        you: { q: '3 + (−7)', fig: line(-5, 4, 3, [-7], false), lines: ['start at 3, move 7 left', '= −4'] },
        why: { q: '2 − 5 also moves 5 left from 2. What does that tell you about 2 + (−5)?', a: '2 + (−5) is the same as 2 − 5. Adding a negative is the same as subtracting.' } },
      { ex: { q: '−4 + (−3)', lines: ['= −4 − 3', '= −7'] },
        you: { q: '−2 + (−6)', lines: ['= −2 − 6', '= −8'] },
        why: { q: 'Tom says −4 + (−3) = 7. What went wrong?', a: 'Tom used "two negatives make a positive". That rule is about multiplying, not adding. Adding a negative moves left, so −4 + (−3) = −7.' } },
    ],
    hinge: {
      q: 'Work out&ensp;−2 + 5',
      options: ['−7', '3', '−3', '7'], answer: 'B',
      why: {
        A: 'added the sizes and kept the minus sign ("symmetric" error). Re-teach with Example 1 on the number line.',
        B: 'correct.',
        C: 'moved the wrong way, or did 5 − 2 and kept the minus. Act it out: start at −2, walk 5 steps right.',
        D: 'ignored the negative sign. Check they read −2 as a place left of zero (Words box).',
      },
    },
    pattern: {
      text: 'Each question changes one thing. Work them out, then look down the answers.',
      items: [
        { q: '−3 + 3', a: '0' }, { q: '−3 + 2', a: '−1' }, { q: '−3 + 1', a: '−2' }, { q: '−3 + 0', a: '−3' },
        { q: '−3 + (−1)', a: '−4' }, { q: '−3 + (−2)', a: '−5' }, { q: '−3 + (−3)', a: '−6' }, { q: '−30 + (−30)', a: '−60' },
      ],
      notice: 'What happens to the answer each time the number added goes down by 1?',
      noticeA: 'The answer goes down by 1 too. Adding a negative carries on the pattern: it makes the answer smaller.',
    },
    drill: [
      { q: '−5 + 2', a: '−3' },
      { q: '−3 + 7', a: '4' },
      { q: '−8 + 8', a: '0' },
      { q: '−1 + 6', a: '5' },
      { q: '4 + (−6)', a: '−2' },
      { q: '2 + (−9)', a: '−7' },
      { q: '−3 + (−4)', a: '−7' },
      { q: '−7 + (−2)', a: '−9' },
      { q: '−12 + 5', a: '−7' },
      { q: '15 + (−20)', a: '−5' },
      { q: '−9 + (−9)', a: '−18' },
      { q: '−30 + 45', a: '15' },
    ],
    mixed: [
      { q: 'A diver is at −12 m. She rises 5 m. Where is she now?', a: '−12 + 5 = −7 m' },
      { q: '−6 + ☐ = −1', a: '☐ = 5' },
      { q: 'It is −9°C. It rises 4°C, then 7°C more. What is the temperature now?', a: '−9 + 4 + 7 = 2°C' },
      { from: '1.02', q: 'How far apart are −8 and 5?', a: '13' },
    ],
    further: [
      { q: 'Always, sometimes or never true? "Adding a negative number makes the answer smaller." Explain.', a: 'Always. Adding a negative always moves left, so the answer is always smaller than the starting number.' },
      { q: 'Find two integers that add to −3. Then find two more, where one of them is positive.', a: 'e.g. −1 + (−2) = −3; e.g. 2 + (−5) = −3' },
      { q: 'Start at −4. Add 2, 6 and −5 in any order. Where do you finish? Does the order matter?', a: '−4 + 2 + 6 + (−5) = −1. The order does not matter.', n: 2 },
    ],
    exit: [
      { q: '−7 + 3', a: '−4' },
      { q: '4 + (−9)', a: '−5' },
      { q: 'It is −6°C. It warms up 10°C. What is the temperature now?', a: '−6 + 10 = 4°C' },
    ],
    teacher: {
      misconception: 'Treating −2 + 5 as "−(2 + 5)" (the symmetric error), and carrying "two negatives make a positive" over from multiplication into addition.',
      next: 'Most students B: go on to page 2. Students with A, C or D: a short re-teach at the board with Examples 1 and 2 on the number line (walk it out), then Your turn 1 and 2 again before page 2. Students who finish Mixed practice: Go further.',
      think: 'Take answers without judging. Show a thermometer: start at −3, count up 5. Link to Example 1: the same move on a sideways number line.',
    },
  },
};

// ---------- the other lessons ----------
const dots = (min, max, marks, every = 1) => D.jumps({ min, max, marks, every });
const arcs = (min, max, list, marks = {}) => D.jumps({ min, max, arcs: list, marks, every: 1 });

Object.assign(module.exports, {
  '1.01': {
    canDo: 'use integers and find opposites',
    doNow: [
      { from: 'Year 6', q: 'Order smallest to largest: 12, 3, 30, 0', a: '0, 3, 12, 30' },
      { from: 'Year 6', q: 'What is 8 − 8?', a: '0' },
      { from: 'Year 6', q: 'It is 0°C. It gets 4 degrees colder. What is the temperature?', a: '−4°C' },
      { from: 'Year 6', q: 'What number is halfway between 0 and 10?', a: '5' },
    ],
    think: { q: 'A lift is at the ground floor, level 0. It goes down 2 floors to the car park. Which level is that?', a: 'level −2' },
    words: [
      ['integer:', 'a whole number: … −2, −1, 0, 1, 2 …'],
      ['opposite:', 'same distance from 0, other side.'],
      ['−(−5):', 'say "the opposite of negative five".'],
    ],
    big: {
      text: '<p>Negative numbers are left of 0. A number and its <u>opposite</u> are the same distance from 0, on opposite sides.</p>',
      figs: [arcs(-6, 6, [{ from: 0, to: 4, label: '4 steps' }, { from: 0, to: -4, label: '4 steps' }])], fh: 17,
    },
    pairs: [
      { ex: { q: 'Write an integer for 5 m below sea level.', lines: ['below 0: negative', '= −5'] },
        you: { q: 'Write an integer for a loss of $8.', lines: ['a loss: negative', '= −8'] },
        why: { q: 'Why is "below sea level" negative?', a: 'Sea level is 0. Below 0 is negative.' } },
      { fh: 17, ex: { q: 'The opposite of −6', fig: arcs(-7, 7, [{ from: 0, to: -6, label: '6' }, { from: 0, to: 6, label: '6' }], { '-6': true }), lines: ['−6 is 6 steps left of 0', 'opposite: 6'] },
        you: { q: 'The opposite of 9', fig: dots(-10, 10, { 9: true }, 2), lines: ['9 is 9 steps right of 0', 'opposite: −9'] },
        why: { q: 'What is the opposite of 0? Why?', a: '0. It is 0 steps from 0, so there is no other side.' } },
      { ex: { q: '−(−7)', lines: ['= the opposite of −7', '= 7'] },
        you: { q: '−(−11)', lines: ['= the opposite of −11', '= 11'] },
        why: { q: 'Read −(−7) aloud, using the word "opposite".', a: '"The opposite of negative seven."' } },
    ],
    hinge: {
      q: 'What is the opposite of −8?', options: ['−8', '8', '0', '−7'], answer: 'B',
      why: {
        A: 'thinks "opposite" means the same number. Re-teach with the Big idea picture: same distance, other side.',
        B: 'correct.',
        C: 'confuses opposites with a zero pair (−8 + 8 = 0). Point out: the opposite is a number, not the sum.',
        D: 'moved one step, not to the other side. Show the two equal jumps from 0.',
      },
    },
    pattern: {
      text: 'Find each one. Each question changes one thing.',
      items: [
        { q: 'opposite of 3', a: '−3' }, { q: 'opposite of 2', a: '−2' }, { q: 'opposite of 1', a: '−1' }, { q: 'opposite of 0', a: '0' },
        { q: 'opposite of −1', a: '1' }, { q: 'opposite of −2', a: '2' }, { q: '−(−2)', a: '2' }, { q: '−(−20)', a: '20' },
      ],
      notice: 'The number goes down by 1 each time. What happens to its opposite?',
      noticeA: 'The opposite goes up by 1 each time. They move in opposite directions.',
    },
    drill: [
      { q: 'opposite of 7', a: '−7' },
      { q: 'opposite of −3', a: '3' },
      { q: 'opposite of 12', a: '−12' },
      { q: 'opposite of −25', a: '25' },
      { q: 'opposite of 0', a: '0' },
      { q: '−(−4)', a: '4' },
      { q: '−(−9)', a: '9' },
      { q: '−(−15)', a: '15' },
      { q: '−(−1)', a: '1' },
      { q: '6 m below sea level', a: '−6' },
      { q: 'a gain of $10', a: '10' },
      { q: '3 floors down', a: '−3' },
    ],
    mixed: [
      { q: 'A diver is 20 m below sea level. Write this as an integer.', a: '−20' },
      { q: 'Which is further from 0: −7 or 5?', a: '−7 (7 steps, not 5)' },
      { q: 'Which two integers are 10 steps from 0?', a: '10 and −10' },
      { from: 'Year 6', q: 'List the integers between −3 and 2.', a: '−2, −1, 0, 1' },
    ],
    further: [
      { q: 'Mia says "the opposite of a number is always negative". Is she right? Explain.', a: 'No. The opposite of −3 is 3, which is positive.' },
      { q: 'Two opposites are 18 steps apart. What are they?', a: '9 and −9' },
      { q: 'Which integers from −5 to 5 are more than 3 steps from 0?', a: '−5, −4, 4, 5' },
    ],
    exit: [
      { q: 'Write an integer for 4°C below zero.', a: '−4' },
      { q: 'What is the opposite of −13?', a: '13' },
      { q: '−(−2)', a: '2' },
    ],
    teacher: {
      misconception: 'Reading the − in −5 only as "take away", so −5 feels like an action rather than a place; and thinking "opposite" means a nearby or equal number.',
      next: 'B: page 2. A, C or D: redraw the Big idea on the board, walk out from 0 both ways, then redo Your turn 2 before page 2.',
      think: 'Accept "−2", "B2" or "two down" and turn them into −2. Point out that the lift buttons often show −1, −2.',
    },
  },

  '1.02': {
    canDo: 'read number lines and find distances between integers',
    doNow: [
      { from: '1.01', q: 'What is the opposite of −4?', a: '4' },
      { from: '1.01', q: '−(−10)', a: '10' },
      { from: '1.01', q: 'Write an integer for 3 floors below ground.', a: '−3' },
      { from: 'Year 6', q: 'Count by 5s: 15, 20, 25, … What comes next?', a: '30' },
    ],
    think: { q: 'A dot is halfway between −4 and 0. What number is it at?', a: '−2' },
    words: [
      ['scale:', 'how much each gap is worth.'],
      ['distance:', 'how many steps apart. Never negative.'],
      ['halfway:', 'the same distance from both ends.'],
    ],
    big: {
      text: '<p>Numbers get larger to the right. To find a distance, count the <u>gaps</u>. Across 0? Count to 0, then on from 0.</p>',
      figs: [arcs(-4, 6, [{ from: -3, to: 0, label: '3' }, { from: 0, to: 5, label: '5' }], { '-3': true, 5: true })], fh: 15,
    },
    pairs: [
      { ex: { q: 'Which number is at the dot?', fig: dots(-6, 6, { '-3': true }, 2), lines: ['one gap left of −2', '= −3'] },
        you: { q: 'Which number is at the dot?', fig: dots(-6, 6, { 1: true }, 2), lines: ['one gap right of 0', '= 1'] },
        why: { q: 'Only every second mark has a number. How did we still find it?', a: 'Each gap is 1. Count gaps from a labelled mark.' } },
      { fh: 14.5, ex: { q: 'How far is it from −3 to 5?', fig: arcs(-4, 6, [{ from: -3, to: 0, label: '3' }, { from: 0, to: 5, label: '5' }], { '-3': true, 5: true }), lines: ['3 to 0, 5 from 0', '3 + 5 = 8'] },
        you: { q: 'How far is it from −4 to 5?', fig: dots(-5, 6, { '-4': true, 5: true }), lines: ['4 to 0, 5 from 0', '4 + 5 = 9'] },
        why: { q: 'Why do we add the two parts?', a: 'The trip passes 0. Steps to 0 plus steps from 0 make the whole trip.' } },
      { ex: { q: 'Which integer is halfway between −8 and 2?', lines: ['10 apart, half is 5', '5 right of −8: −3'] },
        you: { q: 'Which integer is halfway between −6 and 4?', lines: ['10 apart, half is 5', '5 right of −6: −1'] },
        why: { q: 'How can you check that −3 is halfway?', a: 'It is 5 steps from −8 and 5 steps from 2.' } },
    ],
    hinge: {
      q: 'How far apart are −4 and 3?', options: ['1', '7', '−7', '−1'], answer: 'B',
      why: {
        A: 'did 4 − 3, ignoring that the numbers are on opposite sides of 0. Draw it and count to 0, then on.',
        B: 'correct.',
        C: 'right size, but a distance is never negative. Revisit the Words box.',
        D: 'subtracted and kept a minus. Re-teach Example 2 on the number line.',
      },
    },
    pattern: {
      text: 'How far apart are the two numbers? Each question moves one end.',
      items: [
        { q: '−1 to 3', a: '4' }, { q: '−2 to 3', a: '5' }, { q: '−3 to 3', a: '6' }, { q: '−4 to 3', a: '7' },
        { q: '−4 to 2', a: '6' }, { q: '−4 to 1', a: '5' }, { q: '−4 to 0', a: '4' }, { q: '−4 to −1', a: '3' },
      ],
      notice: 'What happens to the distance when one end moves 1 step outwards? 1 step inwards?',
      noticeA: 'Outwards: the distance grows by 1. Inwards: it shrinks by 1.',
    },
    drill: [
      { q: 'distance −2 to 3', a: '5' },
      { q: 'distance −5 to 1', a: '6' },
      { q: 'distance −4 to −1', a: '3' },
      { q: 'distance −8 to 7', a: '15' },
      { q: 'start −3, move 5 right', a: '2' },
      { q: 'start 4, move 9 left', a: '−5' },
      { q: 'start −6, move 2 left', a: '−8' },
      { q: 'start −10, move 13 right', a: '3' },
      { q: 'halfway: −4 and 2', a: '−1' },
      { q: 'halfway: −10 and 0', a: '−5' },
      { q: 'halfway: −9 and −1', a: '−5' },
      { q: 'halfway: −7 and 5', a: '−1' },
    ],
    mixed: [
      { q: 'A number line goes −20, −10, 0, … What are the next two numbers?', a: '10, 20' },
      { q: 'Point A is at −6. Point B is 10 to the right of A. Where is B?', a: '4' },
      { q: 'A lift goes from level −3 to level 6. How many floors is that?', a: '9 floors' },
      { from: '1.01', q: '−(−3)', a: '3' },
    ],
    further: [
      { q: 'Two integers are 12 apart. Halfway between them is −2. What are they?', a: '−8 and 4' },
      { q: 'Start at −5. Move 3 right, then 8 left, then 6 right. Where do you land? How many steps did you walk?', a: 'Land on −4. 3 + 8 + 6 = 17 steps.' },
      { q: 'How many integers are between −6 and 4, not counting −6 and 4?', a: '9 (−5 to 3)' },
    ],
    exit: [
      { q: 'How far is it from −7 to 2?', a: '9' },
      { q: 'Which integer is halfway between −10 and 4?', a: '−3' },
      { q: 'Start at 3 and move 8 left. Where do you land?', a: '−5' },
    ],
    teacher: {
      misconception: 'Counting marks instead of gaps (answers one too many), and subtracting the sizes (4 − 3 = 1) when two numbers are on opposite sides of 0.',
      next: 'B: page 2. A or D: model counting to 0 then on, with fingers on the board line; redo Your turn 2. C: a quick class discussion on "distance is never negative".',
      think: 'Many will say −2 straight away. Ask how they know: "same distance from −4 and from 0". That is the halfway idea for Example 3.',
    },
  },

  '1.03': {
    canDo: 'compare and order integers',
    doNow: [
      { from: '1.02', q: 'How far is it from −5 to 3?', a: '8' },
      { from: '1.02', q: 'Start at −1 and move 6 left. Where do you land?', a: '−7' },
      { from: '1.01', q: 'What is the opposite of −15?', a: '15' },
      { from: '1.02', q: 'Which integer is halfway between −6 and 2?', a: '−2' },
    ],
    think: { q: 'Which is colder: −8°C or −3°C?', a: '−8°C' },
    words: [
      ['&lt;', 'means "is less than".'],
      ['&gt;', 'means "is greater than".'],
      ['ascending:', 'smallest to largest.'],
    ],
    big: {
      text: '<p>Further <u>right</u> means larger. So −3 &gt; −8, even though 8 is more than 3.</p>',
      figs: [dots(-9, 2, { '-8': '−8', '-3': '−3' })],
    },
    pairs: [
      { ex: { q: 'Which is larger: −9 or −4?', fig: dots(-10, 1, { '-9': true, '-4': true }), lines: ['−4 is right of −9', 'larger: −4'] },
        you: { q: 'Which is larger: −2 or −7?', fig: dots(-8, 1, { '-2': true, '-7': true }), lines: ['−2 is right of −7', 'larger: −2'] },
        why: { q: 'Sam says −9 is larger because 9 is more than 4. What would you tell Sam?', a: 'The − means left of 0. −9 is further left, so it is smaller.' } },
      { ex: { q: 'Write &lt; or &gt;:&ensp;−6 ☐ −1', lines: ['−6 is left of −1', '−6 &lt; −1'] },
        you: { q: 'Write &lt; or &gt;:&ensp;0 ☐ −5', lines: ['0 is right of −5', '0 &gt; −5'] },
        why: { q: 'How do you remember which way &lt; and &gt; point?', a: 'The open side faces the larger number.' } },
      { ex: { q: 'Order smallest to largest: 3, −5, 0, −2', lines: ['smallest: −5', '−5, −2, 0, 3'] },
        you: { q: 'Order smallest to largest: −1, 4, −6, 2', lines: ['smallest: −6', '−6, −1, 2, 4'] },
        why: { q: 'Where would your answer sit on a number line?', a: 'Left to right, in the same order.' } },
    ],
    hinge: {
      q: 'Which is the smallest?', options: ['−2', '0', '−9', '−5'], answer: 'C',
      why: {
        A: 'chose the "smallest digit" (magnitude confusion). Place all four on a number line together.',
        B: 'thinks 0 is the smallest number. Remind: negatives are less than 0.',
        C: 'correct.',
        D: 'partly there; check each pair on a number line.',
      },
    },
    pattern: {
      text: 'Write &lt; or &gt;. Each question changes one thing.',
      items: [
        { q: '3 ☐ 5', a: '&lt;' }, { q: '−3 ☐ 5', a: '&lt;' }, { q: '−3 ☐ −5', a: '&gt;' }, { q: '3 ☐ −5', a: '&gt;' },
        { q: '−5 ☐ −3', a: '&lt;' }, { q: '−30 ☐ −5', a: '&lt;' }, { q: '−5 ☐ 0', a: '&lt;' }, { q: '0 ☐ −30', a: '&gt;' },
      ],
      notice: 'Compare 1 and 3. Putting a − on both numbers did what to the sign?',
      noticeA: 'It flipped it: 3 &lt; 5 but −3 &gt; −5.',
    },
    drill: [
      { q: '−4 ☐ 2', a: '&lt;' },
      { q: '−6 ☐ −1', a: '&lt;' },
      { q: '0 ☐ −3', a: '&gt;' },
      { q: '−8 ☐ −9', a: '&gt;' },
      { q: '5 ☐ −5', a: '&gt;' },
      { q: '−12 ☐ −2', a: '&lt;' },
      { q: '−20 ☐ −19', a: '&lt;' },
      { q: '−1 ☐ −10', a: '&gt;' },
      { q: 'smaller: −7 or −3', a: '−7' },
      { q: 'larger: −15 or −51', a: '−15' },
      { q: 'smallest first: 3, −2, −5', a: '−5, −2, 3' },
      { q: 'smallest first: −1, −8, 0, −4', a: '−8, −4, −1, 0' },
    ],
    mixed: [
      { q: 'Which is colder: −15°C or −12°C?', a: '−15°C' },
      { q: 'Write an integer that is between −5 and −3.', a: '−4' },
      { q: 'Order largest to smallest: −4, 7, −10, 0', a: '7, 0, −4, −10' },
      { from: '1.02', q: 'How far is it from −11 to −2?', a: '9' },
    ],
    further: [
      { q: 'Always, sometimes or never? "A negative number is smaller than a positive number." Explain.', a: 'Always. Every negative is left of 0 and every positive is right of 0.' },
      { q: 'I am an odd integer. I am less than −2 and greater than −6. What could I be?', a: '−3 or −5' },
      { q: 'Order these coldest first: −7°C, 4°C, −12°C, 0°C. How far apart are the coldest and warmest?', a: '−12, −7, 0, 4. 16 degrees apart.' },
    ],
    exit: [
      { q: 'Write &lt; or &gt;:&ensp;−8 ☐ −3', a: '&lt;' },
      { q: 'Order smallest to largest: 2, −9, −1, −4', a: '−9, −4, −1, 2' },
      { q: 'Which is warmer: −6°C or −10°C?', a: '−6°C' },
    ],
    teacher: {
      misconception: 'Magnitude confusion: "−9 is bigger than −4 because 9 > 4". Students compare the digits and ignore the sign.',
      next: 'C: page 2. A or D: put all four numbers on one number line on the board, and read left to right. B: short reminder that negatives are below 0 (thermometer).',
      think: 'Nearly all will say −8°C. Ask: "So which number is smaller?" This is the Big idea: colder = lower = smaller.',
    },
  },

  '1.05': {
    canDo: 'subtract positive and negative integers',
    doNow: [
      { from: '1.04', q: '−7 + 4', a: '−3' },
      { from: '1.04', q: '5 + (−8)', a: '−3' },
      { from: '1.03', q: 'Write &lt; or &gt;:&ensp;−6 ☐ −2', a: '&lt;' },
      { from: '1.01', q: 'What is the opposite of −5?', a: '5' },
    ],
    think: { q: 'It is 3°C. It gets 5 degrees colder. What is the temperature now?', a: '−2°C' },
    words: [
      ['difference:', 'the answer to a subtraction.'],
      ['5 − (−3):', 'say "five subtract negative three".'],
      ['opposite:', 'swap the sign: 3 and −3.'],
    ],
    big: {
      text: '<p>Subtracting is <u>adding the opposite</u>. 5 − 3 = 5 + (−3): move left. 5 − (−3) = 5 + 3: move right.</p>',
      figs: [line(-1, 9, 5, [-3]), line(-1, 9, 5, [3])],
    },
    pairs: [
      { ex: { q: '2 − 6', fig: line(-5, 4, 2, [-6]), lines: ['start at 2, move 6 left', '= −4'] },
        you: { q: '−1 − 4', fig: line(-7, 3, -1, [-4], false), lines: ['start at −1, move 4 left', '= −5'] },
        why: { q: 'Why is 2 − 6 negative?', a: 'We took away more than we had, so we went past 0.' } },
      { ex: { q: '3 − (−4)', fig: line(-1, 8, 3, [4]), lines: ['= 3 + 4', '= 7'] },
        you: { q: '−5 − (−2)', fig: line(-7, 2, -5, [2], false), lines: ['= −5 + 2', '= −3'] },
        why: { q: 'Why does subtracting a negative move right?', a: 'Subtracting is adding the opposite. The opposite of −4 is 4, so we add 4.' } },
      { ex: { q: '−6 − (−9)', lines: ['= −6 + 9', '= 3'] },
        you: { q: '−8 − (−3)', lines: ['= −8 + 3', '= −5'] },
        why: { q: 'Ali says 3 − (−2) = 1. What went wrong?', a: 'Ali ignored the negative. 3 − (−2) = 3 + 2 = 5.' } },
    ],
    hinge: {
      q: 'Work out&ensp;4 − (−3)', options: ['1', '7', '−7', '−1'], answer: 'B',
      why: {
        A: 'treated − (−3) as − 3 (ignored the second negative). Re-teach Example 2: rewrite as + 3.',
        B: 'correct.',
        C: 'added the sizes and made it negative. Walk it on the number line.',
        D: 'did 3 − 4. Check they start at the first number.',
      },
    },
    pattern: {
      text: 'Each question subtracts 1 less than the one before.',
      items: [
        { q: '5 − 3', a: '2' }, { q: '5 − 2', a: '3' }, { q: '5 − 1', a: '4' }, { q: '5 − 0', a: '5' },
        { q: '5 − (−1)', a: '6' }, { q: '5 − (−2)', a: '7' }, { q: '5 − (−3)', a: '8' }, { q: '−5 − (−3)', a: '−2' },
      ],
      notice: 'The number subtracted goes down by 1. What happens to the answer? What does that say about subtracting a negative?',
      noticeA: 'The answer goes up by 1 each time. So subtracting a negative makes the answer larger.',
    },
    drill: [
      { q: '3 − 7', a: '−4' },
      { q: '0 − 5', a: '−5' },
      { q: '−2 − 4', a: '−6' },
      { q: '−6 − 6', a: '−12' },
      { q: '5 − (−2)', a: '7' },
      { q: '−3 − (−8)', a: '5' },
      { q: '−4 − (−4)', a: '0' },
      { q: '−9 − (−2)', a: '−7' },
      { q: '1 − 10', a: '−9' },
      { q: '−12 − 8', a: '−20' },
      { q: '7 − (−7)', a: '14' },
      { q: '−15 − (−20)', a: '5' },
    ],
    mixed: [
      { q: 'It is −4°C. It gets 7°C colder. What is the temperature now?', a: '−4 − 7 = −11°C' },
      { q: 'How much warmer is 6°C than −2°C? (warmer − colder)', a: '6 − (−2) = 8°C' },
      { q: '10 − (−5) − 20', a: '= 15 − 20 = −5' },
      { from: '1.04', q: '−3 + (−6)', a: '−9' },
    ],
    further: [
      { q: 'Is 7 − (−2) the same as 7 + 2? Use a number line to explain.', a: 'Yes. Both start at 7 and move 2 right, to 9.' },
      { q: 'Find a positive integer and a second integer whose difference (first − second) is −5.', a: 'e.g. 1 − 6 = −5' },
      { q: 'A submarine is at −120 m. A plane is at 350 m. How far apart are they?', a: '350 − (−120) = 470 m' },
    ],
    exit: [
      { q: '−2 − 7', a: '−9' },
      { q: '6 − (−5)', a: '11' },
      { q: '−4 − (−9)', a: '5' },
    ],
    teacher: {
      misconception: 'Treating − (−3) as − 3, so 4 − (−3) = 1. Students see one minus sign and ignore the other.',
      next: 'B: page 2. A: rewrite on the board, "subtract negative three = add three", and do Pattern 1–7 together. C or D: walk it on a floor or board number line.',
      think: 'Link colder to subtracting: 3 − 5 = −2. Then ask: what would "5 degrees less cold" mean? (Leads to subtracting a negative.)',
    },
  },

  '1.06': {
    canDo: 'multiply integers and choose the sign',
    doNow: [
      { from: '1.05', q: '−3 − 5', a: '−8' },
      { from: '1.05', q: '2 − (−6)', a: '8' },
      { from: '1.04', q: '(−4) + (−4) + (−4)', a: '−12' },
      { from: 'Year 6', q: '7 × 8', a: '56' },
    ],
    think: { q: 'You lose $3 a day for 4 days. By how much has your money changed?', a: '−$12 (4 × (−3))' },
    words: [
      ['product:', 'the answer to a multiplication.'],
      ['same signs:', 'both + or both −.'],
      ['different signs:', 'one + and one −.'],
    ],
    big: {
      text: '<p>Multiply the numbers, then choose the sign. <u>Same</u> signs: positive. <u>Different</u> signs: negative.</p>',
      figs: [D.groups({ n: 3, each: -2 })],
    },
    pairs: [
      { ex: { q: '3 × (−2)', fig: D.groups({ n: 3, each: -2 }), lines: ['(−2) + (−2) + (−2)', '= −6'] },
        you: { q: '4 × (−3)', fig: D.groups({ n: 4, each: -3 }), lines: ['(−3) + (−3) + (−3) + (−3)', '= −12'] },
        why: { q: 'Why is 3 × (−2) negative?', a: 'It is 3 groups of −2. Adding negatives gives a negative.' } },
      { ex: { q: '−5 × 4', lines: ['different signs: −', '5 × 4 = 20, so −20'] },
        you: { q: '6 × (−7)', lines: ['different signs: −', '6 × 7 = 42, so −42'] },
        why: { q: 'Is −5 × 4 the same as 4 × (−5)? Why?', a: 'Yes. Swapping the order does not change a product.' } },
      { ex: { q: '−3 × (−6)', lines: ['same signs: +', '3 × 6 = 18, so 18'] },
        you: { q: '−8 × (−5)', lines: ['same signs: +', '8 × 5 = 40, so 40'] },
        why: { q: 'Page 2 has a pattern that shows why − × − is positive. What does it show?', a: 'Each time the first number goes down 1, the answer goes up 4. Past 0 the answers are positive.' } },
    ],
    hinge: {
      q: 'Work out&ensp;−4 × (−5)', options: ['−20', '20', '−9', '9'], answer: 'B',
      why: {
        A: 'thinks negatives always give a negative. Go through Spot the pattern now, together.',
        B: 'correct.',
        C: 'added instead of multiplying (−4 + (−5)). Check the operation.',
        D: 'added and then used the sign rule. Check the operation.',
      },
    },
    pattern: {
      text: 'The first number goes down by 1 each time.',
      items: [
        { q: '3 × (−4)', a: '−12' }, { q: '2 × (−4)', a: '−8' }, { q: '1 × (−4)', a: '−4' }, { q: '0 × (−4)', a: '0' },
        { q: '−1 × (−4)', a: '4' }, { q: '−2 × (−4)', a: '8' }, { q: '−3 × (−4)', a: '12' }, { q: '−3 × 4', a: '−12' },
      ],
      notice: 'What happens to the answer each time? What does that show about − × −?',
      noticeA: 'It goes up by 4 each time, so −1 × (−4) = 4. Negative × negative is positive.',
    },
    drill: [
      { q: '4 × (−3)', a: '−12' },
      { q: '−5 × 2', a: '−10' },
      { q: '−6 × (−2)', a: '12' },
      { q: '7 × (−4)', a: '−28' },
      { q: '−3 × (−9)', a: '27' },
      { q: '−8 × 5', a: '−40' },
      { q: '−7 × (−7)', a: '49' },
      { q: '9 × (−6)', a: '−54' },
      { q: '−10 × (−4)', a: '40' },
      { q: '−12 × 3', a: '−36' },
      { q: '−2 × 3 × (−4)', a: '24' },
      { q: '−2 × (−2) × (−2)', a: '−8' },
    ],
    mixed: [
      { q: 'A diver goes down 5 m every minute for 6 minutes. What is her change in height?', a: '6 × (−5) = −30 m' },
      { q: '☐ × (−4) = 20', a: '☐ = −5' },
      { q: 'Which is larger: −2 × 6 or −2 × (−6)?', a: '−2 × (−6) = 12' },
      { from: '1.04', q: '−7 + (−3)', a: '−10' },
    ],
    further: [
      { q: 'Find all the pairs of integers that multiply to −12.', a: '1 and −12, −1 and 12, 2 and −6, −2 and 6, 3 and −4, −3 and 4' },
      { q: 'Always, sometimes or never? "Negative × negative × negative is negative." Explain.', a: 'Always. The first two give a positive; positive × negative is negative.' },
      { q: 'Work out (−1) × (−1) × (−1) × (−1) × (−1). What if there were 100 of them?', a: '−1. With 100 of them, +1 (they pair up).' },
    ],
    exit: [
      { q: '−6 × 4', a: '−24' },
      { q: '−9 × (−2)', a: '18' },
      { q: 'The temperature falls 3°C each hour for 5 hours. What is the total change?', a: '5 × (−3) = −15°C' },
    ],
    teacher: {
      misconception: 'Believing a negative × a negative is negative ("negative means less"), and, from the other side, using "two negatives make a positive" when adding.',
      next: 'B: page 2. A: do Spot the pattern together on the board before page 2. C or D: underline the operation sign in each question before answering.',
      think: 'Write 4 × (−3) = −12 from their answers. This is Example 1: repeated addition of a negative.',
    },
  },

  '1.07': {
    canDo: 'divide integers and choose the sign',
    doNow: [
      { from: '1.06', q: '−6 × 7', a: '−42' },
      { from: '1.06', q: '−4 × (−8)', a: '32' },
      { from: '1.05', q: '−2 − 9', a: '−11' },
      { from: '1.03', q: 'Order smallest to largest: −4, 2, −8', a: '−8, −4, 2' },
    ],
    think: { q: 'A debt of $24 is shared equally by 4 people. How much does each person owe?', a: '$6 each (−24 ÷ 4 = −6)' },
    words: [
      ['quotient:', 'the answer to a division.'],
      ['fact family:', '3 × (−4) = −12, so −12 ÷ 3 = −4.'],
      ['share:', 'split into equal groups.'],
    ],
    big: {
      text: '<p>Division undoes multiplication, so the sign rules are the same. <u>Same</u> signs: positive. <u>Different</u> signs: negative.</p>',
      figs: [D.groups({ n: 3, each: -4 })],
    },
    pairs: [
      { ex: { q: '−12 ÷ 3', fig: D.groups({ n: 3, each: -4 }), lines: ['3 × (−4) = −12', 'so −12 ÷ 3 = −4'] },
        you: { q: '−15 ÷ 5', fig: D.groups({ n: 5, each: -3 }), lines: ['5 × (−3) = −15', 'so −15 ÷ 5 = −3'] },
        why: { q: 'How does the × fact help with the ÷?', a: 'Division undoes multiplication, so the × fact gives the ÷ answer.' } },
      { ex: { q: '28 ÷ (−4)', lines: ['different signs: −', '28 ÷ 4 = 7, so −7'] },
        you: { q: '−36 ÷ 9', lines: ['different signs: −', '36 ÷ 9 = 4, so −4'] },
        why: { q: 'How can you check that 28 ÷ (−4) = −7?', a: 'Multiply back: −7 × (−4) = 28.' } },
      { ex: { q: '−30 ÷ (−6)', lines: ['same signs: +', '30 ÷ 6 = 5, so 5'] },
        you: { q: '−48 ÷ (−8)', lines: ['same signs: +', '48 ÷ 8 = 6, so 6'] },
        why: { q: 'Jo says −30 ÷ (−6) = −5. What went wrong?', a: 'Same signs give a positive. The answer is 5.' } },
    ],
    hinge: {
      q: 'Work out&ensp;−20 ÷ (−4)', options: ['−5', '5', '−16', '80'], answer: 'B',
      why: {
        A: 'kept the negative. Check by multiplying back: −5 × (−4) = 20, not −20.',
        B: 'correct.',
        C: 'subtracted: −20 − (−4). Check the operation.',
        D: 'multiplied. Check the operation.',
      },
    },
    pattern: {
      text: 'Each question changes one sign or one number.',
      items: [
        { q: '12 ÷ 3', a: '4' }, { q: '−12 ÷ 3', a: '−4' }, { q: '12 ÷ (−3)', a: '−4' }, { q: '−12 ÷ (−3)', a: '4' },
        { q: '−12 ÷ (−4)', a: '3' }, { q: '−12 ÷ (−6)', a: '2' }, { q: '−12 ÷ 6', a: '−2' }, { q: '−120 ÷ (−6)', a: '20' },
      ],
      notice: 'Which answers are negative? What do their questions have in common?',
      noticeA: '2, 3 and 7. Each one has different signs.',
    },
    drill: [
      { q: '−12 ÷ 3', a: '−4' },
      { q: '−20 ÷ 5', a: '−4' },
      { q: '18 ÷ (−6)', a: '−3' },
      { q: '−24 ÷ (−8)', a: '3' },
      { q: '−35 ÷ 7', a: '−5' },
      { q: '42 ÷ (−7)', a: '−6' },
      { q: '−36 ÷ (−4)', a: '9' },
      { q: '−50 ÷ 10', a: '−5' },
      { q: '−64 ÷ (−8)', a: '8' },
      { q: '81 ÷ (−9)', a: '−9' },
      { q: '−100 ÷ (−25)', a: '4' },
      { q: '−60 ÷ 4 ÷ (−3)', a: '= −15 ÷ (−3) = 5' },
    ],
    mixed: [
      { q: '☐ ÷ 4 = −5', a: '☐ = −20' },
      { q: 'The temperature fell 18°C in 6 hours, the same each hour. What was the change each hour?', a: '−18 ÷ 6 = −3°C' },
      { q: '−80 ÷ 4 ÷ (−2)', a: '= −20 ÷ (−2) = 10' },
      { from: '1.06', q: '−6 × 7', a: '−42' },
    ],
    further: [
      { q: 'Find the average of −6, 2, −5 and −3. (Add them, then divide by 4.)', a: 'Total −12, so −12 ÷ 4 = −3' },
      { q: 'Write three different divisions that have the answer −4.', a: 'e.g. −8 ÷ 2, 12 ÷ (−3), −20 ÷ 5' },
      { q: 'Always, sometimes or never? "Dividing makes a number smaller." Explain.', a: 'Sometimes. −12 ÷ 3 = −4, and −4 is larger than −12.' },
    ],
    exit: [
      { q: '−35 ÷ 5', a: '−7' },
      { q: '−72 ÷ (−8)', a: '9' },
      { q: 'A debt of $60 is shared by 3 people. Write each share as an integer.', a: '−60 ÷ 3 = −20' },
    ],
    teacher: {
      misconception: 'Keeping the negative when both numbers are negative (−20 ÷ (−4) = −5), usually from not linking ÷ to × facts.',
      next: 'B: page 2. A: model "multiply back to check" on three examples. C or D: underline the operation before answering.',
      think: 'Write −24 ÷ 4 = −6: the share of a debt is itself a debt. Link to Example 1.',
    },
  },

  '1.08': {
    canDo: 'use the order of operations with integers',
    doNow: [
      { from: '1.07', q: '−18 ÷ 3', a: '−6' },
      { from: '1.06', q: '−4 × (−6)', a: '24' },
      { from: '1.05', q: '5 − 9', a: '−4' },
      { from: '1.04', q: '−8 + 3', a: '−5' },
    ],
    think: { q: 'Two students work out 2 + 3 × 4. One gets 20. One gets 14. Who is right?', a: '14 (× first: 2 + 12)' },
    words: [
      ['order of operations:', 'brackets, then × and ÷, then + and −.'],
      ['left to right:', 'for a tie, work from left to right.'],
      ['evaluate:', 'work out the value.'],
    ],
    big: {
      text: '<p>1. <u>Brackets</u>. 2. × and ÷, left to right. 3. + and −, left to right. The integer rules still work at every step.</p>',
    },
    pairs: [
      { ex: { q: '−3 + 4 × 2', lines: ['= −3 + 8', '= 5'] },
        you: { q: '−10 + 3 × 2', lines: ['= −10 + 6', '= −4'] },
        why: { q: 'Why do we do 4 × 2 first?', a: '× comes before + in the order of operations.' } },
      { ex: { q: '(−3 + 7) × 2', lines: ['= 4 × 2', '= 8'] },
        you: { q: '(1 − 6) × 3', lines: ['= −5 × 3', '= −15'] },
        why: { q: 'How did the brackets change the answer?', a: 'Brackets go first, so we add before multiplying. Without them, −3 + 7 × 2 = 11.' } },
      { ex: { q: '6 − 2 × (−3)', lines: ['= 6 − (−6)', '= 6 + 6', '= 12'] },
        you: { q: '−5 − 4 × (−2)', lines: ['= −5 − (−8)', '= −5 + 8', '= 3'] },
        why: { q: 'Mia says 6 − 2 × (−3) = −12. What went wrong?', a: 'She did 6 − 2 first. × comes first: 6 − (−6) = 12.' } },
    ],
    hinge: {
      q: 'Work out&ensp;10 − 3 × (−2)', options: ['−14', '4', '16', '−16'], answer: 'C',
      why: {
        A: 'worked left to right: 10 − 3 = 7, 7 × (−2) = −14. Re-teach the order.',
        B: 'did × first but lost the second negative: 10 − 6. Re-teach Example 3.',
        C: 'correct.',
        D: 'sign errors at both steps. Do it step by step on the board.',
      },
    },
    pattern: {
      text: 'The same numbers, with one change each time.',
      items: [
        { q: '2 + 3 × 4', a: '14' }, { q: '2 − 3 × 4', a: '−10' }, { q: '−2 − 3 × 4', a: '−14' }, { q: '−2 − 3 × (−4)', a: '10' },
        { q: '(−2 − 3) × (−4)', a: '20' }, { q: '(−2 + 3) × (−4)', a: '−4' }, { q: '−2 + 3 × (−4)', a: '−14' }, { q: '−20 + 30 × (−4)', a: '−140' },
      ],
      notice: 'Find two questions with the same numbers but different answers. What made them different?',
      noticeA: 'e.g. 4 and 5: −2 − 3 × (−4) = 10 but (−2 − 3) × (−4) = 20. The brackets changed the order.',
    },
    drill: [
      { q: '−4 + 2 × 3', a: '2' },
      { q: '5 − 3 × 4', a: '−7' },
      { q: '−2 × 3 + 1', a: '−5' },
      { q: '(−2 + 5) × 2', a: '6' },
      { q: '(1 − 4) × 3', a: '−9' },
      { q: '−12 ÷ 3 + 6', a: '2' },
      { q: '8 − 10 ÷ 2', a: '3' },
      { q: '−3 × (−2) − 7', a: '−1' },
      { q: '(−6 − 2) ÷ 4', a: '−2' },
      { q: '−10 + 4 × (−2)', a: '−18' },
      { q: '6 − 2 × (−5)', a: '16' },
      { q: '−20 ÷ 5 × 2', a: '−8' },
    ],
    mixed: [
      { q: '−2 × 3 + 4 × (−2)', a: '= −6 + (−8) = −14' },
      { q: '(−9 + 3) ÷ (−2)', a: '= −6 ÷ (−2) = 3' },
      { q: '−3 × (2 − 6)', a: '= −3 × (−4) = 12' },
      { from: '1.07', q: '−12 ÷ (−4)', a: '3' },
    ],
    further: [
      { q: 'Put brackets in to make it true: −4 + 6 × 3 = 6', a: '(−4 + 6) × 3 = 6' },
      { q: 'Use −2, 3 and 5 once each, with + and ×, and brackets if you like. What is the smallest answer you can make?', a: '−2 × (3 + 5) = −16' },
      { q: 'Write a calculation with brackets, × and − that has the answer −12.', a: 'e.g. (2 − 5) × 4 = −12' },
    ],
    exit: [
      { q: '−6 + 2 × 4', a: '= −6 + 8 = 2' },
      { q: '(−6 + 2) × 4', a: '= −4 × 4 = −16' },
      { q: '9 − 3 × (−2)', a: '= 9 − (−6) = 15' },
    ],
    teacher: {
      misconception: 'Working strictly left to right (10 − 3 × (−2) = −14), and losing a negative when subtracting a negative product.',
      next: 'C: page 2. A: re-teach the order with the Think first example. B or D: model Example 3, one line at a time, saying each step aloud.',
      think: 'Both methods are "reasonable"; the order of operations is an agreement so everyone gets the same answer. 14 is right.',
    },
  },

  '1.09': {
    canDo: 'use a calculator with integers and check answers',
    doNow: [
      { from: '1.08', q: '−3 + 2 × 5', a: '7' },
      { from: '1.08', q: '(4 − 9) × 2', a: '−10' },
      { from: '1.07', q: '−56 ÷ 8', a: '−7' },
      { from: '1.06', q: '−7 × (−6)', a: '42' },
    ],
    think: { q: 'Without a calculator: is −48 × 21 about −100, about −1 000, or about −10 000?', a: 'About −1 000 (−50 × 20)' },
    words: [
      ['(−) key:', 'makes a number negative.'],
      ['− key:', 'subtracts.'],
      ['estimate:', 'a quick answer from rounded numbers.'],
    ],
    big: {
      text: '<p>Use <u>(−)</u> for a negative number, − to subtract. Got a +/− key? Press it after the number. Estimate first, then check.</p>',
      figs: [D.keys(['(−)', '4', '8', '×', '2', '1', '='])],
    },
    pairs: [
      { ex: { q: '−37 + 85', lines: ['keys: (−) 37 + 85 =', '= 48'] },
        you: { q: '−126 + 59', lines: ['keys: (−) 126 + 59 =', '= −67'] },
        why: { q: 'What could go wrong if you pressed − instead of (−) at the start?', a: 'Many calculators would subtract 37 from the last answer, instead of starting at −37.' } },
      { ex: { q: '−48 × 21', lines: ['estimate: −50 × 20 = −1 000', '= −1 008'] },
        you: { q: '−39 × 31', lines: ['estimate: −40 × 30 = −1 200', '= −1 209'] },
        why: { q: 'How does the estimate help?', a: 'It checks the sign and the size. −1 008 is close to −1 000.' } },
      { ex: { q: '(−35 − 47) × 12', lines: ['bracket: −82', '= −984'] },
        you: { q: '(−28 + 13) × (−6)', lines: ['bracket: −15', '= 90'] },
        why: { q: 'Why must you type the brackets?', a: 'Without them, the calculator works out 47 × 12 first.' } },
    ],
    hinge: {
      q: 'Ella presses&ensp;(−) 6 − 4 =&ensp;What does her calculator show?', options: ['−2', '2', '−10', '10'], answer: 'C',
      why: {
        A: 'read it as −6 + 4 or as 6 − 4 with a minus. Say it aloud: "negative six, subtract four".',
        B: 'ignored the (−) key. Re-teach the two keys.',
        C: 'correct.',
        D: 'ignored the negative and added. Re-teach the two keys.',
      },
    },
    pattern: {
      text: 'Use your calculator. Each question changes one thing.',
      items: [
        { q: '−25 × 4', a: '−100' }, { q: '−25 × 8', a: '−200' }, { q: '−25 × 12', a: '−300' }, { q: '−25 × 16', a: '−400' },
        { q: '−25 × (−16)', a: '400' }, { q: '25 × (−16)', a: '−400' }, { q: '−250 × 16', a: '−4 000' }, { q: '−250 × (−160)', a: '40 000' },
      ],
      notice: 'What happens when one number gets bigger by 4? When one sign changes?',
      noticeA: 'Adding 4 to the second number adds −100 to the answer. Changing one sign changes the sign of the answer.',
    },
    drill: [
      { q: '−347 + 128', a: '−219' },
      { q: '−95 − 187', a: '−282' },
      { q: '−504 + 769', a: '265' },
      { q: '−56 × 23', a: '−1 288' },
      { q: '68 × (−45)', a: '−3 060' },
      { q: '−37 × (−29)', a: '1 073' },
      { q: '−125 × (−24)', a: '3 000' },
      { q: '−2 016 ÷ 42', a: '−48' },
      { q: '−1 248 ÷ (−24)', a: '52' },
      { q: '−4 785 ÷ 87', a: '−55' },
      { q: '(−64 − 36) × 15', a: '= −100 × 15 = −1 500' },
      { q: '(−18 + 7) × (−33)', a: '= −11 × (−33) = 363' },
    ],
    mixed: [
      { q: 'Estimate −62 × 19. Then use your calculator.', a: '≈ −60 × 20 = −1 200; −1 178' },
      { q: 'A submarine at −185 m rises 12 m a minute for 9 minutes. Where is it now?', a: '−185 + 9 × 12 = −77 m' },
      { q: 'Use your calculator to find the missing number: −23 × ☐ = 1 403', a: '☐ = 1 403 ÷ (−23) = −61' },
      { from: '1.08', q: 'No calculator: −6 + 3 × (−2)', a: '= −6 + (−6) = −12' },
    ],
    further: [
      { q: 'Use your calculator to find the missing number: −37 × ☐ = 1 147', a: '☐ = 1 147 ÷ (−37) = −31' },
      { q: 'A student gets 1 008 for −48 × 21. How can you tell it is wrong without working it out?', a: 'Different signs, so the answer must be negative. It should be −1 008.' },
      { q: 'Moscow had these temperatures: −12, −8, −15, −3 and −7°C. Find the average.', a: 'Total −45, so −45 ÷ 5 = −9°C' },
    ],
    exit: [
      { q: '−234 + 97', a: '−137' },
      { q: '−38 × (−27)', a: '1 026' },
      { q: '(−45 − 27) ÷ 8', a: '= −72 ÷ 8 = −9' },
    ],
    teacher: {
      misconception: 'Using the subtract key for a negative number, and trusting the calculator display without checking the sign or size.',
      next: 'C: page 2. A, B or D: everyone presses (−) 6 − 4 = together and says it aloud. Check which key each calculator model uses (some use +/− after the number).',
      think: 'Round to −50 × 20. The point: an estimate tells you the size and the sign before you touch the calculator.',
    },
  },

  '1.10': {
    canDo: 'solve problems with integers',
    drillCols: 2,
    doNow: [
      { from: '1.07', q: '−144 ÷ 12', a: '−12' },
      { from: '1.08', q: '−2 × (3 − 7)', a: '8' },
      { from: '1.05', q: '−5 − (−8)', a: '3' },
      { from: '1.03', q: 'Which is warmer: −14°C or −9°C?', a: '−9°C' },
    ],
    think: { q: 'A lift at level −2 goes up 6 floors, then down 3 floors. Which level is it on now?', a: 'level 1' },
    words: [
      ['balance:', 'how much money is in an account.'],
      ['overdrawn:', 'the balance is below $0.'],
      ['change:', 'new − old.'],
    ],
    big: {
      text: '<p>Read the story. Write a number sentence. Up, rise, earn: <u>+</u>. Down, fall, spend: <u>−</u>. A change that repeats: <u>×</u>.</p>',
    },
    pairs: [
      { ex: { q: 'It is −4°C at 6 am. By noon it is 9°C warmer. What is the temperature at noon?', lines: ['−4 + 9', '= 5°C'] },
        you: { q: 'It is 3°C at 6 pm. By midnight it is 8°C colder. What is the temperature at midnight?', lines: ['3 − 8', '= −5°C'] },
        why: { q: 'How did you choose + or −?', a: 'Warmer means up (+). Colder means down (−).' } },
      { ex: { q: 'Sam has $45. Sam spends $70. What is the balance?', lines: ['45 − 70', '= −$25'] },
        you: { q: 'Ana has −$30. She is paid $55. What is her balance?', lines: ['−30 + 55', '= $25'] },
        why: { q: 'What does a balance of −$25 mean?', a: 'Sam owes the bank $25.' } },
      { ex: { q: 'A diver at −10 m goes down 3 m a minute for 4 minutes. Where is she now?', lines: ['4 × (−3) = −12', '−10 + (−12) = −22 m'] },
        you: { q: 'A diver at −40 m rises 5 m a minute for 6 minutes. Where is she now?', lines: ['6 × 5 = 30', '−40 + 30 = −10 m'] },
        why: { q: 'Why multiply first?', a: 'The same change happens 4 times, so the total change is 4 × (−3).' } },
    ],
    hinge: {
      q: 'A gull is at 15 m. A shark is at −20 m. How far apart are they?', options: ['5 m', '35 m', '−5 m', '−35 m'], answer: 'B',
      why: {
        A: 'did 20 − 15, ignoring that they are on opposite sides of 0. Draw a vertical number line.',
        B: 'correct: 15 − (−20) = 35.',
        C: 'did 15 + (−20). A distance is higher − lower, and never negative.',
        D: 'right size, but a distance is never negative.',
      },
    },
    pattern: {
      text: 'All four operations with −5. Each changes one thing.',
      items: [
        { q: '−5 + 8', a: '3' }, { q: '−5 + 5', a: '0' }, { q: '−5 + 2', a: '−3' }, { q: '−5 − 2', a: '−7' },
        { q: '−5 − (−2)', a: '−3' }, { q: '−5 × 2', a: '−10' }, { q: '−5 × (−2)', a: '10' }, { q: '−5 ÷ (−5)', a: '1' },
      ],
      notice: 'Which two questions have the same answer? Why?',
      noticeA: '3 and 5 are both −3: subtracting −2 is the same as adding 2.',
    },
    drill: [
      { q: '−5°C, then rises 8°C', a: '3°C' },
      { q: '4°C, then falls 9°C', a: '−5°C' },
      { q: '−2°C, then falls 6°C', a: '−8°C' },
      { q: '−11°C, then rises 11°C', a: '0°C' },
      { q: 'level −3, then up 5', a: 'level 2' },
      { q: 'level 4, then down 6', a: 'level −2' },
      { q: 'have $10, spend $25', a: '−$15' },
      { q: 'have −$20, earn $30', a: '$10' },
      { q: 'apart: 15 m and −10 m', a: '25 m' },
      { q: 'apart: −4 m and −19 m', a: '15 m' },
      { q: 'down 3 m a minute, 5 min', a: '−15 m' },
      { q: 'falls 2°C an hour, 6 h', a: '−12°C' },
    ],
    mixed: [
      { q: 'A quiz: +3 if right, −1 if wrong. Kai gets 6 right, 5 wrong. His score?', a: '6 × 3 + 5 × (−1) = 18 + (−5) = 13' },
      { q: 'A balance is $20. You spend $35, then earn $10. Balance?', a: '20 − 35 + 10 = −$5' },
      { q: 'A plane is at 900 m. A submarine is at −150 m. How far apart are they?', a: '900 − (−150) = 1 050 m' },
      { from: '1.03', q: 'Order coldest first: −3°C, −13°C, 3°C, 0°C', a: '−13, −3, 0, 3' },
    ],
    further: [
      { q: 'In the quiz, Lea answered 10 questions and scored 14. How many were right?', a: '6 right: 6 × 3 + 4 × (−1) = 18 − 4 = 14' },
      { q: 'It is −6°C. It warms 2°C an hour for 12 hours, then cools 3°C an hour for 4 hours. Temperature?', a: '−6 + 12 × 2 − 4 × 3 = −6 + 24 − 12 = 6°C' },
    ],
    exit: [
      { q: 'It is −7°C. It rises 11°C. What is the temperature now?', a: '−7 + 11 = 4°C' },
      { q: 'A balance is $15. You spend $40. What is the balance?', a: '15 − 40 = −$25' },
      { q: 'A diver at −8 m goes down 2 m a minute for 5 minutes. Where is she?', a: '−8 + 5 × (−2) = −18 m' },
    ],
    teacher: {
      misconception: 'Choosing the operation from key words alone, and treating "how far apart" as a subtraction of sizes when the two numbers are on opposite sides of 0.',
      next: 'B: page 2. A, C or D: draw a vertical number line (sea level at 0) and count 15 up and 20 down.',
      think: '−2 + 6 − 3 = 1. Ask students to act it out with a finger on a vertical number line.',
    },
  },
});

// The chapter review: mixed questions from every lesson.
module.exports.REVIEW = [
  { from: '1.01', q: 'What is the opposite of −17?', a: '17' },
  { from: '1.01', q: '−(−8)', a: '8' },
  { from: '1.02', q: 'How far is it from −6 to 9?', a: '15' },
  { from: '1.02', q: 'Which integer is halfway between −14 and 2?', a: '−6' },
  { from: '1.03', q: 'Write &lt; or &gt;:&ensp;−12 ☐ −21', a: '&gt;' },
  { from: '1.03', q: 'Order smallest to largest: 5, −8, 0, −3, −10', a: '−10, −8, −3, 0, 5' },
  { from: '1.04', q: '−9 + 14', a: '5' },
  { from: '1.04', q: '3 + (−11)', a: '−8' },
  { from: '1.05', q: '−4 − 7', a: '−11' },
  { from: '1.05', q: '−2 − (−10)', a: '8' },
  { from: '1.06', q: '−7 × 8', a: '−56' },
  { from: '1.06', q: '−6 × (−9)', a: '54' },
  { from: '1.07', q: '−81 ÷ 9', a: '−9' },
  { from: '1.07', q: '−64 ÷ (−8)', a: '8' },
  { from: '1.08', q: '−5 + 3 × (−4)', a: '= −5 + (−12) = −17' },
  { from: '1.08', q: '(−5 + 3) × (−4)', a: '= −2 × (−4) = 8' },
  { from: '1.09', q: 'Calculator: −384 ÷ 16', a: '−24' },
  { from: '1.09', q: 'Calculator: (−73 + 28) × 11', a: '= −45 × 11 = −495' },
  { from: '1.10', q: 'It is −3°C. It falls 9°C. What is the temperature now?', a: '−3 − 9 = −12°C' },
  { from: '1.10', q: 'A diver at −25 m rises 4 m a minute for 5 minutes. Where is she now?', a: '−25 + 5 × 4 = −5 m' },
  { from: '1.10', q: 'How far apart are 40 m and −35 m?', a: '40 − (−35) = 75 m' },
  { from: '1.06', q: '−2 × (−3) × (−5)', a: '= 6 × (−5) = −30' },
  { from: '1.05', q: 'Is 6 − (−4) the same as 6 + 4? Explain.', a: 'Yes. Subtracting −4 is adding its opposite, 4. Both are 10.' },
  { from: '1.08', q: 'Put brackets in to make it true: 2 − 8 × 3 = −18', a: '(2 − 8) × 3 = −18' },
];
