// Year 7 Chapter 1: Integers. One 4-page lesson per exercise in Test Yourself 1.
const lesson = require('../../lib/lesson');
const D = require('../../lib/diagrams');
const { ev } = require('../../lib/calc');
const evs = (xs) => xs.map((e) => ev(e));
const nl = (o) => `<div class="template-card">${D.numberLine({ w: 88, h: 18, ...o })}</div>`;

module.exports = {
  year: 7, stage: 4, number: 1, title: 'Integers', accent: '#c0392b',
  fileName: 'Year7-Ch01-Integers',
  goals: ['understand positive and negative numbers and their opposites', 'use a number line to show and compare integers', 'order integers',
    'add, subtract, multiply and divide integers', 'use the order of operations with integers, with and without a calculator', 'solve problems involving integers'],
  syllabus: 'NSW Mathematics K–10 Syllabus (2022), Stage 4 Number and algebra: MA4-INT-C-01 compares, orders and calculates with integers to solve problems.',
  lessons: [
    lesson({
      code: '1.01', title: 'Integers and opposites',
      li: ['understand what an integer is', 'write the opposite of an integer'],
      sc: ['describe a real situation with a positive or negative number', 'write the <b>opposite</b> of any integer', 'explain why 0 is its own opposite'],
      terms: ['Integer', 'Negative number', 'Opposite'],
      we: ['Write an integer for: a temperature 6°C below zero; a gain of 4 metres.', 'Write the opposite of: −9, 15, 0', 'A lift goes 3 floors down, then 3 floors up. Write both moves as integers. Where does it end?', 'Which is further from 0: −8 or 6? Explain using opposites.', 'The opposite of a number is 25. What is the number?', 'List the integers whose distance from 0 is exactly 7.'],
      a: { text: 'Write an integer for each situation.', kind: 'short', keepShort: true, items: ['5°C below zero', 'a profit of $40', '12 m below sea level', 'a rise of 8 floors', 'a loss of 3 kg', '200 m above sea level'] },
      b: { text: 'Write the <b>opposite</b> of each integer.', kind: 'short', items: ['−2', '−23', '56', '−10', '8', '0'] },
      c: { text: 'Opposites in real life.', kind: 'work', items: ['What is the opposite of “3 steps forward”? Write both as integers.', 'A diver is at −14 m. What is the opposite position?', 'Write the opposite of the opposite of −7.',
        'Which is further from 0: −12 or 9?', 'Write two integers that are 5 units from 0.', 'A bank balance of −$60 means what?'] },
      d: { text: 'Think it through.', kind: 'work', items: ['Is −0 different from 0? Explain.', 'The opposite of a number is 18. What is the number?', 'List all integers whose distance from 0 is less than 3.', 'Does every integer have an opposite? Explain.'] },
      tallExamples: true,
      ext: { q: 'The opposite of <i>n</i> is written −<i>n</i>. If <i>n</i> = −4, what is −<i>n</i>?', steps: ['−<i>n</i> means “the opposite of <i>n</i>”', 'The opposite of −4 is 4'], a: '−<i>n</i> = 4', qs: ['If <i>n</i> = −11, find −<i>n</i> and −(−<i>n</i>).', 'Is −<i>n</i> always a negative number? Give an example.'] },
      summary: { steps: ['<b>Integers</b> are whole numbers: …, −2, −1, 0, 1, 2, …', 'Negative numbers are below zero.', 'The <b>opposite</b> is the same distance from 0 on the other side.', '0 is its own opposite.'],
        worked: [['Write −7 as a real situation.', ['Negative means below or less'], '7°C below zero'], ['Opposite of −23?', ['Same distance, other side of 0'], '23'], ['Which integers are 4 from 0?', ['One on each side of 0'], '4 and −4'], ['If <i>n</i> = −6, find −<i>n</i>.', ['Opposite of −6'], '6']] },
      exit: { qs: ['Write the opposite of −15.', 'Write an integer for “a drop of 9°C”, then write its opposite.', 'The opposite of a number is −31. What is the number? Explain.'] },
      ans: { we: ['−6; +4', '9, −15, 0', '−3, +3; back where it started', '−8 (8 units from 0)', '−25', '7 and −7'], a: ['−5', '40', '−12', '8', '−3', '200'], b: ['2', '23', '−56', '10', '−8', '0'],
        c: ['3 steps back; +3 and −3', '+14 m (14 m above sea level)', '−7', '−12 (12 units from 0)', '5 and −5', 'You owe $60 (overdrawn)'],
        d: ['No, −0 = 0', '−18', '−2, −1, 0, 1, 2', 'Yes: every integer has an opposite (0 is its own)'], ext: ['11; −11', 'No: if n is negative, −n is positive (e.g. n = −3, −n = 3)'], exit: ['15', '−9; 9', '31, because the opposite of 31 is −31'] },
    }),

    lesson({
      code: '1.02', title: 'The number line',
      li: ['show integers on a number line', 'find integers between two numbers'],
      sc: ['draw a number line with an even scale', 'mark positive and negative integers in the right places', 'list the integers <b>between</b> two numbers'],
      terms: ['Number line', 'Positive', 'Negative'],
      we: [{ t: 'Mark 3, −2, 0 and −5 on the number line.', draw: nl({ min: -6, max: 6 }) }, { t: 'Mark the integers between −3 and 2.', draw: nl({ min: -6, max: 6 }) }, { t: 'Mark −4, 2, −1 and 5.', draw: nl({ min: -6, max: 6 }) }, 'Which integer is 3 to the left of −2?', { t: 'Mark −30, 10 and −15 using steps of 5.', draw: nl({ min: -30, max: 30, step: 5, blank: true }) }, 'How many integers are between −6 and 4?'],
      a: { text: 'Which integer is shown by each letter?', kind: 'short', fig: D.numberLine({ min: -8, max: 8, w: 176, h: 16, marks: { '-7': 'A', '-3': 'B', '0': 'C', '2': 'D', '5': 'E', '-1': 'F' } }), figWide: true, items: ['A', 'B', 'C', 'D', 'E', 'F'] },
      b: { text: 'Mark each set of numbers on the number line.', kind: 'work', items: [{ t: '6, −3, 5, 1, −1', draw: nl({ min: -8, max: 8 }) }, { t: '−7, 4, −4, 0', draw: nl({ min: -8, max: 8 }) }] },
      c: { text: 'Mark each set on the number line.', kind: 'work', items: [{ t: 'integers between −2 and 5', draw: nl({ min: -8, max: 8 }) }, { t: 'integers less than 1 and greater than −6', draw: nl({ min: -8, max: 8 }) },
        { t: 'integers between −8 and −3', draw: nl({ min: -10, max: 2 }) }, { t: 'all even integers from −6 to 6', draw: nl({ min: -8, max: 8 }) }] },
      d: { text: 'Number lines with a scale.', kind: 'work', items: [{ t: 'Mark −20, 15, −5 and 30. Use steps of 10.', draw: nl({ min: -40, max: 40, step: 10, blank: true }) }, { t: 'Mark the integers more than −4 but at most 2.', draw: nl({ min: -6, max: 6 }) },
        'How many integers are between −9 and 9?', 'Which integer is halfway between −10 and 4?'] },
      tallExamples: true,
      ext: { q: 'How many integers are between −15 and 12?', steps: ['From −14 to −1: 14 integers', 'Then 0: 1 integer', 'From 1 to 11: 11 integers'], a: '14 + 1 + 11 = 26 integers', qs: ['How many integers are between −30 and 25?', 'Which integer is halfway between −17 and 5?'] },
      summary: { steps: ['Numbers <b>increase</b> to the right.', 'Negatives are left of 0.', 'Use an <b>even scale</b>: equal gaps.', '“Between” does not include the end numbers.'],
        worked: [['Where is −3?', ['3 steps left of 0'], '3 marks left of zero'], ['Integers between −2 and 2?', ['Do not include −2 and 2'], '−1, 0, 1'], ['Mark −20 on a scale of 10s', ['Each gap is 10', '2 gaps left of 0'], 'second mark left of 0'], ['Halfway between −6 and 2?', ['Distance 8, half is 4', '−6 + 4'], '−2']] },
      exit: { qs: ['List the integers between −3 and 1.', 'Which is further left on a number line: −8 or −2?', 'Which integer is halfway between −9 and 3?'] },
      ans: { we: ['dots at −5, −2, 0, 3', '−2, −1, 0, 1', 'dots at −4, −1, 2, 5', '−5', 'scale in 5s; dots at −30, −15, 10', '9'], a: ['−7', '−3', '0', '2', '5', '−1'], b: ['dots at −3, −1, 1, 5, 6', 'dots at −7, −4, 0, 4'],
        c: ['−1, 0, 1, 2, 3, 4', '−5, −4, −3, −2, −1, 0', '−7, −6, −5, −4', '−6, −4, −2, 0, 2, 4, 6'], d: ['scale −40 to 40 in 10s with dots', '−3, −2, −1, 0, 1, 2', '17', '−3'],
        ext: ['54', '−6'], exit: ['−2, −1, 0', '−8', '−3'] },
    }),

    lesson({
      code: '1.03', title: 'Comparing and ordering integers',
      li: ['compare integers using &lt; and &gt;', 'put integers in ascending and descending order'],
      sc: ['use a number line to decide which integer is larger', 'write true statements with &lt; and &gt;', 'order a set of integers from smallest to largest and largest to smallest'],
      terms: ['Ascending', 'Descending', '&lt; and &gt;'],
      we: ['True or false: −4 &gt; 2? −2 &lt; −3?', 'Write in ascending order: 3, −6, 0, −1, 5', 'Write &lt; or &gt;: −6 ☐ −9', 'Descending: −2, 8, −15, 0, 3', 'Ascending: −(−3), −5, 1, −(2)', 'Write 3 integers between −12 and −8 in ascending order.'],
      a: { text: 'Write true (T) or false (F).', kind: 'short', items: ['−4 &gt; 2', '−2 &lt; −3', '2 &gt; −1', '−11 &lt; −10', '−3 &gt; −4', '−9 &gt; −2'] },
      b: { text: 'Write &lt; or &gt; between each pair.', kind: 'short', items: ['5 ☐ −5', '−7 ☐ −1', '0 ☐ −3', '−12 ☐ −21', '−1 ☐ 1', '−100 ☐ −99'] },
      c: { text: 'Order each set.', kind: 'work', items: ['Ascending: 4, −2, 7, −8, 0', 'Descending: −9, 14, 3, 0, −5, −10, −1', 'Ascending: −15, 12, −3, −20, 8', 'Descending: −7, −2, −11, 6, −1',
        'Ascending: temperatures −4°C, 3°C, −12°C, 0°C, −1°C', 'Descending: heights 40 m, −8 m, −35 m, 12 m'] },
      d: { text: 'Challenge.', kind: 'work', items: ['Write 3 integers that are less than −5 but greater than −10.', 'Which is the smallest: −(−6), −8 or −(−10)?', 'Put in ascending order: −1, −10, −100, −1000, 0', 'Is it true that the larger the number after a negative sign, the smaller the integer? Explain.'] },
      ext: { q: 'Write in ascending order: −3, 2, −(−5), −7, 0', steps: ['−(−5) is the opposite of −5, which is 5', 'Now order: −7, −3, 0, 2, 5'], a: '−7, −3, 0, 2, −(−5)', qs: ['Order from smallest: −(−2), −4, −(−4), 3, −(−9)', 'Find two integers between −(−3) and −(4).'] },
      summary: { steps: ['Further <b>right</b> on the number line = <b>larger</b>.', '&lt; means “is less than”; &gt; means “is greater than”.', '<b>Ascending</b>: smallest to largest.', '<b>Descending</b>: largest to smallest.'],
        worked: [['Is −5 &lt; −1?', ['−5 is further left'], 'True'], ['Order −2, 4, −8, 1', ['Smallest is the most negative'], '−8, −2, 1, 4'], ['Descending: −3, −30, 3, 0', ['Largest first'], '3, 0, −3, −30'], ['Order −(−4), −6, 2', ['−(−4) = 4'], '−6, 2, 4']] },
      exit: { qs: ['True or false: −7 &gt; −3?', 'Write in descending order: 2, −5, 0, −1', 'Write in ascending order: −12, 5, −(−8), −20, 0'] },
      ans: { we: ['False; false', '−6, −1, 0, 3, 5', '&gt;', '8, 3, 0, −2, −15', '−5, −(2), 1, −(−3)', '−11, −10, −9'], a: ['F', 'F', 'T', 'T', 'T', 'F'], b: ['&gt;', '&lt;', '&gt;', '&gt;', '&lt;', '&lt;'],
        c: ['−8, −2, 0, 4, 7', '14, 3, 0, −1, −5, −9, −10', '−20, −15, −3, 8, 12', '6, −1, −2, −7, −11', '−12, −4, −1, 0, 3', '40, 12, −8, −35'],
        d: ['e.g. −6, −7, −8', '−8', '−1000, −100, −10, −1, 0', 'Yes, for negatives: −20 is smaller than −2'], ext: ['−4, −(−2), 3, −(−4), −(−9)', 'e.g. 0 and 2 (any integer from −3 to 2)'], exit: ['False', '2, 0, −1, −5', '−20, −12, 0, 5, −(−8)'] },
    }),

    lesson({
      code: '1.04', title: 'Adding integers',
      li: ['add positive and negative integers'],
      sc: ['use a number line to add integers', 'know that adding a negative is the same as subtracting', 'add three or more integers'],
      terms: ['Sum', 'Adding a negative'],
      we: [{ t: '3 + (−4). Use the number line.', draw: nl({ min: -6, max: 6 }) }, '−8 + (−2) and −4 + 8', '−5 + (−4) + (−2)', '−8 + 5 + 4', 'It is −7°C and the temperature rises 12°C. New temperature?', 'Find the missing number: ☐ + 9 = −4'],
      a: { text: 'Evaluate each sum.', kind: 'short', items: ['5 + (−2)', '−3 + 7', '−6 + (−1)', '10 + (−13)', '−5 + (−5)', '−3 + 6'] },
      b: { text: 'Evaluate each sum.', kind: 'short', items: ['−9 + 4', '8 + (−8)', '−12 + (−3)', '−1 + 15', '20 + (−25)', '−7 + (−7)'] },
      c: { text: 'Three or more integers.', kind: 'short', items: ['−5 + (−4) + (−2)', '−8 + 5 + 4', '−7 + 6 + (−7)', '3 + (−9) + 10', '−20 + 15 + (−6)', '−1 + (−2) + (−3) + (−4)'] },
      d: { text: 'Adding integers in context.', kind: 'work', items: ['The temperature is −6°C and rises 11°C. What is the new temperature?', 'A lift at level −2 goes up 7 floors. Which level is it at?', 'Maya has $25 and spends $40 on credit. What is her balance?', 'Find the missing number: −9 + ☐ = −3'] },
      ext: { q: 'Find the missing number: ☐ + (−14) = −5', steps: ['Think: what plus −14 gives −5?', 'Undo by adding 14: −5 + 14 = 9', 'Check: 9 + (−14) = −5 ✓'], a: '9', qs: ['☐ + (−8) = −20', '−13 + ☐ + 6 = 0'] },
      summary: { steps: ['Adding a <b>positive</b>: move right.', 'Adding a <b>negative</b>: move left.', 'Same signs: add and keep the sign.', 'Different signs: subtract, keep the sign of the bigger number.'],
        worked: [['4 + (−6)', ['Start at 4, move 6 left'], '−2'], ['−5 + (−3)', ['Same signs: 5 + 3 = 8, keep −'], '−8'], ['−9 + 4 + (−2)', ['−9 + 4 = −5', '−5 + (−2) = −7'], '−7'], ['☐ + (−4) = 1', ['1 + 4 = 5'], '5']] },
      exit: { qs: ['−6 + 9', '−4 + (−8) + 5', 'It is −3°C and the temperature drops 5°C, then rises 9°C. What is the temperature now?'] },
      ans: { we: ['−1', '−10; 4', '−11', '1', '5°C', '−13'], a: evs(['5 + (−2)', '−3 + 7', '−6 + (−1)', '10 + (−13)', '−5 + (−5)', '−3 + 6']), b: evs(['−9 + 4', '8 + (−8)', '−12 + (−3)', '−1 + 15', '20 + (−25)', '−7 + (−7)']),
        c: evs(['−5 + (−4) + (−2)', '−8 + 5 + 4', '−7 + 6 + (−7)', '3 + (−9) + 10', '−20 + 15 + (−6)', '−1 + (−2) + (−3) + (−4)']), d: ['5°C', 'level 5', '−$15', '6'], ext: ['−12', '7'], exit: ['3', '−7', '1°C'] },
    }),

    lesson({
      code: '1.05', title: 'Subtracting integers',
      li: ['subtract positive and negative integers'],
      sc: ['subtract a positive integer by moving left', 'know that subtracting a negative is the same as adding', 'simplify expressions with + and − signs'],
      terms: ['Difference', 'Subtracting a negative'],
      we: ['7 − 11 and −4 − 8', '3 − (−4) and −5 − (−9)', '−3 − 4 − 5', '8 − 6 − (−4)', 'The temperature rose from −9°C to 6°C. By how much?', 'Find the missing number: −2 − ☐ = 6'],
      a: { text: 'Evaluate each expression.', kind: 'short', items: ['7 − 11', '−4 − 8', '2 − 9', '−6 − 1', '0 − 5', '−10 − 10'] },
      b: { text: 'Subtracting a negative: change to adding.', kind: 'short', items: ['3 − (−4)', '−5 − (−9)', '−5 − (−5)', '8 − (−2)', '−12 − (−3)', '0 − (−7)'] },
      c: { text: 'Evaluate each expression.', kind: 'short', items: ['−3 − 4 − 5', '−8 + 5 − 4', '8 − 6 − (−4)', '3 − 8 + (−6)', '−2 − (−7) − 10', '15 − (−5) + (−20)'] },
      d: { text: 'Subtraction in context.', kind: 'work', items: ['The minimum temperature was −5°C and the maximum was 11°C. By how much did it rise?', 'Find the difference between −18 m and 7 m.', 'A submarine at −120 m rises 45 m. How deep is it now?', 'What is 4 less than −9?'] },
      ext: { q: 'Find the missing number: 6 − ☐ = 10', steps: ['Subtracting a negative adds', '6 + 4 = 10, so we subtracted −4', 'Check: 6 − (−4) = 10 ✓'], a: '−4', qs: ['−3 − ☐ = 5', '☐ − (−8) = −2'] },
      summary: { steps: ['Subtracting a <b>positive</b>: move left.', 'Subtracting a <b>negative</b> = adding the positive.', '− (−) becomes +.', 'Difference between two temperatures: higher − lower.'],
        worked: [['5 − 9', ['Start at 5, move 9 left'], '−4'], ['−2 − (−6)', ['= −2 + 6'], '4'], ['−4 − 3 − (−8)', ['−4 − 3 = −7', '−7 + 8'], '1'], ['Rise from −8°C to 5°C', ['5 − (−8) = 13'], '13°C']] },
      exit: { qs: ['−3 − 6', '4 − (−9)', 'The temperature went from −7°C to 12°C. How much did it rise?'] },
      ans: { we: ['−4; −12', '7; 4', '−12', '6', '15°C', '−8'], a: evs(['7 − 11', '−4 − 8', '2 − 9', '−6 − 1', '0 − 5', '−10 − 10']), b: evs(['3 − (−4)', '−5 − (−9)', '−5 − (−5)', '8 − (−2)', '−12 − (−3)', '0 − (−7)']),
        c: evs(['−3 − 4 − 5', '−8 + 5 − 4', '8 − 6 − (−4)', '3 − 8 + (−6)', '−2 − (−7) − 10', '15 − (−5) + (−20)']), d: ['16°C', '25 m', '−75 m (75 m deep)', '−13'], ext: ['−8', '−10'], exit: ['−9', '13', '19°C'] },
    }),

    lesson({
      code: '1.06', title: 'Multiplying integers',
      li: ['multiply positive and negative integers'],
      sc: ['know the sign rules for multiplying', 'multiply two integers', 'multiply three integers by working in pairs'],
      terms: ['Product', 'Sign rule'],
      we: ['6 × (−3) and −2 × 5', '−8 × (−6) and −6 × (−4) × (−1)', '−2 × 3 × 7', '−4 × 2 × (−5)', 'Find the missing number: ☐ × (−7) = 56', 'Is (−1)¹⁰⁰ positive or negative? Explain.'],
      a: { text: 'Evaluate each product.', kind: 'short', items: ['6 × (−3)', '−2 × 5', '−11 × 4', '7 × (−9)', '−3 × 8', '10 × (−10)'] },
      b: { text: 'Negative × negative.', kind: 'short', items: ['−8 × (−6)', '−5 × (−5)', '−7 × (−3)', '−12 × (−2)', '−1 × (−20)', '−9 × (−4)'] },
      c: { text: 'Evaluate each product.', kind: 'short', items: ['−6 × (−4) × (−1)', '−2 × 3 × 7', '−4 × 2 × (−5)', '(−3)²', '−5 × (−2) × 10', '(−2) × (−2) × (−2)'] },
      d: { text: 'Think it through.', kind: 'work', items: ['A diver descends 4 m every minute. Where is she after 7 minutes?', 'Find the missing number: −6 × ☐ = 42', 'Is the product of 5 negative numbers positive or negative? Explain.', 'The temperature drops 3°C each hour for 6 hours. What is the total change?'] },
      ext: { q: 'Evaluate (−1) × (−1) × (−1) × … with 15 factors of −1.', steps: ['Each pair of −1s makes +1', '15 factors = 7 pairs and one left over'], a: '−1', qs: ['Evaluate (−2)⁵', 'Find two integers with a product of −24 and a sum of 5.'] },
      summary: { steps: ['+ × + = +', '− × − = +', '+ × − = −', 'Odd number of negatives → negative answer.'],
        worked: [['4 × (−7)', ['Different signs → negative'], '−28'], ['−9 × (−3)', ['Same signs → positive'], '27'], ['−2 × (−5) × (−3)', ['−2 × (−5) = 10', '10 × (−3)'], '−30'], ['(−3)³', ['Three negatives → negative', '27'], '−27']] },
      exit: { qs: ['−7 × 6', '−8 × (−9)', '−3 × (−4) × (−5)'] },
      ans: { we: ['−18; −10', '48; −24', '−42', '40', '−8', 'Positive: 100 negatives make 50 pairs'], a: evs(['6 * -3', '-2 * 5', '-11 * 4', '7 * -9', '-3 * 8', '10 * -10']), b: evs(['-8*-6', '-5*-5', '-7*-3', '-12*-2', '-1*-20', '-9*-4']),
        c: evs(['-6*-4*-1', '-2*3*7', '-4*2*-5', '(-3)**2', '-5*-2*10', '-2*-2*-2']), d: ['−28 m (28 m deep)', '−7', 'Negative: 2 pairs make positive, 1 negative left', '−18°C'], ext: ['−32', '8 and −3'], exit: ['−42', '72', '−60'] },
    }),

    lesson({
      code: '1.07', title: 'Dividing integers',
      li: ['divide positive and negative integers'],
      sc: ['use the same sign rules for dividing as for multiplying', 'divide two integers', 'work left to right with two divisions'],
      terms: ['Quotient', 'Sign rule'],
      we: ['−12 ÷ (−4) and 15 ÷ (−5)', '24 ÷ (−6) ÷ (−2)', '−36 ÷ 3 ÷ 4', '−64 ÷ (−4) ÷ 2', 'A debt of $96 is shared by 8 people. Write each share as an integer.', 'Find the missing number: ☐ ÷ (−6) = −9'],
      a: { text: 'Evaluate each quotient.', kind: 'short', items: ['−12 ÷ (−4)', '15 ÷ (−5)', '−6 ÷ (−6)', '16 ÷ (−4)', '−24 ÷ 12', '−1000 ÷ 10'] },
      b: { text: 'Evaluate each quotient.', kind: 'short', items: ['−45 ÷ 9', '−56 ÷ (−8)', '63 ÷ (−7)', '−100 ÷ (−25)', '0 ÷ (−3)', '−81 ÷ 9'] },
      c: { text: 'Work from left to right.', kind: 'short', items: ['24 ÷ (−6) ÷ (−2)', '−36 ÷ 3 ÷ 4', '−64 ÷ (−4) ÷ 2', '−60 ÷ (−5) ÷ (−3)', '100 ÷ (−10) ÷ (−5)', '−48 ÷ 2 ÷ (−3)'] },
      d: { text: 'Division in context.', kind: 'work', items: ['A $−84 debt is shared equally by 4 people. What is each share?', 'The temperature fell 18°C over 6 hours. What was the change each hour?', 'Find the missing number: ☐ ÷ (−5) = 7', 'Find the missing number: −72 ÷ ☐ = 9'] },
      ext: { q: 'Evaluate −6 × 8 ÷ (−12)', steps: ['Work left to right', '−6 × 8 = −48', '−48 ÷ (−12) = 4'], a: '4', qs: ['−90 ÷ (−3) × (−2)', '−5 × (−12) ÷ (−4) ÷ 3'] },
      summary: { steps: ['Same signs → positive.', 'Different signs → negative.', '0 divided by any number is 0.', 'Two divisions: work left to right.'],
        worked: [['−20 ÷ 4', ['Different signs'], '−5'], ['−35 ÷ (−7)', ['Same signs'], '5'], ['−40 ÷ (−2) ÷ (−5)', ['−40 ÷ (−2) = 20', '20 ÷ (−5)'], '−4'], ['☐ ÷ (−3) = −6', ['−6 × (−3)'], '18']] },
      exit: { qs: ['−36 ÷ 9', '−42 ÷ (−6)', '−80 ÷ (−4) ÷ (−5)'] },
      ans: { we: ['3; −3', '2', '−3', '8', '−$12', '54'], a: evs(['-12/-4', '15/-5', '-6/-6', '16/-4', '-24/12', '-1000/10']), b: evs(['-45/9', '-56/-8', '63/-7', '-100/-25', '0/-3', '-81/9']),
        c: evs(['24/-6/-2', '-36/3/4', '-64/-4/2', '-60/-5/-3', '100/-10/-5', '-48/2/-3']), d: ['−$21', '−3°C each hour', '−35', '−8'], ext: ['−60', '−5'], exit: ['−4', '7', '−4'] },
    }),

    lesson({
      code: '1.08', title: 'Order of operations with integers',
      li: ['use the order of operations with positive and negative numbers'],
      sc: ['do brackets first, then × and ÷, then + and −', 'work left to right for operations of the same kind', 'evaluate an expression with a fraction bar'],
      terms: ['Order of operations', 'Fraction bar'],
      we: ['−6 + (−3) × 2', '(9 − 17) ÷ (−4 + 6), written as a fraction', '−3 × 5 + 6 ÷ (−2)', '−12 + (−3) × (−7) − 2', '<span class="fr"><sup>7 + (−12) + 6</sup><sub>2 − 5</sub></span>', '−6 + (−6) ÷ (−2) × 2'],
      a: { text: 'Evaluate each expression.', kind: 'short', items: ['4 − 3 × 6', '−12 ÷ 4 − 10', '30 ÷ (−6) + 5', '−2 + 5 × 3', '10 − (−2) × 4', '−8 ÷ 2 + 1'] },
      b: { text: 'Evaluate each expression.', kind: 'short', items: ['−3 × 5 + 6 ÷ (−2)', '−2 × 7 + 15 ÷ (−3)', '(−4 + 1) × 5', '20 ÷ (−5 − 5)', '−3 × (2 − 7)', '(−6 − 2) ÷ (−4)'] },
      c: { text: 'Evaluate each expression.', kind: 'short', items: ['−12 + (−3) × (−7) − 2', '−6 + (−6) ÷ (−2) × 2', '5 − 3 × (−2) + 1', '−20 ÷ (−2 × 5)', '(−3)² − 10', '4 × (−3) − (−2) × 5'] },
      d: { text: 'Fraction bars: work out the top and bottom first.', kind: 'work', items: ['<span class="fr"><sup>9 − 17</sup><sub>−4 + 6</sub></span>', '<span class="fr"><sup>7 + (−12) + 6</sup><sub>2 − 5</sub></span>', '<span class="fr"><sup>−3 × 8</sup><sub>−6</sub></span>', '<span class="fr"><sup>−10 − 14</sup><sub>2 × (−3)</sub></span>'] },
      ext: { q: 'Insert brackets to make this true: −2 + 6 × −3 = −12', steps: ['Try (−2 + 6) × −3', '= 4 × (−3) = −12 ✓'], a: '(−2 + 6) × −3', qs: ['Insert brackets: 8 − 12 ÷ −4 + 2 = 2', 'Write an expression using −3, 4 and 5 that equals −17.'] },
      summary: { title: 'Order of operations', steps: ['<b>B</b>rackets first.', '× and ÷ from left to right.', '+ and − from left to right.', 'Fraction bar: work out top and bottom first.'],
        worked: [['−5 + 4 × (−2)', ['4 × (−2) = −8', '−5 + (−8)'], '−13'], ['(−3 − 5) × 2', ['−3 − 5 = −8', '−8 × 2'], '−16'], ['<span class="fr"><sup>−18</sup><sub>2 − 5</sub></span>', ['2 − 5 = −3', '−18 ÷ (−3)'], '6'], ['(−2 + 6) × −3', ['4 × −3'], '−12']] },
      exit: { qs: ['−5 + 2 × 3', '−3 × (4 − 9)', '<span class="fr"><sup>−4 × 6</sup><sub>3 − 5</sub></span>'] },
      ans: { we: ['−12', '−4', '−18', '7', '1 ÷ (−3) = −1/3', '0'], a: evs(['4 − 3 × 6', '−12 ÷ 4 − 10', '30 ÷ (−6) + 5', '−2 + 5 × 3', '10 − (−2) × 4', '−8 ÷ 2 + 1']), b: evs(['−3 × 5 + 6 ÷ (−2)', '−2 × 7 + 15 ÷ (−3)', '(−4 + 1) × 5', '20 ÷ (−5 − 5)', '−3 × (2 − 7)', '(−6 − 2) ÷ (−4)']),
        c: evs(['−12 + (−3) × (−7) − 2', '−6 + (−6) ÷ (−2) × 2', '5 − 3 × (−2) + 1', '−20 ÷ (−2 × 5)', '(-3)**2 − 10', '4 × (−3) − (−2) × 5']), d: evs(['(9 − 17)/(−4 + 6)', '(7 + (−12) + 6)/(2 − 5)', '(−3 × 8)/(−6)', '(−10 − 14)/(2 × (−3))']).map((x) => (x === '−0.333333' ? '−1/3' : x)),
        ext: ['(8 − 12) ÷ (−4 + 2) = 2', 'e.g. −3 × 4 − 5 = −17'], exit: ['1', '15', '12'] },
    }),

    lesson({
      code: '1.09', title: 'Integers on a calculator',
      li: ['use a calculator to work with integers'],
      sc: ['enter a negative number using the (−) key', 'use brackets on a calculator', 'check that an answer is reasonable'],
      terms: ['(−) key', 'Estimate'],
      we: ['Use your calculator: 28 − 37 and −17 + 11', '[5 + (−20)] ÷ (−3)', '18 − 15 × 2 on a calculator', '100 − 120 ÷ 4 + 17', '−16 × 3 + (−4)', '<span class="fr"><sup>−84 − 16</sup><sub>−25</sub></span>'],
      a: { text: 'Use your calculator.', kind: 'short', items: ['28 − 37', '−17 + 11', '−45 − 38', '−16 × 3', '−144 ÷ (−12)', '−250 + 175'] },
      b: { text: 'Use your calculator.', kind: 'short', items: ['18 − 15 × 2', '−16 × 3 + (−4)', '100 − 120 ÷ 4 + 17', '−7 × (−8) − 60', '−96 ÷ 8 + 5', '(−13)²'] },
      c: { text: 'Use brackets on your calculator.', kind: 'short', items: ['[5 + (−20)] ÷ (−3)', '(−14 − 22) ÷ (−4)', '−3 × (17 − 29)', '(−8 + 3) × (−6 − 1)', '(−55 + 19) ÷ 12', '−(−7 − 11) × 2'] },
      d: { text: 'Estimate first, then check with a calculator.', kind: 'work', items: ['Estimate −49 × 21, then calculate.', 'Estimate −612 ÷ 29.8 (1 d.p.), then calculate.', 'Jo typed −6² and got −36. Why? How do you get 36?', 'Find the error: 20 − 4 × 3 = 48 on a calculator?'] },
      ext: { q: 'Evaluate <span class="fr"><sup>−48 + 12</sup><sub>−3 × (−4)</sub></span> on a calculator.', steps: ['Put brackets around the top and the bottom', '(−48 + 12) ÷ (−3 × (−4))', '= −36 ÷ 12'], a: '−3', qs: ['<span class="fr"><sup>−125 − 25</sup><sub>6 × (−5)</sub></span>', '<span class="fr"><sup>(−9)² − 1</sup><sub>−16</sub></span>'] },
      summary: { steps: ['Use the <b>(−)</b> key for negative numbers.', 'Calculators follow the order of operations.', 'Use brackets for fraction bars.', 'Estimate to check your answer.'],
        worked: [['−23 + 9', ['(−) 23 + 9 ='], '−14'], ['18 − 15 × 2', ['× first'], '−12'], ['(−36 + 6) ÷ 5', ['Brackets on top'], '−6'], ['(−3)² vs −3²', ['(−3)² = 9, −3² = −9'], '9 and −9']] },
      exit: { qs: ['−84 + 39', '−15 × (−7) − 100', '(−35 − 45) ÷ (−16)'] },
      ans: { we: ['−9; −6', '5', '−12', '87', '−52', '4'], a: evs(['28 − 37', '−17 + 11', '−45 − 38', '−16 × 3', '−144 ÷ (−12)', '−250 + 175']), b: evs(['18 − 15 × 2', '−16 × 3 + (−4)', '100 − 120 ÷ 4 + 17', '−7 × (−8) − 60', '−96 ÷ 8 + 5', '(-13)**2']),
        c: evs(['(5 + (−20)) ÷ (−3)', '(−14 − 22) ÷ (−4)', '−3 × (17 − 29)', '(−8 + 3) × (−6 − 1)', '(−55 + 19) ÷ 12', '-(-7 - 11) * 2']), d: ['≈ −1000; −1029', '≈ −20; −20.5', 'The calculator squares 6 first, then makes it negative. Enter (−6)²', 'It should be 8: × is done before −'],
        ext: ['5', '−5'], exit: ['−45', '5', '5'] },
    }),

    lesson({
      code: '1.10', title: 'Integer problems',
      li: ['solve real problems using integers'],
      sc: ['decide which operation a problem needs', 'write an integer calculation for a word problem', 'check the answer makes sense'],
      terms: ['Rise', 'Balance', 'Deposit'],
      we: ['The minimum overnight temperature in Goulburn was −5°C. During the day it rose to 11°C. By how much did it rise?', 'A bank account has $120. Three withdrawals of $55 are made. What is the balance?', 'A lift at level 4 goes down 7 floors. Which level is it on?', 'Balance −$35, deposit $120. New balance?', 'Harrison saves $80 a week and pays $210 a month for a car loan. How much after 6 months (26 weeks)?', 'A diver at −42 m rises 6 m every minute. Where is she after 5 minutes?'],
      a: { text: 'Temperature problems.', kind: 'work', items: ['It was −3°C at 6 am and 14°C at noon. What was the rise?', 'It was 8°C and fell 12°C. What is the new temperature?', 'The temperature fell 2°C each hour from 5°C. What is it after 4 hours?', 'Find the average of −4°C, 2°C, −1°C and −5°C.'] },
      b: { text: 'Heights and depths.', kind: 'work', items: ['A diver at −18 m rises 7 m. How deep is she?', 'A lift goes from level 3 to level −2. How many floors did it travel?', 'A plane at 900 m descends 350 m. What is its height now?', 'A cave is 35 m below sea level and a hill is 120 m above. Find the difference.'] },
      c: { text: 'Money problems.', kind: 'work', items: ['Balance $40, withdraw $65. New balance?', 'Balance −$30, deposit $75. New balance?', 'Sam owes $12 to each of 5 friends. Write this as an integer and find the total.', 'A shop made −$250 on Monday and $400 on Tuesday. Total?'] },
      d: { text: 'Multi-step problems.', kind: 'work', items: ['Harrison saves $80 a week. Each month $210 is taken out for a car loan. How much is in the account after 6 months (26 weeks)?', 'A game scores +5 for a win and −3 for a loss. Mia wins 7 and loses 9. What is her score?'] },
      ext: { q: 'A submarine at −240 m rises 15 m per minute. How long until it is at −60 m?', steps: ['Distance to rise: −60 − (−240) = 180 m', 'Time: 180 ÷ 15 = 12'], a: '12 minutes', qs: ['A freezer is at 4°C and cools by 3°C every 10 minutes. How long until it is −17°C?', 'Write your own integer problem with an answer of −8.'] },
      summary: { steps: ['Read carefully and underline the numbers.', 'Rise, gain, deposit → add. Fall, loss, withdraw → subtract.', 'Difference: larger − smaller.', 'Check the answer makes sense.'],
        worked: [['From −5°C to 11°C', ['11 − (−5)'], '16°C rise'], ['$20 balance, withdraw $50', ['20 − 50'], '−$30'], ['6 months: +$80 × 26, −$210 × 6', ['2080 − 1260'], '$820'], ['Rise 15 m/min from −240 m to −60 m', ['180 ÷ 15'], '12 minutes']] },
      exit: { qs: ['It was −6°C and rose 10°C. What is the temperature now?', 'A diver goes from −30 m to −12 m. How far did she rise?', 'A score starts at 0. Gain 4, lose 7, lose 7, gain 3. Final score?'] },
      ans: { we: ['16°C', '−$45', 'level −3', '$85', '$820', '−12 m'], a: ['17°C', '−4°C', '−3°C', '−2°C'], b: ['12 m deep (−11 m)', '5 floors', '550 m', '155 m'], c: ['−$25', '$45', '−$60', '$150'], d: ['26 × 80 − 6 × 210 = $820', '35 − 27 = 8'],
        ext: ['70 minutes', 'e.g. It was 4°C and fell 12°C'], exit: ['4°C', '18 m', '−7'] },
    }),
  ],
};
