// Calm two-page lessons for Chapter 1 (lib/worksheet3.js), in the style of the Freefall sheets. Every question is
// written out by hand so each step grows in small, deliberate changes. The working lines (one step a line, the answer
// last) make the fading scaffolds: worked, answer blank, numbers blank, blank.
const D = require('../../lib/diagrams');

// Number lines for the questions: blank (just the start) and done (the jumps drawn).
const nl = (min, max, start, moves) => ({ fig: D.jumps({ min, max, start, done: false, every: 1 }), figDone: D.jumps({ min, max, start, moves, every: 1 }) });

// A dot on a number line (a letter above it if given); every: 2 labels every second mark.
const dot = (min, max, v, label = true, every = 1) => D.jumps({ min, max, marks: { [v]: label }, every });
// A number line that counts in steps, labelled only at the given values, with a ? at one mark.
const scale = (min, step, labels, ask) => D.numberLine({ min, max: min + 10 * step, step, blank: true, marks: { ...Object.fromEntries(labels.map((v) => [v, String(v).replace('-', '−')])), [ask]: '?' }, w: 56, h: 13 });
const table = (head, rows) => `<table class="data-table"><tr>${head.map((h) => `<th>${h}</th>`).join('')}</tr>${rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}</table>`;
// The "Is it right?" HOW TO, the same in every lesson.
const judge = (ex) => ({ text: `<p>Work it out yourself. Then say yes or no, with the right answer.</p><p class="ex">${ex}</p>` });

module.exports = {
  '1.01': { steps: [
    { title: 'What is an integer?',
      how: { text: '<p>An <b>integer</b> is a whole number. It can be positive, negative or zero.</p><p>Negatives are left of 0. Positives are right of 0.</p><p class="ex">The dot is 3 left of 0. It is at −3.</p>', fig: dot(-6, 6, -3) },
      rounds: [{ text: 'Which integer is at the dot? Count from 0. The last one has no number line.',
        we: [{ q: 'Where is the dot?', fig: dot(-8, 5, -2), lines: ['the dot is at −2'] }],
        you: [
          { q: 'Where is the dot?', fig: dot(-8, 5, -4), lines: ['the dot is at −4'] },
          { q: 'Where is the dot?', fig: dot(-8, 5, 3), lines: ['the dot is at 3'] },
          { q: 'Where is the dot?', fig: dot(-8, 5, -7), lines: ['the dot is at −7'] },
          { q: 'Where is the dot?', fig: dot(-8, 5, -1), lines: ['the dot is at −1'] },
          { q: 'Which integer is 6 left of 0?', lines: ['it is at −6'] },
        ] }] },
    { title: 'Integers in real life',
      how: { text: '<p>Below zero, down, a loss or spending: <b>negative</b>.</p><p>Above zero, up, a gain or saving: <b>positive</b>.</p><p class="ex">5 m below sea level: −5</p>' },
      rounds: [{ text: 'Write an integer for each one.',
        we: [{ q: '3°C below zero', lines: ['= −3'] }],
        you: [
          { q: 'a gain of 4 kg', lines: ['= 4'] },
          { q: '8 m below sea level', lines: ['= −8'] },
          { q: 'a loss of $12', lines: ['= −12'] },
          { q: '6 floors down', lines: ['= −6'] },
          { q: 'a rise of 15 cm', lines: ['= 15'] },
          { q: 'spending $30', lines: ['= −30'] },
        ] }] },
    { title: 'Opposites',
      how: { text: '<p>The <b>opposite</b> is the same distance from 0, on the other side.</p><p class="ex">The opposite of 4 is −4. The opposite of −4 is 4.</p>', fig: D.jumps({ min: -6, max: 6, arcs: [{ from: 0, to: 4, label: '4' }, { from: 0, to: -4, label: '4' }], every: 1 }) },
      rounds: [{ text: 'Write the opposite of each integer.', two: true,
        we: [{ q: '7', lines: ['opposite: −7'] }],
        you: [
          { q: '−5', lines: ['opposite: 5'] },
          { q: '9', lines: ['opposite: −9'] },
          { q: '−12', lines: ['opposite: 12'] },
          { q: '30', lines: ['opposite: −30'] },
          { q: '0', lines: ['opposite: 0'] },
          { q: '−100', lines: ['opposite: 100'] },
        ] }] },
    { title: 'Double opposites',
      how: { text: '<p>A − in front of a bracket means <b>the opposite of</b>.</p><p class="ex">−(−6) means the opposite of −6, which is 6.</p><p class="ex">−(+6) means the opposite of 6, which is −6.</p>' },
      rounds: [{ text: 'Say "the opposite of" for the − in front of the bracket.', two: true,
        we: [{ q: '−(−3)', lines: ['= opposite of −3', '= 3'] }, { q: '−(+4)', lines: ['= opposite of 4', '= −4'] }],
        you: [
          { q: '−(−8)', lines: ['= opposite of −8', '= 8'] },
          { q: '−(+5)', lines: ['= opposite of 5', '= −5'] },
          { q: '−(−20)', lines: ['= opposite of −20', '= 20'] },
          { q: '−(+12)', lines: ['= opposite of 12', '= −12'] },
          { q: '−(−45)', lines: ['= opposite of −45', '= 45'] },
          { q: '−(+30)', lines: ['= opposite of 30', '= −30'] },
        ] }] },
    { title: 'Distance from zero',
      how: { text: '<p>The <b>distance from 0</b> is how many steps a number is from 0. It is never negative.</p><p class="ex">−7 or 5: distances 7 and 5. Further: −7.</p>' },
      rounds: [{ text: 'Which is further from 0? Write how far each one is.',
        we: [{ q: '−4 or 3', lines: ['distances: 4 and 3', 'further: −4'] }],
        you: [
          { q: '−8 or 5', lines: ['distances: 8 and 5', 'further: −8'] },
          { q: '6 or −2', lines: ['distances: 6 and 2', 'further: 6'] },
          { q: '−10 or 9', lines: ['distances: 10 and 9', 'further: −10'] },
          { q: '−3 or −11', lines: ['distances: 3 and 11', 'further: −11'] },
          { q: '14 or −15', lines: ['distances: 14 and 15', 'further: −15'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says the opposite of −9 is 9. Both are 9 from 0. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −(−4) = −4. Is he right?', lines: ['= opposite of −4', '= 4', 'No. The answer is 4.'] }],
        you: [
          { q: 'Ali says −(+7) = 7. Is he right?', lines: ['= opposite of 7', '= −7', 'No. The answer is −7.'] },
          { q: 'Ben says −6 is further from 0 than 4. Is he right?', lines: ['distances: 6 and 4', '6 is more than 4', 'Yes. Ben is right.'] },
          { q: 'Mia says the opposite of 0 is 0. Is she right?', lines: ['0 is 0 steps from 0', 'its opposite: 0', 'Yes. Mia is right.'] },
          { q: 'Jo says 10 m down and 10 m up are opposites. Is Jo right?', lines: ['down: −10, up: 10', 'same distance, other side', 'Yes. Jo is right.'] },
        ] }] },
  ] },

  '1.02': { steps: [
    { title: 'Reading a number line',
      how: { text: '<p>Numbers get larger to the <b>right</b>.</p><p>Only every second mark has a number. Count the marks from a number you know.</p><p class="ex">One mark left of −2 is −3.</p>' },
      rounds: [{ text: 'Which integer is at the letter? The last one has no number line.',
        we: [{ q: 'Where is P?', fig: dot(-8, 6, -5, 'P', 2), lines: ['P is at −5'] }],
        you: [
          { q: 'Where is Q?', fig: dot(-8, 6, -1, 'Q', 2), lines: ['Q is at −1'] },
          { q: 'Where is R?', fig: dot(-8, 6, 3, 'R', 2), lines: ['R is at 3'] },
          { q: 'Where is S?', fig: dot(-8, 6, -7, 'S', 2), lines: ['S is at −7'] },
          { q: 'Where is T?', fig: dot(-8, 6, 5, 'T', 2), lines: ['T is at 5'] },
          { q: 'Which integer is between −8 and −6?', lines: ['it is −7'] },
        ] }] },
    { title: 'Moving left and right',
      how: { text: '<p>Move <b>right</b>: the number gets larger.</p><p>Move <b>left</b>: the number gets smaller.</p><p class="ex">Start at 2, move 5 left. Land on −3.</p>', fig: D.jumps({ min: -5, max: 5, start: 2, moves: [-5], every: 1 }) },
      rounds: [{ text: 'Where do you land? Use the number line at the top of the page.',
        we: [{ q: 'Start at 3. Move 5 left.', lines: ['land on −2'] }],
        you: [
          { q: 'Start at −2. Move 6 right.', lines: ['land on 4'] },
          { q: 'Start at 1. Move 4 left.', lines: ['land on −3'] },
          { q: 'Start at −3. Move 5 left.', lines: ['land on −8'] },
          { q: 'Start at −7. Move 10 right.', lines: ['land on 3'] },
          { q: 'Start at 6. Move 13 left.', lines: ['land on −7'] },
        ] }] },
    { title: 'Distance between',
      how: { text: '<p>Count the steps from one number to the other.</p><p>Across 0? Count to 0, then on from 0.</p><p class="ex">−3 and 5: 3 to 0, 5 from 0. 3 + 5 = 8.</p>', fig: D.jumps({ min: -5, max: 6, arcs: [{ from: -3, to: 0, label: '3' }, { from: 0, to: 5, label: '5' }], every: 1 }) },
      rounds: [{ text: 'How far apart are the two integers?', two: true,
        we: [{ q: '−2 and 4', lines: ['2 to 0, 4 from 0', '= 6'] }, { q: '−7 and −3', lines: ['count −7 to −3', '= 4'] }],
        you: [
          { q: '−1 and 6', lines: ['1 to 0, 6 from 0', '= 7'] },
          { q: '−5 and 3', lines: ['5 to 0, 3 from 0', '= 8'] },
          { q: '−9 and −2', lines: ['count −9 to −2', '= 7'] },
          { q: '4 and −8', lines: ['8 to 0, 4 from 0', '= 12'] },
          { q: '−12 and −5', lines: ['count −12 to −5', '= 7'] },
          { q: '−15 and 10', lines: ['15 to 0, 10 from 0', '= 25'] },
        ] }] },
    { title: 'Scales in 2s, 5s and 10s',
      how: { text: '<p>Find the <b>step</b>: the difference between two labels ÷ the gaps between them.</p><p class="ex">−10 to 0 is 10, in 5 gaps. 10 ÷ 5 = 2, step 2.</p>' },
      rounds: [{ text: 'Find the step. Then find the number at the ?',
        we: [{ q: 'What is at the ?', fig: scale(-10, 2, [-10, 0], 8), lines: ['10 ÷ 5 = 2, step 2', '? = 8'] }],
        you: [
          { q: 'What is at the ?', fig: scale(-8, 2, [-8, 0], 4), lines: ['8 ÷ 4 = 2, step 2', '? = 4'] },
          { q: 'What is at the ?', fig: scale(-20, 5, [-20, 0], 10), lines: ['20 ÷ 4 = 5, step 5', '? = 10'] },
          { q: 'What is at the ?', fig: scale(-40, 10, [-40, -20], 10), lines: ['20 ÷ 2 = 10, step 10', '? = 10'] },
          { q: 'The scale is −15, −10, ☐, 0. What is ☐?', lines: ['−15 to −10 is 5, step 5', '☐ = −5'] },
        ] }] },
    { title: 'Halfway between',
      how: { text: '<p>Find how far apart they are. Halve it. Move that far from the smaller one.</p><p class="ex">−7 and 3: 10 apart, half is 5. −7 + 5 = −2.</p>' },
      rounds: [{ text: 'Which integer is halfway between?',
        we: [{ q: '−4 and 2', lines: ['6 apart, half is 3', '−4 + 3 = −1'] }],
        you: [
          { q: '−6 and 2', lines: ['8 apart, half is 4', '−6 + 4 = −2'] },
          { q: '−10 and 0', lines: ['10 apart, half is 5', '−10 + 5 = −5'] },
          { q: '−3 and 9', lines: ['12 apart, half is 6', '−3 + 6 = 3'] },
          { q: '−11 and −1', lines: ['10 apart, half is 5', '−11 + 5 = −6'] },
          { q: '−15 and 5', lines: ['20 apart, half is 10', '−15 + 10 = −5'] },
        ] }] },
    { title: 'Number line problems',
      how: { text: '<p>Picture a number line. Start there, then make each move.</p><p class="ex">An ant at −2 walks 5 left. It is at −7.</p>' },
      rounds: [{ text: 'Where does it end up? Write each move.',
        we: [{ q: 'An ant starts at 3. It walks 7 left. Where is it now?', lines: ['start at 3, move 7 left', 'land on −4'] }],
        you: [
          { q: 'A frog starts at −4. It hops 9 right. Where is it now?', lines: ['start at −4, move 9 right', 'land on 5'] },
          { q: 'Point A is at −6. Point B is 10 to the right of A. Where is B?', lines: ['start at −6, move 10 right', 'land on 4'] },
          { q: 'An ant at 5 walks 8 left, then 2 right. Where is it now?', lines: ['start at 5, move 8 left: −3', 'move 2 right', 'land on −1'] },
          { q: 'A lift at level −3 goes up 7 floors, then down 6. Which level is it on?', lines: ['start at −3, move 7 up: 4', 'move 6 down', 'land on −2'] },
        ] }] },
  ] },

  '1.03': { steps: [
    { title: 'Which is larger?',
      how: { text: '<p>On a number line, the number further <b>right</b> is larger.</p><p class="ex">−2 is right of −7, so −2 is larger.</p>', fig: D.jumps({ min: -8, max: 2, marks: { '-7': '−7', '-2': '−2' }, every: 1 }) },
      rounds: [{ text: 'Which integer is larger? The last one has no number line.',
        we: [{ q: '−3 or 2', fig: D.jumps({ min: -8, max: 5, marks: { '-3': true, 2: true }, every: 1 }), lines: ['larger: 2'] }],
        you: [
          { q: '−6 or −2', fig: D.jumps({ min: -8, max: 5, marks: { '-6': true, '-2': true }, every: 1 }), lines: ['larger: −2'] },
          { q: '1 or −4', fig: D.jumps({ min: -8, max: 5, marks: { 1: true, '-4': true }, every: 1 }), lines: ['larger: 1'] },
          { q: '−8 or −3', fig: D.jumps({ min: -8, max: 5, marks: { '-8': true, '-3': true }, every: 1 }), lines: ['larger: −3'] },
          { q: '−1 or −7', fig: D.jumps({ min: -8, max: 5, marks: { '-1': true, '-7': true }, every: 1 }), lines: ['larger: −1'] },
          { q: '−12 or −9', lines: ['larger: −9'] },
        ] }] },
    { title: 'Using &lt; and &gt;',
      how: { text: '<p>&lt; means <b>is less than</b>. &gt; means <b>is greater than</b>.</p><p>The open side faces the larger number.</p><p class="ex">−5 &lt; 2 and −1 &gt; −6</p>' },
      rounds: [{ text: 'Find the larger one. Then write &lt; or &gt; in the box.', two: true,
        we: [{ q: '−4 ☐ 3', lines: ['larger: 3', 'symbol: &lt;'] }],
        you: [
          { q: '−2 ☐ −6', lines: ['larger: −2', 'symbol: &gt;'] },
          { q: '0 ☐ −5', lines: ['larger: 0', 'symbol: &gt;'] },
          { q: '−9 ☐ −3', lines: ['larger: −3', 'symbol: &lt;'] },
          { q: '4 ☐ −10', lines: ['larger: 4', 'symbol: &gt;'] },
          { q: '−15 ☐ −14', lines: ['larger: −14', 'symbol: &lt;'] },
          { q: '−20 ☐ 1', lines: ['larger: 1', 'symbol: &lt;'] },
        ] }] },
    { title: 'Ordering',
      how: { text: '<p><b>Ascending</b>: smallest to largest, left to right on the number line.</p><p><b>Descending</b>: largest to smallest.</p><p class="ex">Ascending: −6, −1, 2, 5</p>', fig: D.jumps({ min: -7, max: 6, marks: { '-6': '−6', '-1': '−1', 2: '2', 5: '5' }, every: 1 }) },
      rounds: [{ text: 'Find the smallest (or largest) first. Then write them in order.',
        we: [{ q: 'Ascending: 3, −4, 0, −1', lines: ['smallest: −4', '−4, −1, 0, 3'] }, { q: 'Descending: −2, 5, −7, 1', lines: ['largest: 5', '5, 1, −2, −7'] }],
        you: [
          { q: 'Ascending: 2, −3, −1, 4', lines: ['smallest: −3', '−3, −1, 2, 4'] },
          { q: 'Descending: −4, 6, −1, 0', lines: ['largest: 6', '6, 0, −1, −4'] },
          { q: 'Ascending: −12, 8, −15, −3, 1', lines: ['smallest: −15', '−15, −12, −3, 1, 8'] },
          { q: 'Descending: −20, −2, −11, 5, −8', lines: ['largest: 5', '5, −2, −8, −11, −20'] },
        ] }] },
    { title: 'Comparing temperatures',
      how: { text: '<p>Colder is <b>lower</b> on the thermometer: a smaller number.</p><p class="ex">−8°C is colder than −3°C.</p>', fig: D.thermometer({ min: -10, max: 0, value: -3, unit: 1.3, every: 5, arrows: [{ v: -3, text: '−3°C' }, { v: -8, text: '−8°C' }], w: 36 }) },
      rounds: [{ text: 'Which is colder (or warmer)? Picture the thermometer.',
        we: [{ q: 'Which is colder: −4°C or −9°C?', lines: ['−9 is lower than −4', 'colder: −9°C'] }],
        you: [
          { q: 'Which is colder: −2°C or −6°C?', lines: ['−6 is lower than −2', 'colder: −6°C'] },
          { q: 'Which is colder: 3°C or −1°C?', lines: ['−1 is lower than 3', 'colder: −1°C'] },
          { q: 'Which is warmer: −10°C or −7°C?', lines: ['−7 is higher than −10', 'warmer: −7°C'] },
          { q: 'Which is colder: −21°C or −12°C?', lines: ['−21 is lower than −12', 'colder: −21°C'] },
        ] }] },
    { title: 'Simplify, then compare',
      how: { text: '<p>Simplify any −(−n) or −(+n) first.</p><p>Then compare.</p><p class="ex">−(−2) ☐ −5 becomes 2 ☐ −5, so &gt;.</p>' },
      rounds: [{ text: 'Simplify. Then write &lt; or &gt;.', two: true,
        we: [{ q: '−(−3) ☐ −4', lines: ['= 3 ☐ −4', 'symbol: &gt;'] }],
        you: [
          { q: '−(−1) ☐ −2', lines: ['= 1 ☐ −2', 'symbol: &gt;'] },
          { q: '−(+4) ☐ −3', lines: ['= −4 ☐ −3', 'symbol: &lt;'] },
          { q: '−(−5) ☐ 6', lines: ['= 5 ☐ 6', 'symbol: &lt;'] },
          { q: '−7 ☐ −(+9)', lines: ['= −7 ☐ −9', 'symbol: &gt;'] },
          { q: '−(+6) ☐ 5', lines: ['= −6 ☐ 5', 'symbol: &lt;'] },
          { q: '−8 ☐ −(−8)', lines: ['= −8 ☐ 8', 'symbol: &lt;'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says −3 &gt; −8. −3 is right of −8. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −9 is larger than −4. Is he right?', lines: ['−9 is left of −4', 'so −9 is smaller', 'No. −4 is larger.'] }],
        you: [
          { q: 'Mia says −1 &gt; −10. Is she right?', lines: ['−1 is right of −10', 'so −1 is larger', 'Yes. Mia is right.'] },
          { q: 'Ben says −20°C is colder than −2°C. Is he right?', lines: ['−20 is lower than −2', 'so −20°C is colder', 'Yes. Ben is right.'] },
          { q: 'Ali says −5, −7, 0, 2 is in ascending order. Is he right?', lines: ['smallest: −7', '−7, −5, 0, 2', 'No. It is −7, −5, 0, 2.'] },
          { q: 'Jo says −(−6) &lt; −6. Is Jo right?', lines: ['−(−6) = 6', '6 is right of −6', 'No. −(−6) &gt; −6.'] },
        ] }] },
  ] },

  '1.04': { steps: [
    { title: 'Adding a positive',
      how: { text: '<p>Start at the first number.</p><p>Adding a positive number: move <b>right</b>.</p><p class="ex">−3 + 5: start at −3, move 5 right. Land on 2.</p>', fig: D.jumps({ min: -6, max: 6, start: -3, moves: [5], every: 1 }) },
      rounds: [{ text: 'Draw the jump. Write where you land. The last one has no number line.',
        we: [{ q: '−2 + 4', ...nl(-8, 5, -2, [4]), lines: ['= 2'] }],
        you: [
          { q: '−4 + 3', ...nl(-8, 5, -4, [3]), lines: ['= −1'] },
          { q: '−5 + 2', ...nl(-8, 5, -5, [2]), lines: ['= −3'] },
          { q: '−6 + 4', ...nl(-8, 5, -6, [4]), lines: ['= −2'] },
          { q: '−3 + 7', ...nl(-8, 5, -3, [7]), lines: ['= 4'] },
          { q: '−7 + 7', lines: ['= 0'] },
        ] }] },
    { title: 'Adding a negative',
      how: { text: '<p>Adding a negative number: move <b>left</b>.</p><p>+ (−4) means the same as − 4.</p><p class="ex">3 + (−5) = 3 − 5 = −2</p>', fig: D.jumps({ min: -4, max: 5, start: 3, moves: [-5], every: 1 }) },
      rounds: [{ text: 'Rewrite + (−) as −. Then work it out.', two: true,
        we: [{ q: '6 + (−2)', lines: ['= 6 − 2', '= 4'] }, { q: '−2 + (−3)', lines: ['= −2 − 3', '= −5'] }],
        you: [
          { q: '7 + (−3)', lines: ['= 7 − 3', '= 4'] },
          { q: '5 + (−5)', lines: ['= 5 − 5', '= 0'] },
          { q: '2 + (−6)', lines: ['= 2 − 6', '= −4'] },
          { q: '4 + (−10)', lines: ['= 4 − 10', '= −6'] },
          { q: '−1 + (−4)', lines: ['= −1 − 4', '= −5'] },
          { q: '−3 + (−6)', lines: ['= −3 − 6', '= −9'] },
        ] }] },
    { title: 'Zero pairs',
      how: { text: '<p>A + and a − make a <b>zero pair</b>. They cancel out.</p><p>So take the difference. The sign with more wins.</p><p class="ex">−6 + 4: 6 − 4 = 2. − has more: −2.</p>', fig: D.counters({ pos: 4, neg: 6, pairs: true }) },
      rounds: [{ text: 'Take the difference. Which sign has more?', two: true,
        we: [{ q: '−5 + 8', lines: ['8 − 5 = 3', '+ has more: 3'] }, { q: '6 + (−9)', lines: ['9 − 6 = 3', '− has more: −3'] }],
        you: [
          { q: '−7 + 10', lines: ['10 − 7 = 3', '+ has more: 3'] },
          { q: '−9 + 4', lines: ['9 − 4 = 5', '− has more: −5'] },
          { q: '8 + (−12)', lines: ['12 − 8 = 4', '− has more: −4'] },
          { q: '−15 + 20', lines: ['20 − 15 = 5', '+ has more: 5'] },
          { q: '25 + (−40)', lines: ['40 − 25 = 15', '− has more: −15'] },
          { q: '−36 + 50', lines: ['50 − 36 = 14', '+ has more: 14'] },
        ] }] },
    { title: 'Three numbers',
      how: { text: '<p>Add from left to right, one jump at a time.</p><p class="ex">−4 + 9 + (−7) = 5 + (−7) = −2</p>', fig: D.jumps({ min: -5, max: 6, start: -4, moves: [9, -7], every: 1 }) },
      rounds: [{ text: 'Add from left to right. Draw the jumps when there is a number line.',
        we: [{ q: '1 + (−4) + 5', ...nl(-6, 6, 1, [-4, 5]), lines: ['= −3 + 5', '= 2'] }],
        you: [
          { q: '2 + (−5) + 4', ...nl(-6, 6, 2, [-5, 4]), lines: ['= −3 + 4', '= 1'] },
          { q: '−3 + 6 + (−2)', ...nl(-6, 6, -3, [6, -2]), lines: ['= 3 + (−2)', '= 1'] },
          { q: '12 + (−15) + (−6)', lines: ['= −3 + (−6)', '= −9'] },
          { q: '−20 + 8 + 15', lines: ['= −12 + 15', '= 3'] },
        ] }] },
    { title: 'Adding in real life',
      how: { text: '<p>Write the story as a sum.</p><p>Up, rises and gains are <b>positive</b>.</p><p>Down, falls and spending are <b>negative</b>.</p><p class="ex">−6°C, then it warms up 10°C:<br>−6 + 10 = 4°C</p>' },
      rounds: [{ text: 'Write a sum. Then answer the question.',
        we: [{ q: 'It is −5°C. The temperature rises 8°C. What is the temperature now?', lines: ['−5 + 8', '= 3°C'] }],
        you: [
          { q: 'It is −4°C at dawn. By lunch it has warmed up 9°C. What is the temperature at lunch?', lines: ['−4 + 9', '= 5°C'] },
          { q: 'A lift is at level −2. It goes up 5 floors. Which level is it on now?', lines: ['−2 + 5', '= level 3'] },
          { q: 'Sam has $15 in the bank. Sam spends $40 using credit. What is the balance now?', lines: ['15 + (−40)', '= −$25'] },
          { q: 'A diver is at −18&nbsp;m. She swims up 7&nbsp;m, then down 4&nbsp;m. Where is she now?', lines: ['−18 + 7 + (−4)', '= −11 + (−4)', '= −15 m'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says 3 + (−5) = −2. 3 − 5 = −2. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −6 + 2 = −8. Is he right?', lines: ['start at −6, move 2 right', '= −4', 'No. The answer is −4.'] }],
        you: [
          { q: 'Mia says −8 + 5 = −13. Is she right?', lines: ['start at −8, move 5 right', '= −3', 'No. The answer is −3.'] },
          { q: 'Ben says −7 + 3 + (−3) = −7. Is he right?', lines: ['3 + (−3) is a zero pair', '−7 + 0 = −7', 'Yes. Ben is right.'] },
          { q: 'Ali says 6 + (−9) = 3. Is he right?', lines: ['9 − 6 = 3', '− has more: −3', 'No. The answer is −3.'] },
          { q: 'Jo says adding always makes a number bigger. Is Jo right?', lines: ['4 + (−6) = −2', '−2 is smaller than 4', 'No. It can get smaller.'] },
        ] }] },
  ] },
  '1.05': { steps: [
    { title: 'Subtracting a positive',
      how: { text: '<p>Start at the first number.</p><p>Subtracting a positive number: move <b>left</b>.</p><p class="ex">2 − 5: start at 2, move 5 left. Land on −3.</p>', fig: D.jumps({ min: -5, max: 4, start: 2, moves: [-5], every: 1 }) },
      rounds: [{ text: 'Draw the jump. Write where you land. The last one has no number line.',
        we: [{ q: '1 − 4', ...nl(-8, 5, 1, [-4]), lines: ['= −3'] }],
        you: [
          { q: '3 − 5', ...nl(-8, 5, 3, [-5]), lines: ['= −2'] },
          { q: '0 − 6', ...nl(-8, 5, 0, [-6]), lines: ['= −6'] },
          { q: '2 − 7', ...nl(-8, 5, 2, [-7]), lines: ['= −5'] },
          { q: '4 − 12', ...nl(-8, 5, 4, [-12]), lines: ['= −8'] },
          { q: '5 − 11', lines: ['= −6'] },
        ] }] },
    { title: 'Starting below zero',
      how: { text: '<p>Start below zero and subtract: you go <b>further</b> below zero.</p><p class="ex">−3 − 4 = −7. You owe $3, then spend $4 more: you owe $7.</p>' },
      rounds: [{ text: 'Move left. Write where you land.', two: true,
        we: [{ q: '−2 − 3', lines: ['move 3 left', '= −5'] }],
        you: [
          { q: '−1 − 4', lines: ['move 4 left', '= −5'] },
          { q: '−5 − 2', lines: ['move 2 left', '= −7'] },
          { q: '−6 − 6', lines: ['move 6 left', '= −12'] },
          { q: '−10 − 5', lines: ['move 5 left', '= −15'] },
          { q: '−8 − 12', lines: ['move 12 left', '= −20'] },
          { q: '−25 − 15', lines: ['move 15 left', '= −40'] },
        ] }] },
    { title: 'Subtracting a negative',
      how: { text: '<p>Subtracting a negative: move <b>right</b>.</p><p>− (−3) means the same as + 3.</p><p class="ex">−2 − (−5) = −2 + 5 = 3</p>', fig: D.jumps({ min: -4, max: 5, start: -2, moves: [5], every: 1 }) },
      rounds: [{ text: 'Rewrite − (−) as +. Then work it out.', two: true,
        we: [{ q: '4 − (−2)', lines: ['= 4 + 2', '= 6'] }],
        you: [
          { q: '6 − (−3)', lines: ['= 6 + 3', '= 9'] },
          { q: '1 − (−7)', lines: ['= 1 + 7', '= 8'] },
          { q: '−2 − (−5)', lines: ['= −2 + 5', '= 3'] },
          { q: '−8 − (−3)', lines: ['= −8 + 3', '= −5'] },
          { q: '−4 − (−4)', lines: ['= −4 + 4', '= 0'] },
          { q: '−15 − (−20)', lines: ['= −15 + 20', '= 5'] },
        ] }] },
    { title: 'Mixed + and −',
      how: { text: '<p>First rewrite each − (−) as +.</p><p>Then work from left to right.</p><p class="ex">−3 − (−5) − 4 = −3 + 5 − 4 = 2 − 4 = −2</p>' },
      rounds: [{ text: 'Rewrite − (−) as +. Then work from left to right.',
        we: [{ q: '2 − (−3) − 6', lines: ['= 2 + 3 − 6', '= 5 − 6', '= −1'] }],
        you: [
          { q: '1 − (−4) − 7', lines: ['= 1 + 4 − 7', '= 5 − 7', '= −2'] },
          { q: '−3 − 5 − (−2)', lines: ['= −3 − 5 + 2', '= −8 + 2', '= −6'] },
          { q: '−6 − (−9) + (−5)', lines: ['= −6 + 9 + (−5)', '= 3 + (−5)', '= −2'] },
          { q: '10 − (−2) − 15', lines: ['= 10 + 2 − 15', '= 12 − 15', '= −3'] },
        ] }] },
    { title: 'Change and difference',
      how: { text: '<p>Change = new − old. A negative change is a fall.</p><p>Difference = higher − lower.</p><p class="ex">From −4°C to 6°C: 6 − (−4) = 6 + 4 = 10. A rise of 10°C.</p>' },
      rounds: [{ text: 'Write a subtraction. Then answer the question.',
        we: [{ q: 'It was −3°C, then 5°C. How much did it rise?', lines: ['5 − (−3)', '= 5 + 3', '= 8°C'] }],
        you: [
          { q: 'It was −6°C, then 2°C. How much did it rise?', lines: ['2 − (−6)', '= 2 + 6', '= 8°C'] },
          { q: 'A gull is at 25 m. A diver is at −15 m. How far apart are they?', lines: ['25 − (−15)', '= 25 + 15', '= 40 m'] },
          { q: 'A freezer is −18°C. The kitchen is 22°C. What is the difference?', lines: ['22 − (−18)', '= 22 + 18', '= 40°C'] },
          { q: 'It was 4°C, then −9°C. What was the change?', lines: ['−9 − 4', '= −13°C'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says 3 − (−2) = 5. 3 + 2 = 5. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −4 − 3 = −1. Is he right?', lines: ['start at −4, move 3 left', '= −7', 'No. The answer is −7.'] }],
        you: [
          { q: 'Mia says 2 − (−6) = −4. Is she right?', lines: ['= 2 + 6', '= 8', 'No. The answer is 8.'] },
          { q: 'Ben says −5 − (−5) = 0. Is he right?', lines: ['= −5 + 5', '= 0', 'Yes. Ben is right.'] },
          { q: 'Ali says −1 − 8 = −9. Is he right?', lines: ['start at −1, move 8 left', '= −9', 'Yes. Ali is right.'] },
          { q: 'Jo says subtracting always makes a number smaller. Is Jo right?', lines: ['4 − (−3) = 7', '7 is larger than 4', 'No. It can get larger.'] },
        ] }] },
  ] },

  '1.06': { steps: [
    { title: 'Equal groups',
      how: { text: '<p>3 × (−2) means 3 groups of −2.</p><p class="ex">(−2) + (−2) + (−2) = −6, so 3 × (−2) = −6.</p>', fig: D.groups({ n: 3, each: -2 }) },
      rounds: [{ text: 'Add the groups. Then write the answer.',
        we: [{ q: '2 × (−4)', lines: ['(−4) + (−4)', '= −8'] }],
        you: [
          { q: '2 × (−3)', lines: ['(−3) + (−3)', '= −6'] },
          { q: '3 × (−4)', lines: ['(−4) + (−4) + (−4)', '= −12'] },
          { q: '4 × (−2)', lines: ['(−2) + (−2) + (−2) + (−2)', '= −8'] },
          { q: '3 × (−10)', lines: ['(−10) + (−10) + (−10)', '= −30'] },
          { q: '2 × (−25)', lines: ['(−25) + (−25)', '= −50'] },
        ] }] },
    { title: 'The sign rules',
      how: { text: '<p><b>Same</b> signs: positive. <b>Different</b> signs: negative.</p><p>Multiply the numbers, then choose the sign.</p><p class="ex">−4 × 5: different signs: −. 4 × 5 = 20, so −20.</p>' },
      rounds: [{ text: 'Choose the sign. Then multiply.',
        we: [{ q: '−3 × 4', lines: ['different signs: −', '= −12'] }],
        you: [
          { q: '5 × (−2)', lines: ['different signs: −', '= −10'] },
          { q: '−6 × 3', lines: ['different signs: −', '= −18'] },
          { q: '−4 × (−2)', lines: ['same signs: +', '= 8'] },
          { q: '7 × (−5)', lines: ['different signs: −', '= −35'] },
          { q: '−9 × (−3)', lines: ['same signs: +', '= 27'] },
          { q: '−8 × 6', lines: ['different signs: −', '= −48'] },
        ] }] },
    { title: 'Why − × − is +',
      how: { text: '<p>Down the table, each answer goes <b>up 3</b>.</p><p>So a negative × a negative is positive.</p>', fig: table(['product', 'answer'], [['1 × (−3)', '−3'], ['0 × (−3)', '0'], ['−1 × (−3)', '3'], ['−2 × (−3)', '6']]) },
      rounds: [
        { text: 'Continue the pattern for two more lines.',
          we: [{ q: '1 × (−5) = −5, 0 × (−5) = 0, …', lines: ['−1 × (−5) = 5', '−2 × (−5) = 10'] }],
          you: [
            { q: '1 × (−4) = −4, 0 × (−4) = 0, …', lines: ['−1 × (−4) = 4', '−2 × (−4) = 8'] },
            { q: '1 × (−2) = −2, 0 × (−2) = 0, …', lines: ['−1 × (−2) = 2', '−2 × (−2) = 4'] },
          ] },
        { text: 'Now use the rule.', two: true,
          we: [{ q: '−2 × (−6)', lines: ['same signs: +', '= 12'] }],
          you: [
            { q: '−5 × (−4)', lines: ['same signs: +', '= 20'] },
            { q: '−7 × (−8)', lines: ['same signs: +', '= 56'] },
          ] },
      ] },
    { title: 'Three numbers',
      how: { text: '<p>Multiply two numbers at a time, left to right.</p><p>Check: an <b>even</b> number of negatives gives +, an <b>odd</b> number gives −.</p><p class="ex">−2 × 3 × (−4) = −6 × (−4) = 24</p>' },
      rounds: [{ text: 'Multiply from left to right.',
        we: [{ q: '2 × (−3) × 4', lines: ['= −6 × 4', '= −24'] }],
        you: [
          { q: '−2 × 5 × 3', lines: ['= −10 × 3', '= −30'] },
          { q: '3 × (−2) × (−5)', lines: ['= −6 × (−5)', '= 30'] },
          { q: '−3 × 4 × (−5)', lines: ['= −12 × (−5)', '= 60'] },
          { q: '−4 × (−2) × (−3)', lines: ['= 8 × (−3)', '= −24'] },
          { q: '−5 × (−2) × (−2) × (−3)', lines: ['= 10 × (−2) × (−3)', '= −20 × (−3)', '= 60'] },
        ] }] },
    { title: 'Multiplying in real life',
      how: { text: '<p>A change that repeats is a multiplication. Down, falling or spending is negative.</p><p class="ex">Down 3 m a minute for 5 minutes: 5 × (−3) = −15 m.</p>' },
      rounds: [{ text: 'Write a multiplication. Then answer the question.',
        we: [{ q: 'The temperature drops 2°C every hour for 4 hours. What is the total change?', lines: ['4 × (−2)', '= −8°C'] }],
        you: [
          { q: 'A diver goes down 4 m every minute for 6 minutes. What is her change in height?', lines: ['6 × (−4)', '= −24 m'] },
          { q: 'Sam spends $5 a day for 7 days. What is the change in Sam’s money?', lines: ['7 × (−5)', '= −$35'] },
          { q: 'A share price falls $3 a week for 9 weeks. What is the total change?', lines: ['9 × (−3)', '= −$27'] },
          { q: 'A lift at level 3 goes down 2 floors, 5 times. Which level is it on now?', lines: ['5 × (−2) = −10', '3 + (−10)', '= level −7'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says −4 × (−5) = 20. Same signs: +. 4 × 5 = 20. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −3 × 6 = 18. Is he right?', lines: ['different signs: −', '= −18', 'No. The answer is −18.'] }],
        you: [
          { q: 'Mia says −7 × (−2) = −14. Is she right?', lines: ['same signs: +', '= 14', 'No. The answer is 14.'] },
          { q: 'Ben says −4 × ☐ = 28 means ☐ = −7. Is he right?', lines: ['−4 × (−7)', '= 28', 'Yes. Ben is right.'] },
          { q: 'Ali says 3 × (−2) × (−5) = −30. Is he right?', lines: ['3 × (−2) = −6', '−6 × (−5) = 30', 'No. The answer is 30.'] },
          { q: 'Jo says −2 × (−3) × (−4) is positive. Is Jo right?', lines: ['−2 × (−3) = 6', '6 × (−4) = −24', 'No. It is −24.'] },
        ] }] },
  ] },

  '1.07': { steps: [
    { title: 'Division undoes ×',
      how: { text: '<p>Every × fact gives two ÷ facts.</p><p class="ex">3 × (−4) = −12, so<br>−12 ÷ 3 = −4 and −12 ÷ (−4) = 3.</p>' },
      rounds: [{ text: 'Write two ÷ facts from each × fact.',
        we: [{ q: '4 × (−2) = −8', lines: ['−8 ÷ 4 = −2', '−8 ÷ (−2) = 4'] }],
        you: [
          { q: '2 × (−5) = −10', lines: ['−10 ÷ 2 = −5', '−10 ÷ (−5) = 2'] },
          { q: '3 × (−6) = −18', lines: ['−18 ÷ 3 = −6', '−18 ÷ (−6) = 3'] },
          { q: '5 × (−4) = −20', lines: ['−20 ÷ 5 = −4', '−20 ÷ (−4) = 5'] },
          { q: '6 × (−7) = −42', lines: ['−42 ÷ 6 = −7', '−42 ÷ (−7) = 6'] },
        ] }] },
    { title: 'The sign rules',
      how: { text: '<p>The same as for ×. <b>Same</b> signs: positive. <b>Different</b> signs: negative.</p><p class="ex">−20 ÷ 4: different signs: −. 20 ÷ 4 = 5, so −5.</p>' },
      rounds: [{ text: 'Choose the sign. Then divide.',
        we: [{ q: '−18 ÷ 3', lines: ['different signs: −', '= −6'] }],
        you: [
          { q: '−12 ÷ 4', lines: ['different signs: −', '= −3'] },
          { q: '20 ÷ (−5)', lines: ['different signs: −', '= −4'] },
          { q: '−30 ÷ (−6)', lines: ['same signs: +', '= 5'] },
          { q: '−42 ÷ 7', lines: ['different signs: −', '= −6'] },
          { q: '−56 ÷ (−8)', lines: ['same signs: +', '= 7'] },
          { q: '72 ÷ (−9)', lines: ['different signs: −', '= −8'] },
        ] }] },
    { title: 'Missing numbers',
      how: { text: '<p>Use the opposite operation.</p><p class="ex">☐ ÷ (−3) = 5, so ☐ = 5 × (−3) = −15.</p><p class="ex">−24 ÷ ☐ = 6, so ☐ = −24 ÷ 6 = −4.</p>' },
      rounds: [{ text: 'Find the missing number. Use the opposite operation.',
        we: [{ q: '☐ ÷ 2 = −4', lines: ['☐ = −4 × 2', '☐ = −8'] }, { q: '−20 ÷ ☐ = 5', lines: ['☐ = −20 ÷ 5', '☐ = −4'] }],
        you: [
          { q: '☐ ÷ 3 = −6', lines: ['☐ = −6 × 3', '☐ = −18'] },
          { q: '☐ ÷ (−4) = 5', lines: ['☐ = 5 × (−4)', '☐ = −20'] },
          { q: '−30 ÷ ☐ = −6', lines: ['☐ = −30 ÷ (−6)', '☐ = 5'] },
          { q: '☐ ÷ (−7) = −3', lines: ['☐ = −3 × (−7)', '☐ = 21'] },
          { q: '48 ÷ ☐ = −8', lines: ['☐ = 48 ÷ (−8)', '☐ = −6'] },
        ] }] },
    { title: 'Dividing step by step',
      how: { text: '<p>Divide from left to right, one step at a time.</p><p class="ex">−60 ÷ 5 ÷ (−3) = −12 ÷ (−3) = 4</p>' },
      rounds: [{ text: 'Divide from left to right.',
        we: [{ q: '−24 ÷ 2 ÷ 3', lines: ['= −12 ÷ 3', '= −4'] }],
        you: [
          { q: '−40 ÷ 4 ÷ 2', lines: ['= −10 ÷ 2', '= −5'] },
          { q: '36 ÷ (−3) ÷ 2', lines: ['= −12 ÷ 2', '= −6'] },
          { q: '−48 ÷ (−4) ÷ (−3)', lines: ['= 12 ÷ (−3)', '= −4'] },
          { q: '−90 ÷ 3 ÷ (−5)', lines: ['= −30 ÷ (−5)', '= 6'] },
        ] }] },
    { title: 'Sharing equally',
      how: { text: '<p>Sharing a debt or a fall equally: divide a negative.</p><p class="ex">A fall of 12°C over 4 hours: −12 ÷ 4 = −3°C each hour.</p>' },
      rounds: [{ text: 'Write a division. Then answer the question.',
        we: [{ q: 'A debt of $20 is shared by 4 people. Write each share as an integer.', lines: ['−20 ÷ 4', '= −$5 each'] }],
        you: [
          { q: 'A debt of $36 is shared by 3 people. Write each share as an integer.', lines: ['−36 ÷ 3', '= −$12 each'] },
          { q: 'The temperature fell 15°C in 5 hours. What was the change each hour?', lines: ['−15 ÷ 5', '= −3°C each hour'] },
          { q: 'A diver went down 24 m in 6 minutes. What was her change each minute?', lines: ['−24 ÷ 6', '= −4 m each minute'] },
          { q: 'A share price fell $56 over 8 days, the same each day. What was the change each day?', lines: ['−56 ÷ 8', '= −$7 each day'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says −18 ÷ (−3) = 6. Same signs: +. 18 ÷ 3 = 6. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −24 ÷ 6 = 4. Is he right?', lines: ['different signs: −', '= −4', 'No. The answer is −4.'] }],
        you: [
          { q: 'Mia says 35 ÷ (−7) = −5. Is she right?', lines: ['different signs: −', '= −5', 'Yes. Mia is right.'] },
          { q: 'Ben says −40 ÷ (−8) = −5. Is he right?', lines: ['same signs: +', '= 5', 'No. The answer is 5.'] },
          { q: 'Ali says ☐ ÷ (−2) = 6 means ☐ = −3. Is he right?', lines: ['☐ = 6 × (−2)', '☐ = −12', 'No. ☐ is −12, not −3.'] },
          { q: 'Jo says dividing by a negative always gives a negative. Is Jo right?', lines: ['−12 ÷ (−3) = 4', '4 is positive', 'No. It can be positive.'] },
        ] }] },
  ] },

  '1.08': { steps: [
    { title: 'The order',
      how: { text: '<p>1. Brackets first.</p><p>2. × and ÷, left to right.</p><p>3. + and −, left to right.</p><p class="ex">−3 + 4 × 2 = −3 + 8 = 5</p>' },
      rounds: [{ text: 'Do the × or ÷ first. Then the + or −.', two: true,
        we: [{ q: '−5 + 2 × 3', lines: ['= −5 + 6', '= 1'] }],
        you: [
          { q: '−1 + 2 × 5', lines: ['= −1 + 10', '= 9'] },
          { q: '−10 + 3 × 2', lines: ['= −10 + 6', '= −4'] },
          { q: '6 − 4 × 3', lines: ['= 6 − 12', '= −6'] },
          { q: '−8 + 12 ÷ 4', lines: ['= −8 + 3', '= −5'] },
          { q: '−7 − 10 ÷ 2', lines: ['= −7 − 5', '= −12'] },
          { q: '4 × (−3) + 5', lines: ['= −12 + 5', '= −7'] },
        ] }] },
    { title: 'Brackets first',
      how: { text: '<p>Work out the brackets first.</p><p class="ex">(−3 + 7) × 2 = 4 × 2 = 8</p>' },
      rounds: [{ text: 'Brackets first. Then the rest.', two: true,
        we: [{ q: '(−2 + 5) × 3', lines: ['= 3 × 3', '= 9'] }],
        you: [
          { q: '(−4 + 6) × 5', lines: ['= 2 × 5', '= 10'] },
          { q: '(1 − 7) × 2', lines: ['= −6 × 2', '= −12'] },
          { q: '(−3 − 2) × 4', lines: ['= −5 × 4', '= −20'] },
          { q: '(−8 + 2) ÷ 3', lines: ['= −6 ÷ 3', '= −2'] },
          { q: '−2 × (5 − 9)', lines: ['= −2 × (−4)', '= 8'] },
          { q: '(−9 − 6) ÷ 5', lines: ['= −15 ÷ 5', '= −3'] },
        ] }] },
    { title: '× and ÷ before + and −',
      how: { text: '<p>Do every × and ÷ first. Then + and −, left to right.</p><p class="ex">−10 ÷ 2 + 3 × (−4) = −5 + (−12) = −17</p>' },
      rounds: [{ text: 'Do both × and ÷ in the first line.',
        we: [{ q: '2 × (−3) + 12 ÷ 4', lines: ['= −6 + 3', '= −3'] }],
        you: [
          { q: '3 × (−2) + 8 ÷ 2', lines: ['= −6 + 4', '= −2'] },
          { q: '−12 ÷ 3 − 2 × 5', lines: ['= −4 − 10', '= −14'] },
          { q: '4 × (−5) + (−18) ÷ 6', lines: ['= −20 + (−3)', '= −23'] },
          { q: '−3 × (−4) − 20 ÷ (−5)', lines: ['= 12 − (−4)', '= 12 + 4', '= 16'] },
        ] }] },
    { title: 'Left to right',
      how: { text: '<p>Same rank? Work from <b>left to right</b>.</p><p>The same goes for + and −.</p><p class="ex">−12 ÷ 3 × 2 = −4 × 2 = −8</p>' },
      rounds: [{ text: 'Work from left to right.',
        we: [{ q: '−20 ÷ 5 × 2', lines: ['= −4 × 2', '= −8'] }, { q: '3 − 7 + 2', lines: ['= −4 + 2', '= −2'] }],
        you: [
          { q: '−18 ÷ 6 × 3', lines: ['= −3 × 3', '= −9'] },
          { q: '6 − 10 + 3', lines: ['= −4 + 3', '= −1'] },
          { q: '24 ÷ (−4) × 2', lines: ['= −6 × 2', '= −12'] },
          { q: '−2 − 5 + 9', lines: ['= −7 + 9', '= 2'] },
          { q: '−30 ÷ (−5) × (−2)', lines: ['= 6 × (−2)', '= −12'] },
        ] }] },
    { title: 'Putting it together',
      how: { text: '<p>One step a line. Copy down everything you have not worked out yet.</p><p class="ex">−2 − (3 + (−5)) × 4 = −2 − (−2) × 4 = −2 − (−8) = 6</p>' },
      rounds: [{ text: 'Brackets, then × and ÷, then + and −.',
        we: [{ q: '5 − (2 − 6) × 3', lines: ['= 5 − (−4) × 3', '= 5 − (−12)', '= 17'] }],
        you: [
          { q: '−4 + (1 − 3) × 5', lines: ['= −4 + (−2) × 5', '= −4 + (−10)', '= −14'] },
          { q: '10 − (−2 + 6) × 3', lines: ['= 10 − 4 × 3', '= 10 − 12', '= −2'] },
          { q: '(−8 + 2) ÷ 3 − 4', lines: ['= −6 ÷ 3 − 4', '= −2 − 4', '= −6'] },
          { q: '−3 × (4 − 7) + (−10)', lines: ['= −3 × (−3) + (−10)', '= 9 + (−10)', '= −1'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says −3 + 4 × 2 = 5. 4 × 2 first: −3 + 8 = 5. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says −2 + 3 × 4 = 4. Is he right?', lines: ['3 × 4 = 12 first', '−2 + 12 = 10', 'No. The answer is 10.'] }],
        you: [
          { q: 'Mia says 6 − 2 × (−3) = 12. Is she right?', lines: ['2 × (−3) = −6 first', '6 − (−6) = 12', 'Yes. Mia is right.'] },
          { q: 'Ben says −12 ÷ 2 × 3 = −2. Is he right?', lines: ['left to right: −12 ÷ 2 = −6', '−6 × 3 = −18', 'No. The answer is −18.'] },
          { q: 'Ali says (−5 + 3) × 2 = −4. Is he right?', lines: ['brackets first: −2', '−2 × 2 = −4', 'Yes. Ali is right.'] },
          { q: 'Jo says −4 + 6 × 3 = 6. Is Jo right?', lines: ['6 × 3 first: −4 + 18', '= 14', 'No. (−4 + 6) × 3 = 6.'] },
        ] }] },
  ] },

  '1.09': { steps: [
    { title: 'The (−) key',
      how: { text: '<p>Use <b>(−)</b> for a negative number. Use <b>−</b> to subtract.</p><p>Got a <b>+/−</b> key instead? Press it after the number.</p><p class="ex">−35 + 12 = −23. Press:</p>', fig: D.keys(['(−)', '3', '5', '+', '1', '2', '=']) },
      rounds: [{ text: 'Write the keys you press. Then the answer.', two: true,
        we: [{ q: '−48 + 25', lines: ['(−) 48 + 25 =', '= −23'] }],
        you: [
          { q: '−63 + 41', lines: ['(−) 63 + 41 =', '= −22'] },
          { q: '−27 − 38', lines: ['(−) 27 − 38 =', '= −65'] },
          { q: '−150 + 86', lines: ['(−) 150 + 86 =', '= −64'] },
          { q: '45 − 112', lines: ['45 − 112 =', '= −67'] },
          { q: '−208 − 97', lines: ['(−) 208 − 97 =', '= −305'] },
          { q: '−76 + 176', lines: ['(−) 76 + 176 =', '= 100'] },
        ] }] },
    { title: '× and ÷ with negatives',
      how: { text: '<p>Put brackets around a negative that comes after × or ÷.</p><p class="ex">−24 × (−15) = 360. Press:</p>', fig: D.keys(['(−)', '2', '4', '×', '(', '(−)', '1', '5', ')', '=']) },
      rounds: [{ text: 'Write the keys you press. Then the answer.',
        we: [{ q: '−18 × 12', lines: ['(−) 18 × 12 =', '= −216'] }],
        you: [
          { q: '−23 × 15', lines: ['(−) 23 × 15 =', '= −345'] },
          { q: '36 × (−14)', lines: ['36 × ( (−) 14 ) =', '= −504'] },
          { q: '−540 ÷ 12', lines: ['(−) 540 ÷ 12 =', '= −45'] },
          { q: '−27 × (−31)', lines: ['(−) 27 × ( (−) 31 ) =', '= 837'] },
          { q: '−1 196 ÷ (−26)', lines: ['(−) 1196 ÷ ( (−) 26 ) =', '= 46'] },
        ] }] },
    { title: 'Check the sign first',
      how: { text: '<p>Before you press =, use the sign rules: + or −?</p><p>If the calculator disagrees, check your keys.</p><p class="ex">−48 × 25: different signs: −. The answer is −1 200.</p>' },
      rounds: [{ text: 'Choose the sign first. Then use the calculator.',
        we: [{ q: '−34 × 29', lines: ['different signs: −', '= −986'] }],
        you: [
          { q: '−52 × (−18)', lines: ['same signs: +', '= 936'] },
          { q: '65 × (−24)', lines: ['different signs: −', '= −1 560'] },
          { q: '−3 024 ÷ 56', lines: ['different signs: −', '= −54'] },
          { q: '−2 491 ÷ (−47)', lines: ['same signs: +', '= 53'] },
          { q: '−125 × 16', lines: ['different signs: −', '= −2 000'] },
        ] }] },
    { title: 'Brackets on the calculator',
      how: { text: '<p>Press ( and ) for brackets. The calculator follows the order of operations.</p><p class="ex">(−35 − 47) × 12 = −984</p>', fig: D.keys(['(', '(−)', '3', '5', '−', '4', '7', ')', '×', '1', '2', '=']) },
      rounds: [{ text: 'Write the value of the brackets. Then the answer.',
        we: [{ q: '(−28 + 13) × 6', lines: ['bracket: −15', '= −90'] }],
        you: [
          { q: '(−45 − 19) × 5', lines: ['bracket: −64', '= −320'] },
          { q: '(36 − 81) × (−4)', lines: ['bracket: −45', '= 180'] },
          { q: '(−120 + 48) ÷ 8', lines: ['bracket: −72', '= −9'] },
          { q: '(−67 − 58) ÷ (−25)', lines: ['bracket: −125', '= 5'] },
        ] }] },
    { title: 'Estimate, then calculate',
      how: { text: '<p>Round to the nearest 10 and work it out in your head. Then check on the calculator.</p><p class="ex">−48 × 21 ≈ −50 × 20 = −1 000. Calculator: −1 008.</p>' },
      rounds: [{ text: 'Estimate first. Then use the calculator.',
        we: [{ q: '−39 × 21', lines: ['≈ −40 × 20 = −800', '= −819'] }],
        you: [
          { q: '−52 × 19', lines: ['≈ −50 × 20 = −1 000', '= −988'] },
          { q: '−61 × (−29)', lines: ['≈ −60 × (−30) = 1 800', '= 1 769'] },
          { q: '78 × (−41)', lines: ['≈ 80 × (−40) = −3 200', '= −3 198'] },
          { q: '−403 + 198', lines: ['≈ −400 + 200 = −200', '= −205'] },
        ] }] },
    { title: 'Calculator problems',
      how: { text: '<p>Write a number sentence first. Then use the calculator.</p><p class="ex">$250, then 6 payments of $45: 250 − 6 × 45 = −20. The balance is −$20.</p>' },
      rounds: [{ text: 'Write a number sentence. Then use the calculator.',
        we: [{ q: 'An account has $120. Four payments of $38 come out. What is the balance?', lines: ['120 − 4 × 38', '= −$32'] }],
        you: [
          { q: 'A submarine at −185 m rises 12 m a minute for 9 minutes. Where is it now?', lines: ['−185 + 9 × 12', '= −77 m'] },
          { q: 'It is −14°C. It warms 3°C an hour for 7 hours. What is the temperature?', lines: ['−14 + 7 × 3', '= 7°C'] },
          { q: 'An account has $85. Seven payments of $26 come out. What is the balance?', lines: ['85 − 7 × 26', '= −$97'] },
          { q: 'A diver at −42 m goes down 6 m a minute for 8 minutes. Where is she now?', lines: ['−42 − 8 × 6', '= −90 m'] },
        ] }] },
  ] },

  '1.10': { steps: [
    { title: 'Temperature',
      how: { text: '<p>A rise is +. A fall is −.</p><p class="ex">−5°C, then a rise of 8°C: −5 + 8 = 3°C.</p>', fig: D.thermometer({ min: -10, max: 5, value: 3, unit: 1.2, every: 5, arrows: [{ v: 3, text: 'after' }, { v: -5, text: 'before' }], w: 36 }) },
      rounds: [{ text: 'Write a sum. Then the new temperature.',
        we: [{ q: '−6°C, rises 4°C', lines: ['−6 + 4', '= −2°C'] }],
        you: [
          { q: '−3°C, rises 9°C', lines: ['−3 + 9', '= 6°C'] },
          { q: '2°C, falls 5°C', lines: ['2 − 5', '= −3°C'] },
          { q: '−1°C, falls 6°C', lines: ['−1 − 6', '= −7°C'] },
          { q: '−8°C, rises 8°C', lines: ['−8 + 8', '= 0°C'] },
          { q: '−12°C, rises 15°C', lines: ['−12 + 15', '= 3°C'] },
        ] }] },
    { title: 'Above and below sea level',
      how: { text: '<p>Above sea level is +. Below is −.</p><p>Distance apart = higher − lower.</p><p class="ex">A gull at 20 m and a diver at −10 m: 20 − (−10) = 30 m.</p>' },
      rounds: [{ text: 'How far apart are they? Write a subtraction.',
        we: [{ q: 'A gull at 20 m and a diver at −5 m', lines: ['20 − (−5)', '= 25 m'] }],
        you: [
          { q: 'A boat at 0 m and a diver at −12 m', lines: ['0 − (−12)', '= 12 m'] },
          { q: 'A cliff top at 30 m and a diver at −8 m', lines: ['30 − (−8)', '= 38 m'] },
          { q: 'A lighthouse top at 45 m and a diver at −20 m', lines: ['45 − (−20)', '= 65 m'] },
          { q: 'A diver at −5 m and a wreck at −22 m', lines: ['−5 − (−22)', '= 17 m'] },
          { q: 'A bird at 42 m and a shark at −37 m', lines: ['42 − (−37)', '= 79 m'] },
        ] }] },
    { title: 'Lifts and floors',
      how: { text: '<p>The ground floor is level 0. Basements are negative.</p><p class="ex">Level −2, up 5 floors: −2 + 5 = level 3.</p>', fig: D.vscale({ min: -3, max: 4, unit: 2.4, every: 1, kind: 'ground', marks: [{ v: -2, text: 'start' }, { v: 3, text: 'finish' }], w: 40 }) },
      rounds: [{ text: 'Write a sum. Then the level.',
        we: [{ q: 'A lift at level −1 goes up 4 floors. Which level is it on?', lines: ['−1 + 4', '= level 3'] }],
        you: [
          { q: 'A lift at level 2 goes down 5 floors. Which level is it on?', lines: ['2 − 5', '= level −3'] },
          { q: 'A lift at level −3 goes up 8 floors. Which level is it on?', lines: ['−3 + 8', '= level 5'] },
          { q: 'A lift at level 5 goes down 9 floors. Which level is it on?', lines: ['5 − 9', '= level −4'] },
          { q: 'A lift at level −2 goes down 2, then up 7. Which level is it on?', lines: ['−2 − 2 + 7', '= level 3'] },
        ] }] },
    { title: 'Money',
      how: { text: '<p>Money in is +. Money out is −. Below $0 means you owe money.</p><p class="ex">$20, then pay $35: 20 − 35 = −15. The balance is −$15.</p>' },
      rounds: [{ text: 'Write a sum. Then the new balance.',
        we: [{ q: 'The balance is $30. You pay $45.', lines: ['30 − 45', '= −$15'] }],
        you: [
          { q: 'The balance is $12. You pay $25.', lines: ['12 − 25', '= −$13'] },
          { q: 'The balance is −$20. You pay in $50.', lines: ['−20 + 50', '= $30'] },
          { q: 'The balance is −$15. You pay $30.', lines: ['−15 − 30', '= −$45'] },
          { q: 'The balance is $40. You pay $25, then $30.', lines: ['40 − 25 − 30', '= −$15'] },
          { q: 'The balance is −$60. You pay in $35, then $40.', lines: ['−60 + 35 + 40', '= $15'] },
        ] }] },
    { title: 'Several steps',
      how: { text: '<p>Break it into steps. One number sentence a step.</p><p class="ex">−40 m, up 3 m a minute for 5 minutes: 3 × 5 = 15, −40 + 15 = −25 m.</p>' },
      rounds: [{ text: 'Write a number sentence for each step.',
        we: [{ q: 'It is −6°C. It warms 2°C an hour for 5 hours. How warm is it now?', lines: ['2 × 5 = 10, −6 + 10', '= 4°C'] }],
        you: [
          { q: 'A diver at −30 m rises 4 m a minute for 6 minutes. Where is she?', lines: ['4 × 6 = 24, −30 + 24', '= −6 m'] },
          { q: 'It is 5°C. It cools 3°C an hour for 4 hours. How cold is it now?', lines: ['4 × (−3) = −12, 5 + (−12)', '= −7°C'] },
          { q: 'A win scores +3, a loss −2. A team wins 4 and loses 7. What is its score?', lines: ['4 × 3 + 7 × (−2) = 12 + (−14)', '= −2'] },
          { q: 'Sam has $50 and pays $12 a week for 6 weeks. What is the balance?', lines: ['6 × 12 = 72, 50 − 72', '= −$22'] },
        ] }] },
    { title: 'Is it right?',
      how: judge('Kim says −4°C, then a rise of 6°C, is 2°C. −4 + 6 = 2. Yes, Kim is right.'),
      rounds: [{ text: 'Is it right? Explain your answer.',
        we: [{ q: 'Tom says level −3, up 5 floors, is level −8. Is he right?', lines: ['−3 + 5', '= 2', 'No. It is at level 2.'] }],
        you: [
          { q: 'Mia says 12 m and −9 m are 3 m apart. Is she right?', lines: ['12 − (−9)', '= 21', 'No. They are 21 m apart.'] },
          { q: 'Ben says −$20, then $35 in, leaves $15. Is he right?', lines: ['−20 + 35', '= 15', 'Yes. Ben is right.'] },
          { q: 'Ali says 3°C, falling 8°C, gives −5°C. Is he right?', lines: ['3 − 8', '= −5', 'Yes. Ali is right.'] },
          { q: 'Jo says it is warmer at −4°C than at −9°C. Is Jo right?', lines: ['−4 is higher than −9', 'so −4°C is warmer', 'Yes. Jo is right.'] },
        ] }] },
  ] },

};

// "Check yourself": one last question at the end of step 6 with no scaffold at all, only where it fits without
// crowding the column (tried in every lesson; only these fit).
const CHECKS = {
  '1.02': { q: 'Which integer is halfway between −9 and 3?', lines: ['= −3'] },
  '1.09': { q: '(−37 − 89) × (−15)', lines: ['= 1 890'] },
};
Object.entries(CHECKS).forEach(([code, check]) => { module.exports[code].steps[5].check = check; });

