// Year 7 Chapter 5: Algebra and equations. One 4-page lesson per exercise in Test Yourself 5 (there is no 5.06 in the Test Yourself).
const lesson = require('../../lib/lesson');
const { ev, F } = require('../../lib/calc');

const evs = (xs) => xs.map((e) => ev(e));
// Algebra display: letters in italics, ^n as a superscript, - as a true minus. Only use on pure expressions.
const al = (s) => s.replace(/([a-zA-Z])/g, '<i>$1</i>').replace(/\^(\d+)/g, '<sup>$1</sup>').replace(/(^|[\s(=×÷])-/g, '$1−').replace(/ - /g, ' − ');
const f = (n, d) => F(n, d);
const fa = (n, d) => F(al(n), al(d));
const sub = (expr, vals) => ev(Object.entries(vals).reduce((e, [k, v]) => e.replace(new RegExp(k, 'g'), `(${v})`), expr));

module.exports = {
  year: 7, stage: 4, number: 5, title: 'Algebra and equations', accent: '#148f77',
  fileName: 'Year7-Ch05-Algebra-and-equations',
  goals: ['use the commutative, associative and distributive laws', 'use variables and algebraic notation', 'write expressions from words and substitute into them', 'simplify by adding, subtracting, multiplying and dividing terms',
    'solve one-step and two-step equations', 'solve problems using equations'],
  syllabus: 'NSW Mathematics K–10 Syllabus (2022), Stage 4 Number and algebra: MA4-ALG-C-01 generalises number properties to operate with algebraic expressions, and MA4-EQU-C-01 solves linear equations.',
  lessons: [
    lesson({
      code: '5.01', title: 'The commutative and associative laws',
      li: ['use the commutative and associative laws to make calculations easier'],
      sc: ['know that order does not matter for + and × (commutative law)', 'know that grouping does not matter for + and × (associative law)', 'regroup numbers to make friendly pairs such as 10s and 100s'],
      terms: ['Commutative', 'Associative'],
      we: ['7 + 18 + 3', '91 + 18 + 9', '2 × 17 × 5', '25 × 31 × 4', '13 × 30', '7 × 400'],
      a: { text: 'Evaluate by pairing friendly numbers.', kind: 'short', items: ['7 + 18 + 3', '91 + 18 + 9', '46 + 25 + 4', '15 + 38 + 5', '64 + 17 + 36', '8 + 29 + 12 + 1'] },
      b: { text: 'Evaluate by pairing friendly numbers.', kind: 'short', items: ['2 × 17 × 5', '25 × 31 × 4', '5 × 9 × 20', '4 × 13 × 25', '50 × 7 × 2', '2 × 8 × 5 × 5'] },
      c: { text: 'Evaluate mentally.', kind: 'work', cols: 3, items: ['13 × 30', '7 × 400', '12 × 50', '30 × 80', '600 × 4', '25 × 12'] },
      d: { text: 'Think it through.', kind: 'work', items: ['Does the commutative law work for subtraction? Test it with 10 − 4.', 'Does the associative law work for division? Test it with (24 ÷ 6) ÷ 2.', 'Evaluate 125 × 17 × 8 mentally.', 'Evaluate 1 + 2 + 3 + … + 20 by pairing numbers.'] },
      ext: { q: 'Evaluate 4 × 7 × 25 × 3 × 5 × 2 mentally.', steps: ['Regroup: (4 × 25) × (5 × 2) × 7 × 3', '100 × 10 × 21'], a: '21 000', qs: ['Evaluate 8 × 125 × 9 × 5 × 2 mentally.', 'Explain why 38 + 47 + 62 + 53 is easy to do mentally.'] },
      summary: { steps: ['Commutative: a + b = b + a and a × b = b × a.', 'Associative: (a + b) + c = a + (b + c).', 'Look for pairs making 10, 100 or 1000.', 'Not true for − and ÷.'],
        worked: [['7 + 18 + 3', ['(7 + 3) + 18'], '28'], ['25 × 31 × 4', ['(25 × 4) × 31'], '3100'], ['13 × 30', ['13 × 3 × 10'], '390'], ['4 × 7 × 25 × 3 × 5 × 2', ['100 × 10 × 21'], '21 000']] },
      exit: { qs: ['Evaluate 16 + 27 + 4.', 'Evaluate 5 × 23 × 2.', 'Evaluate 20 × 13 × 5.'] },
      ans: { we: evs(['7 + 18 + 3', '91 + 18 + 9', '2 × 17 × 5', '25 × 31 × 4', '13 × 30', '7 × 400']), a: evs(['7 + 18 + 3', '91 + 18 + 9', '46 + 25 + 4', '15 + 38 + 5', '64 + 17 + 36', '8 + 29 + 12 + 1']), b: evs(['2 × 17 × 5', '25 × 31 × 4', '5 × 9 × 20', '4 × 13 × 25', '50 × 7 × 2', '2 × 8 × 5 × 5']),
        c: evs(['13 × 30', '7 × 400', '12 × 50', '30 × 80', '600 × 4', '25 × 12']), d: ['No: 10 − 4 = 6 but 4 − 10 = −6', 'No: (24 ÷ 6) ÷ 2 = 2 but 24 ÷ (6 ÷ 2) = 8', ev('125 × 17 × 8'), '210 (10 pairs of 21)'], ext: [ev('8 × 125 × 9 × 5 × 2'), '38 + 62 = 100 and 47 + 53 = 100'], exit: evs(['16 + 27 + 4', '5 × 23 × 2', '20 × 13 × 5']) },
    }),

    lesson({
      code: '5.02', title: 'The distributive law',
      li: ['use the distributive law for mental arithmetic'],
      sc: ['split a number into tens and units, or a friendly number ± a bit', 'multiply each part, then add or subtract', 'choose the easiest way to split'],
      terms: ['Distributive law', 'Expand'],
      we: ['22 × 9 as 22 × (10 − 1)', '17 × 8 as (10 + 7) × 8', '27 × 11', '13 × 12', '48 × 6', '99 × 35'],
      a: { text: 'Complete the working to evaluate.', kind: 'short', items: ['14 × 6 = 10 × 6 + 4 × 6', '23 × 4 = 20 × 4 + 3 × 4', '31 × 7 = 30 × 7 + 1 × 7', '19 × 5 = 20 × 5 − 1 × 5', '42 × 3 = 40 × 3 + 2 × 3', '29 × 4 = 30 × 4 − 1 × 4'] },
      b: { text: 'Use the distributive law to evaluate.', kind: 'short', items: ['22 × 9', '17 × 8', '27 × 11', '13 × 12', '15 × 7', '39 × 3'] },
      c: { text: 'Use the distributive law. Show your working.', kind: 'work', cols: 3, items: ['48 × 6', '99 × 35', '101 × 23', '53 × 12', '8 × 199', '65 × 21'] },
      d: { text: 'Think it through.', kind: 'work', items: ['Evaluate 7 × 68 + 7 × 32 mentally.', 'Evaluate 15 × 43 − 15 × 33 mentally.', 'Show two different ways to evaluate 18 × 25.', 'Explain why 6 × 97 = 6 × 100 − 6 × 3.'] },
      ext: { q: 'Evaluate 999 × 47 mentally.', steps: ['999 = 1000 − 1', '47 000 − 47'], a: '46 953', qs: ['Evaluate 1001 × 64 mentally.', 'Evaluate 37 × 99 + 37 mentally.'] },
      summary: { steps: ['a × (b + c) = a × b + a × c.', 'Split into tens and units: 17 = 10 + 7.', 'Or near a friendly number: 9 = 10 − 1.', 'Multiply each part, then add or subtract.'],
        worked: [['22 × 9', ['22 × 10 − 22'], '198'], ['17 × 8', ['80 + 56'], '136'], ['99 × 35', ['3500 − 35'], '3465'], ['999 × 47', ['47 000 − 47'], '46 953']] },
      exit: { qs: ['Evaluate 12 × 7 using the distributive law.', 'Evaluate 19 × 6.', 'Evaluate 102 × 45.'] },
      ans: { we: evs(['22 × 9', '17 × 8', '27 × 11', '13 × 12', '48 × 6', '99 × 35']), a: evs(['14 × 6', '23 × 4', '31 × 7', '19 × 5', '42 × 3', '29 × 4']), b: evs(['22 × 9', '17 × 8', '27 × 11', '13 × 12', '15 × 7', '39 × 3']),
        c: evs(['48 × 6', '99 × 35', '101 × 23', '53 × 12', '8 × 199', '65 × 21']), d: ['7 × 100 = 700', '15 × 10 = 150', 'e.g. 18 × 25 = 10 × 25 + 8 × 25 = 450; or 20 × 25 − 2 × 25 = 450', '97 = 100 − 3, so multiply each part by 6'], ext: [ev('1001 × 64'), ev('37 × 100')], exit: evs(['12 × 7', '19 × 6', '102 × 45']) },
    }),

    lesson({
      code: '5.03', title: 'Variables and algebraic notation',
      li: ['use a variable to describe a pattern', 'write and read algebraic notation'],
      sc: ['write a general rule using a variable', 'simplify notation, e.g. 5 × a × 2 = 10<i>a</i>', 'write a term in expanded form'],
      terms: ['Variable', 'Pronumeral', 'Term'],
      we: ['Write the rule for: 3 − (−3) = 2 × 3, 5 − (−5) = 2 × 5, 11 − (−11) = 2 × 11', `Simplify ${al('x + x + x + x')}.`, `Simplify ${al('5 × a × 2')}.`, `Simplify ${al('8 × c × b × 3 × a')}.`, `Write ${al('4mnk')} in expanded form.`, `Write ${al('9c^2')} and ${fa('6a', 'b')} in expanded form.`],
      a: { text: 'Simplify.', kind: 'short', items: [al('x + x + x + x'), al('u ÷ 5'), al('2y - y'), al('5 × a × 2'), al('m × 7'), al('p × q')] },
      b: { text: 'Simplify.', kind: 'short', items: [al('8 × c × b × 3 × a'), al('2 × m × w × 10 × w'), al('k × k × k'), al('3 × y × y'), al('a + a + b + b + b'), al('4 × d ÷ 2')] },
      c: { text: 'Write in expanded form.', kind: 'work', cols: 3, items: [al('4mnk'), fa('6a', 'b'), al('9c^2'), al('3xy^2'), al('a^3b'), fa('5m', '2n')] },
      d: { text: 'Patterns and rules.', kind: 'work', items: ['Write a rule for: 4 + 4 = 2 × 4, 7 + 7 = 2 × 7, 10 + 10 = 2 × 10', 'Write a rule for: 3 × 0 = 0, 8 × 0 = 0, 15 × 0 = 0', 'Matchstick squares: 1 square uses 4 sticks, 2 squares use 7, 3 squares use 10. Find a rule for <i>n</i> squares.', `Is ${al('3a^2')} the same as ${al('(3a)^2')}? Explain.`] },
      ext: { q: 'Write a rule for the pattern: 1 × 3 = 2² − 1, 2 × 4 = 3² − 1, 3 × 5 = 4² − 1', steps: ['First number is n, second is n + 2', 'The square is of n + 1'], a: `${al('n(n + 2) = (n + 1)^2 - 1')}`, qs: ['Write a rule for: 5 × 5 − 4 × 6 = 1, 8 × 8 − 7 × 9 = 1, 3 × 3 − 2 × 4 = 1', 'Test your rule with a number of your own.'] },
      summary: { steps: ['A <b>variable</b> is a letter that stands for a number.', 'Leave out ×: 3 × a = 3<i>a</i>. Number first, letters in order.', 'a × a = a²; a ÷ 5 = a/5.', 'Expanded form shows every ×.'],
        worked: [['Rule for 3 − (−3) = 2 × 3…', ['Replace the number with a'], `${al('a - (-a) = 2a')}`], [al('5 × a × 2'), ['5 × 2 = 10'], al('10a')], [al('2 × m × w × 10 × w'), ['20 × m × w²'], al('20mw^2')], [al('9c^2'), ['9 × c × c'], al('9 × c × c')]] },
      exit: { qs: [`Simplify ${al('y + y + y')}.`, `Simplify ${al('4 × p × 3 × q')}.`, `Write ${al('5a^2b')} in expanded form.`] },
      ans: { we: [al('a - (-a) = 2 × a'), al('4x'), al('10a'), al('24abc'), al('4 × m × n × k'), `${al('9 × c × c')}; ${al('6 × a ÷ b')}`], a: [al('4x'), fa('u', '5'), al('y'), al('10a'), al('7m'), al('pq')], b: [al('24abc'), al('20mw^2'), al('k^3'), al('3y^2'), al('2a + 3b'), al('2d')],
        c: [al('4 × m × n × k'), al('6 × a ÷ b'), al('9 × c × c'), al('3 × x × y × y'), al('a × a × a × b'), al('5 × m ÷ (2 × n)')], d: [al('a + a = 2 × a'), al('a × 0 = 0'), `${al('3n + 1')} sticks`, `No: ${al('3a^2 = 3 × a × a')} but ${al('(3a)^2 = 9 × a × a')}`], ext: [al('n × n - (n - 1)(n + 1) = 1'), 'check'], exit: [al('3y'), al('12pq'), al('5 × a × a × b')] },
    }),

    lesson({
      code: '5.04', title: 'Expressions from words',
      li: ['write algebraic expressions from worded statements'],
      sc: ['know the words for +, −, × and ÷ (sum, difference, product, quotient)', 'write an expression using a variable', 'use brackets when needed'],
      terms: ['Expression', 'Consecutive'],
      we: ['3 times the number <i>N</i>', 'the difference between <i>N</i> and 5', 'the next consecutive number after <i>N</i>', 'one-third of <i>N</i>', '2<i>H</i> decreased by <i>k</i>', 'double the sum of <i>x</i> and 4'],
      a: { text: 'Write an expression. Use <i>N</i> for the number.', kind: 'short', items: ['the number plus 7', '3 times the number', 'the number minus 5', 'the number divided by 4', 'the next consecutive number', 'one-third of the number'] },
      b: { text: 'Write an expression.', kind: 'short', items: ['the sum of <i>M</i> and 3', '5 more than <i>B</i>', '2<i>H</i> decreased by <i>k</i>', 'the product of <i>a</i> and <i>b</i>', '10 less than <i>y</i>', '<i>p</i> shared equally among 6'] },
      c: { text: 'Write an expression.', kind: 'work', cols: 3, items: ['double the sum of <i>x</i> and 4', 'the square of <i>t</i>', '7 less than 3 times <i>w</i>', 'half of the difference between <i>m</i> and 1', 'the number before <i>n</i>', 'the average of <i>a</i> and <i>b</i>'] },
      d: { text: 'Write an expression for each situation.', kind: 'work', items: ['The cost of <i>n</i> pens at $3 each.', 'Sam is <i>s</i> years old. His sister is 4 years older. Find the sum of their ages.', 'A rectangle is <i>L</i> cm long and 5 cm wide. Write its perimeter.', 'The change from $50 after buying <i>k</i> drinks at $2.50 each.'] },
      ext: { q: 'Write an expression for the sum of three consecutive numbers starting at <i>n</i>, and simplify it.', steps: [`${al('n + (n + 1) + (n + 2)')}`, 'Collect like terms'], a: al('3n + 3'), qs: ['Write and simplify the sum of three consecutive even numbers starting at <i>e</i>.', 'Explain why the sum of 3 consecutive numbers is always divisible by 3.'] },
      summary: { steps: ['Sum → +, difference → −.', 'Product → ×, quotient → ÷.', 'More than → +, less than → − (order!).', 'Use brackets when a whole group is multiplied.'],
        worked: [['3 times N', ['3 × N'], al('3N')], ['N decreased by 5', ['N − 5'], al('N - 5')], ['Double the sum of x and 4', ['Brackets first'], al('2(x + 4)')], ['3 consecutive numbers', [al('n + n + 1 + n + 2')], al('3n + 3')]] },
      exit: { qs: ['Write “the number plus 12” using <i>N</i>.', 'Write “4 less than <i>y</i>”.', 'Write “the product of <i>m</i> and 5, then add 2”.'] },
      ans: { we: [al('3N'), al('N - 5'), al('N + 1'), fa('N', '3'), al('2H - k'), al('2(x + 4)')], a: [al('N + 7'), al('3N'), al('N - 5'), fa('N', '4'), al('N + 1'), fa('N', '3')], b: [al('M + 3'), al('B + 5'), al('2H - k'), al('ab'), al('y - 10'), fa('p', '6')],
        c: [al('2(x + 4)'), al('t^2'), al('3w - 7'), fa('m - 1', '2'), al('n - 1'), fa('a + b', '2')], d: [al('3n') + ' dollars', al('2s + 4'), al('2L + 10'), al('50 - 2.5k')], ext: [al('3e + 6'), al('3n + 3 = 3(n + 1)')], exit: [al('N + 12'), al('y - 4'), al('5m + 2')] },
    }),

    lesson({
      code: '5.05', title: 'Substitution',
      li: ['find the value of an expression by substituting numbers'],
      sc: ['replace each variable with its value, using brackets', 'follow the order of operations', 'substitute into a formula'],
      terms: ['Substitute', 'Evaluate', 'Formula'],
      we: ['If <i>a</i> = 2 and <i>b</i> = 5, find <i>a</i> + <i>b</i>.', 'If <i>a</i> = 2 and <i>c</i> = 6, find 3<i>a</i> − <i>c</i>.', 'If <i>a</i> = 2, <i>b</i> = 5, <i>c</i> = 6, find <i>abc</i>.', 'If <i>C</i> = 30<i>h</i> + 19, find <i>C</i> when <i>h</i> = 3.', 'Find <i>C</i> when <i>h</i> = −1.', 'Find <i>C</i> when <i>h</i> = 2.5.'],
      given: '',
      a: { text: 'If <i>a</i> = 2, <i>b</i> = 5 and <i>c</i> = 6, evaluate:', kind: 'short', items: [al('a + b'), al('c - a'), al('4b'), al('bc'), al('a + b + c'), al('3a - c')] },
      b: { text: 'If <i>a</i> = 2, <i>b</i> = 5 and <i>c</i> = 6, evaluate:', kind: 'short', items: [al('a + 2b - c'), al('abc'), al('c^2'), fa('c', 'a'), al('2(a + b)'), al('b^2 - c')] },
      c: { text: 'If <i>C</i> = 30<i>h</i> + 19, find <i>C</i> when:', kind: 'work', cols: 3, items: ['<i>h</i> = 3', '<i>h</i> = −1', '<i>h</i> = 5', '<i>h</i> = 2.5', '<i>h</i> = 0', '<i>h</i> = 10'] },
      d: { text: 'Substitute into each formula.', kind: 'work', items: ['<i>P</i> = 2<i>L</i> + 2<i>W</i>. Find <i>P</i> when <i>L</i> = 8 and <i>W</i> = 3.', '<i>A</i> = ½<i>bh</i>. Find <i>A</i> when <i>b</i> = 10 and <i>h</i> = 7.', '<i>F</i> = 1.8<i>C</i> + 32. Find <i>F</i> when <i>C</i> = 25.', `If <i>x</i> = −3, evaluate ${al('x^2 + 2x')}.`] },
      ext: { q: 'A taxi charges <i>C</i> = 4 + 2.5<i>k</i> dollars for <i>k</i> km. How far can you go for $39?', steps: ['39 = 4 + 2.5k', '35 = 2.5k', 'k = 35 ÷ 2.5'], a: '14 km', qs: ['Using the same formula, find the cost of a 22 km trip.', 'A phone plan costs C = 15 + 0.2m for m minutes. How many minutes for $27?'] },
      summary: { steps: ['Write the expression.', 'Replace each variable with its value in brackets.', 'Use the order of operations.', 'Remember 3<i>a</i> means 3 × <i>a</i>.'],
        worked: [['a + b, a = 2, b = 5', ['2 + 5'], '7'], ['3a − c', ['3 × 2 − 6'], '0'], ['C = 30h + 19, h = −1', ['30 × (−1) + 19'], '−11'], ['Taxi for $39', ['2.5k = 35'], '14 km']] },
      exit: { qs: ['If <i>m</i> = 4, evaluate 5<i>m</i>.', 'If <i>x</i> = 3 and <i>y</i> = 7, evaluate 2<i>x</i> + <i>y</i>.', 'If <i>A</i> = <i>l</i>² − 3<i>l</i>, find <i>A</i> when <i>l</i> = −2.'] },
      ans: { we: ['7', '0', '60', '109', '−11', '94'], a: ['a + b', 'c - a', '4*b', 'b*c', 'a + b + c', '3*a - c'].map((e) => sub(e, { a: 2, b: 5, c: 6 })), b: ['a + 2*b - c', 'a*b*c', 'c*c', 'c/a', '2*(a + b)', 'b*b - c'].map((e) => sub(e, { a: 2, b: 5, c: 6 })),
        c: [3, -1, 5, 2.5, 0, 10].map((h) => ev(`30 × ${h < 0 ? `(${h})` : h} + 19`)), d: ['22', '35', '77', '3'], ext: ['$59', '60 minutes'], exit: ['20', '13', '10'] },
    }),

    lesson({
      code: '5.07', title: 'Adding and subtracting terms',
      li: ['simplify expressions by collecting like terms'],
      sc: ['identify <b>like terms</b> (same letters, same powers)', 'add and subtract the coefficients of like terms', 'collect several sets of like terms'],
      terms: ['Like terms', 'Coefficient'],
      we: [al('3m + 4m'), al('12m - 4m'), al('7y - 4y - y'), al('6uv + 4 + 12uv'), al('5h^2 + 6h + 8h^2 + 11h'), al('13h^3 - 6h - 8h - 11h^3')],
      a: { text: 'Simplify.', kind: 'short', items: [al('3m + 4m'), al('12m - 4m'), al('5a + a'), al('9k - 9k'), al('2x + 3x + 4x'), al('7y - 4y - y')] },
      b: { text: 'Are these like terms? Write yes or no.', kind: 'short', items: [`${al('3a')} and ${al('5a')}`, `${al('2x')} and ${al('2y')}`, `${al('4ab')} and ${al('7ba')}`, `${al('m^2')} and ${al('3m')}`, `${al('6')} and ${al('6p')}`, `${al('-2k^2')} and ${al('k^2')}`] },
      c: { text: 'Simplify.', kind: 'work', cols: 3, items: [al('6uv + 4 + 12uv'), al('5a + 3b + 2a + b'), al('8x - 3 + 2x + 7'), al('4pq - pq + 3qp'), al('10 - 3m - 4 + 5m'), al('2y + 5 - 2y')] },
      d: { text: 'Simplify.', kind: 'work', items: [al('5h^2 + 6h + 8h^2 + 11h'), al('13h^3 - 6h - 8h - 11h^3'), al('3ab - 2a + 5ab + 7a - b'), 'A triangle has sides 2<i>x</i>, 3<i>x</i> + 1 and <i>x</i> + 4. Write and simplify its perimeter.'] },
      ext: { q: `Simplify ${al('4x^2y - 3xy^2 + x^2y + 5xy^2 - xy')}.`, steps: [`Like terms: ${al('4x^2y + x^2y')}`, `${al('-3xy^2 + 5xy^2')}`, `${al('-xy')} has no partner`], a: al('5x^2y + 2xy^2 - xy'), qs: [`Simplify ${al('7a^2 - 3a + 2 - a^2 + 5a - 8')}.`, 'Find the missing term: 5<i>m</i> + ? − 2<i>m</i> = 9<i>m</i>'] },
      summary: { steps: ['<b>Like terms</b> have exactly the same letters and powers.', 'Add or subtract only like terms.', 'Keep the sign in front of each term.', 'Write the answer with the highest power first.'],
        worked: [[al('3m + 4m'), ['3 + 4 = 7'], al('7m')], [al('7y - 4y - y'), ['7 − 4 − 1'], al('2y')], [al('6uv + 4 + 12uv'), ['6 + 12 = 18'], al('18uv + 4')], [al('5h^2 + 6h + 8h^2 + 11h'), ['h² terms, then h terms'], al('13h^2 + 17h')]] },
      exit: { qs: [`Simplify ${al('6k + 3k')}.`, `Simplify ${al('4a + 7 - a + 2')}.`, `Simplify ${al('3x^2 + 5x - x^2 - 8x')}.`] },
      ans: { we: [al('7m'), al('8m'), al('2y'), al('18uv + 4'), al('13h^2 + 17h'), al('2h^3 - 14h')], a: [al('7m'), al('8m'), al('6a'), '0', al('9x'), al('2y')], b: ['yes', 'no', 'yes', 'no', 'no', 'yes'],
        c: [al('18uv + 4'), al('7a + 4b'), al('10x + 4'), al('6pq'), al('2m + 6'), '5'], d: [al('13h^2 + 17h'), al('2h^3 - 14h'), al('8ab + 5a - b'), al('6x + 5')], ext: [al('6a^2 + 2a - 6'), al('6m')], exit: [al('9k'), al('3a + 9'), al('2x^2 - 3x')] },
    }),

    lesson({
      code: '5.08', title: 'Multiplying terms',
      li: ['multiply algebraic terms'],
      sc: ['multiply the numbers first, then the letters', 'write repeated letters as powers', 'use the sign rules for negative terms'],
      terms: ['Coefficient', 'Power'],
      we: [al('3m × 4m'), al('a × a × a × a'), al('9v × 4 × 5v'), al('3pq × 5pq'), al('-7d × (-3d)'), al('lmn × lmn × lmn')],
      a: { text: 'Simplify.', kind: 'short', items: [al('3 × 4m'), al('2a × 5'), al('a × b'), al('a × a × a × a'), al('x × 7 × y'), al('3m × 4m')] },
      b: { text: 'Simplify.', kind: 'short', items: [al('6p × 2q'), al('9v × 4 × 5v'), al('k × k × 2'), al('5ab × 2a'), al('4x × 3x × x'), al('2c × 2c × 2c')] },
      c: { text: 'Simplify. Watch the signs.', kind: 'work', cols: 3, items: [al('-7d × (-3d)'), al('-2a × 6b'), al('3x × (-x)'), al('-4m × (-m) × 2'), al('-3x^2y × 2x'), al('5 × (-t) × (-t)')] },
      d: { text: 'Simplify.', kind: 'work', items: [al('3pq × 5pq'), al('lmn × lmn × lmn'), al('2a^2 × 3a^3'), 'A rectangle is 3<i>x</i> cm long and 2<i>y</i> cm wide. Write its area.'] },
      ext: { q: `Simplify ${al('(2ab)^3')}.`, steps: [al('2ab × 2ab × 2ab'), 'Numbers: 2 × 2 × 2 = 8', al('a^3b^3')], a: al('8a^3b^3'), qs: [`Simplify ${al('(-3m)^2')}.`, `Find the missing term: ${al('4x × ? = 20x^2y')}.`] },
      summary: { steps: ['Multiply the numbers (coefficients).', 'Multiply the letters, in alphabetical order.', 'Same letter repeated → use a power.', 'Signs: same → +, different → −.'],
        worked: [[al('3m × 4m'), ['3 × 4 = 12, m × m = m²'], al('12m^2')], [al('9v × 4 × 5v'), ['9 × 4 × 5 = 180'], al('180v^2')], [al('-7d × (-3d)'), ['− × − = +'], al('21d^2')], [al('(2ab)^3'), ['8, a³, b³'], al('8a^3b^3')]] },
      exit: { qs: [`Simplify ${al('5 × 3k')}.`, `Simplify ${al('4a × 6ab')}.`, `Simplify ${al('-2x × 3x × (-y)')}.`] },
      ans: { we: [al('12m^2'), al('a^4'), al('180v^2'), al('15p^2q^2'), al('21d^2'), al('l^3m^3n^3')], a: [al('12m'), al('10a'), al('ab'), al('a^4'), al('7xy'), al('12m^2')], b: [al('12pq'), al('180v^2'), al('2k^2'), al('10a^2b'), al('12x^3'), al('8c^3')],
        c: [al('21d^2'), al('-12ab'), al('-3x^2'), al('8m^2'), al('-6x^3y'), al('5t^2')], d: [al('15p^2q^2'), al('l^3m^3n^3'), al('6a^5'), `${al('6xy')} cm²`], ext: [al('9m^2'), al('5xy')], exit: [al('15k'), al('24a^2b'), al('6x^2y')] },
    }),

    lesson({
      code: '5.09', title: 'Dividing terms',
      li: ['divide algebraic terms'],
      sc: ['write a division as a fraction', 'cancel common factors in the numbers and the letters', 'simplify answers that are still fractions'],
      terms: ['Quotient', 'Cancel'],
      we: [al('15m ÷ 3'), al('9v ÷ v'), fa('49y', '7'), fa('12x^2y', '4xy'), al('32de^2 ÷ 10de'), fa('-3x^2y × 2x', '3x × (-x)')],
      a: { text: 'Simplify.', kind: 'short', items: [al('15m ÷ 3'), al('9v ÷ v'), fa('49y', '7'), al('8ab ÷ 2'), al('20k ÷ 5k'), fa('6pq', 'q')] },
      b: { text: 'Simplify.', kind: 'short', items: [fa('12x^2y', '4xy'), al('18m^2 ÷ 6m'), fa('10ab', '5b'), al('24t^3 ÷ 8t'), fa('3x', '12'), fa('4a', '6ab')] },
      c: { text: 'Simplify.', kind: 'work', cols: 3, items: [al('32de^2 ÷ 10de'), fa('-20mn', '4m'), fa('-15x^2', '-5x'), fa('9a^2b^2', '3ab'), fa('14pq^2', '21pq'), al('-36y^3 ÷ 4y^2')] },
      d: { text: 'Simplify.', kind: 'work', items: [fa('-3x^2y × 2x', '3x × (-x)'), fa('4a × 6b', '8ab'), fa('10m^2n', '2m × 5n'), 'A rectangle has area 24<i>xy</i> cm² and length 6<i>x</i> cm. Find its width.'] },
      ext: { q: `Simplify ${fa('6a^3b × 4ab^2', '12a^2b^2')}.`, steps: [`Top: ${al('24a^4b^3')}`, `÷ ${al('12a^2b^2')}`], a: al('2a^2b'), qs: [`Simplify ${fa('(3m)^2', '6m')}.`, `Simplify ${fa('8x^2y × 3y', '6xy × 2x')}.`] },
      summary: { steps: ['Write the division as a fraction.', 'Cancel the numbers by their HCF.', 'Cancel letters that are on top and bottom.', 'Signs: same → +, different → −.'],
        worked: [[al('15m ÷ 3'), ['15 ÷ 3 = 5'], al('5m')], [fa('12x^2y', '4xy'), ['12 ÷ 4 = 3, cancel x and y'], al('3x')], [al('32de^2 ÷ 10de'), ['32/10 = 16/5, cancel d and e'], fa('16e', '5')], [fa('6a^3b × 4ab^2', '12a^2b^2'), ['24 ÷ 12 = 2'], al('2a^2b')]] },
      exit: { qs: [`Simplify ${al('21p ÷ 7')}.`, `Simplify ${fa('16ab^2', '4b')}.`, `Simplify ${fa('-10x^3', '15x')}.`] },
      ans: { we: [al('5m'), '9', al('7y'), al('3x'), fa('16e', '5'), al('2xy')], a: [al('5m'), '9', al('7y'), al('4ab'), '4', al('6p')], b: [al('3x'), al('3m'), al('2a'), al('3t^2'), fa('x', '4'), fa('2', '3b')],
        c: [fa('16e', '5'), al('-5n'), al('3x'), al('3ab'), fa('2q', '3'), al('-9y')], d: [al('2xy'), '3', al('m'), `${al('4y')} cm`], ext: [fa('3m', '2'), al('2y')], exit: [al('3p'), al('4ab'), fa('-2x^2', '3')] },
    }),

    lesson({
      code: '5.10', title: 'Guess, check and improve',
      li: ['solve equations by guess, check and improve'],
      sc: ['substitute a guess into the equation', 'decide whether the guess is too high or too low', 'improve the guess until it is correct'],
      terms: ['Equation', 'Solution'],
      we: ['Is <i>x</i> = 4 a solution of 3<i>x</i> + 2 = 14?', 'Solve 4<i>m</i> − 9 = 7.', `Solve ${fa('k', '7')} + 2 = 2.`, `Solve ${fa('d', '3')} − 4 = 2.`, 'Solve 5<i>a</i> + 13 = 58.', 'Solve 2<i>x</i> + 3 = 4 (the answer is not a whole number).'],
      a: { text: 'Is the value a solution? Write yes or no.', kind: 'short', items: ['<i>x</i> + 5 = 12, <i>x</i> = 7', '3<i>y</i> = 21, <i>y</i> = 6', '<i>m</i> − 4 = 9, <i>m</i> = 13', '2<i>k</i> + 1 = 11, <i>k</i> = 5', `${fa('p', '2')} = 8, <i>p</i> = 4`, '10 − <i>t</i> = 3, <i>t</i> = 7'] },
      b: { text: 'Solve by guess, check and improve.', kind: 'short', items: ['<i>x</i> + 8 = 15', '4<i>m</i> = 36', '<i>y</i> − 6 = 11', '2<i>a</i> + 1 = 9', '3<i>n</i> − 2 = 10', `${fa('w', '5')} = 4`] },
      c: { text: 'Solve by guess, check and improve. Show your guesses in a table.', kind: 'work', cols: 3, items: ['4<i>m</i> − 9 = 7', `${fa('k', '7')} + 2 = 2`, `${fa('d', '3')} − 4 = 2`, '5<i>a</i> + 13 = 58', '7<i>b</i> − 10 = 39', '3(<i>x</i> + 2) = 27'] },
      d: { text: 'Solve by guess, check and improve.', kind: 'work', items: ['2<i>x</i> + 3 = 4', '<i>n</i>² = 144', '<i>x</i>² + <i>x</i> = 30', 'I think of a number, multiply by 6 and subtract 5. The answer is 43. What is my number?'] },
      ext: { q: 'Solve <i>x</i>² = 20 to 1 decimal place by guess, check and improve.', steps: ['4² = 16 (low), 5² = 25 (high)', '4.4² = 19.36 (low), 4.5² = 20.25 (high)', '4.47² ≈ 19.98, so round to 4.5'], a: '<i>x</i> ≈ 4.5', qs: ['Solve <i>x</i>³ = 50 to 1 decimal place.', 'Solve <i>x</i>(<i>x</i> + 1) = 50 to 1 decimal place.'] },
      summary: { steps: ['Guess a value for the variable.', 'Substitute it into the equation.', 'Too big or too small? Adjust your guess.', 'Stop when both sides are equal.'],
        worked: [['Is x = 4 a solution of 3x + 2 = 14?', ['3 × 4 + 2 = 14'], 'yes'], ['4m − 9 = 7', ['m = 3: 3 (low)', 'm = 4: 7 ✓'], 'm = 4'], ['d/3 − 4 = 2', ['d = 18: 6 − 4 = 2 ✓'], 'd = 18'], ['x² = 20', ['4.4 low, 4.5 high'], 'x ≈ 4.5']] },
      exit: { qs: ['Is <i>a</i> = 3 a solution of 5<i>a</i> − 1 = 14?', 'Solve 3<i>x</i> + 4 = 25.', `Solve ${fa('y', '4')} + 7 = 12.`] },
      ans: { we: ['yes', '<i>m</i> = 4', '<i>k</i> = 0', '<i>d</i> = 18', '<i>a</i> = 9', '<i>x</i> = 0.5'], a: ['yes', 'no', 'yes', 'yes', 'no', 'yes'], b: ['7', '9', '17', '4', '4', '20'].map((x) => `= ${x}`),
        c: ['<i>m</i> = 4', '<i>k</i> = 0', '<i>d</i> = 18', '<i>a</i> = 9', '<i>b</i> = 7', '<i>x</i> = 7'], d: ['<i>x</i> = 0.5', '<i>n</i> = 12 (or −12)', '<i>x</i> = 5 (or −6)', '8'], ext: ['<i>x</i> ≈ 3.7', '<i>x</i> ≈ 6.6'], exit: ['yes', '<i>x</i> = 7', '<i>y</i> = 20'] },
    }),

    lesson({
      code: '5.11', title: 'Solving one-step equations',
      li: ['solve one-step equations algebraically'],
      sc: ['use the inverse operation to undo +, −, × or ÷', 'do the same to both sides of the equation', 'check the solution by substituting'],
      terms: ['Inverse operation', 'Solve'],
      we: ['<i>w</i> + 17 = 52', '<i>e</i> − 12 = 0', '5<i>p</i> = 15', `${fa('x', '2')} = 6`, '−4<i>y</i> = 28', '<i>k</i> + 3.5 = 1'],
      a: { text: 'Solve.', kind: 'short', items: ['<i>w</i> + 17 = 52', '<i>e</i> − 12 = 0', '<i>a</i> + 9 = 20', '<i>m</i> − 6 = 14', '<i>x</i> + 25 = 40', '<i>y</i> − 13 = 7'] },
      b: { text: 'Solve.', kind: 'short', items: ['5<i>p</i> = 15', `${fa('x', '2')} = 6`, '8<i>t</i> = 72', `${fa('n', '5')} = 9`, '12<i>c</i> = 60', `${fa('h', '10')} = 3`] },
      c: { text: 'Solve. Show each step and check.', kind: 'work', cols: 3, items: ['−4<i>y</i> = 28', '<i>k</i> + 3.5 = 1', `${fa('m', '-3')} = 5`, '<i>x</i> − 8 = −12', '6<i>b</i> = 21', '0.5<i>q</i> = 7'] },
      d: { text: 'Write an equation, then solve it.', kind: 'work', items: ['A number plus 19 is 45.', 'Seven times a number is 84.', 'A number divided by 4 is 11.', 'Take 23 from a number and the answer is 58.'] },
      ext: { q: 'Solve 15 = <i>x</i> − 4 and check.', steps: ['The variable can be on either side', 'Add 4 to both sides: 19 = x'], a: '<i>x</i> = 19. Check: 19 − 4 = 15 ✓', qs: ['Solve 36 = 9<i>n</i>.', `Solve ${fa('2', '3')}<i>a</i> = 10.`] },
      summary: { steps: ['Ask: what is being done to the variable?', 'Do the <b>inverse</b> to both sides.', '+ ↔ −, × ↔ ÷.', 'Check by substituting back.'],
        worked: [['w + 17 = 52', ['− 17 from both sides'], '<i>w</i> = 35'], ['5p = 15', ['÷ 5'], '<i>p</i> = 3'], ['x/2 = 6', ['× 2'], '<i>x</i> = 12'], ['15 = x − 4', ['+ 4'], '<i>x</i> = 19']] },
      exit: { qs: ['Solve <i>n</i> + 8 = 30.', 'Solve 9<i>x</i> = 63.', `Solve ${fa('t', '6')} = −4.`] },
      ans: { we: ['<i>w</i> = 35', '<i>e</i> = 12', '<i>p</i> = 3', '<i>x</i> = 12', '<i>y</i> = −7', '<i>k</i> = −2.5'], a: ['35', '12', '11', '20', '15', '20'], b: ['3', '12', '9', '45', '5', '30'],
        c: ['<i>y</i> = −7', '<i>k</i> = −2.5', '<i>m</i> = −15', '<i>x</i> = −4', '<i>b</i> = 3.5', '<i>q</i> = 14'], d: ['<i>n</i> + 19 = 45, <i>n</i> = 26', '7<i>n</i> = 84, <i>n</i> = 12', '<i>n</i>/4 = 11, <i>n</i> = 44', '<i>n</i> − 23 = 58, <i>n</i> = 81'], ext: ['<i>n</i> = 4', '<i>a</i> = 15'], exit: ['<i>n</i> = 22', '<i>x</i> = 7', '<i>t</i> = −24'] },
    }),

    lesson({
      code: '5.12', title: 'Solving two-step equations',
      li: ['solve two-step equations algebraically'],
      sc: ['undo + or − first, then × or ÷', 'set out each step on a new line', 'solve equations with fractions'],
      terms: ['Two-step equation', 'Check'],
      we: ['3<i>t</i> + 4 = 10', '4<i>y</i> − 7 = 5', `${fa('m', '4')} − 8 = 9`, `${fa('x', '3')} + 5 = 8`, `${fa('m - 4', '2')} = 3`, '7 − 2<i>x</i> = 15'],
      a: { text: 'Solve.', kind: 'short', items: ['2<i>n</i> + 6 = 12', '3<i>t</i> + 4 = 10', '5<i>a</i> − 2 = 18', '4<i>y</i> − 7 = 5', '6<i>k</i> + 1 = 31', '10<i>b</i> − 5 = 45'] },
      b: { text: 'Solve.', kind: 'short', items: [`${fa('m', '4')} − 8 = 9`, `${fa('x', '3')} + 5 = 8`, `${fa('a', '2')} + 1 = 7`, `${fa('p', '5')} − 3 = 1`, `${fa('y', '6')} + 2 = 4`, `${fa('w', '10')} − 1 = 0`] },
      c: { text: 'Solve. Show each step.', kind: 'work', cols: 3, items: [`${fa('m - 4', '2')} = 3`, `${fa('k + 5', '3')} = 4`, '7 − 2<i>x</i> = 15', '3<i>x</i> + 11 = 2', '5<i>d</i> − 8 = −23', '2(<i>x</i> + 3) = 18'] },
      d: { text: 'Solve. Show each step.', kind: 'work', items: [`${fa('2x', '3')} + 1 = 9`, '4(<i>y</i> − 2) = 30', '1.5<i>t</i> + 2 = 8', `${fa('3n - 1', '4')} = 5`] },
      ext: { q: 'Solve 5<i>x</i> + 3 = 2<i>x</i> + 18.', steps: ['− 2x from both sides: 3x + 3 = 18', '− 3: 3x = 15', '÷ 3'], a: '<i>x</i> = 5', qs: ['Solve 7<i>a</i> − 4 = 3<i>a</i> + 12.', 'Solve 2(<i>x</i> + 5) = <i>x</i> + 14.'] },
      summary: { steps: ['Undo + or − first (both sides).', 'Then undo × or ÷.', 'For a fraction like (m − 4)/2: × first.', 'Check in the original equation.'],
        worked: [['3t + 4 = 10', ['− 4: 3t = 6', '÷ 3'], '<i>t</i> = 2'], ['m/4 − 8 = 9', ['+ 8: m/4 = 17', '× 4'], '<i>m</i> = 68'], ['(m − 4)/2 = 3', ['× 2: m − 4 = 6', '+ 4'], '<i>m</i> = 10'], ['5x + 3 = 2x + 18', ['3x = 15'], '<i>x</i> = 5']] },
      exit: { qs: ['Solve 2<i>x</i> + 5 = 17.', `Solve ${fa('n', '3')} − 2 = 4.`, 'Solve 3(<i>k</i> − 1) = 24.'] },
      ans: { we: ['<i>t</i> = 2', '<i>y</i> = 3', '<i>m</i> = 68', '<i>x</i> = 9', '<i>m</i> = 10', '<i>x</i> = −4'], a: ['3', '2', '4', '3', '5', '5'], b: ['68', '9', '12', '20', '12', '10'],
        c: ['<i>m</i> = 10', '<i>k</i> = 7', '<i>x</i> = −4', '<i>x</i> = −3', '<i>d</i> = −3', '<i>x</i> = 6'], d: ['<i>x</i> = 12', '<i>y</i> = 9.5', '<i>t</i> = 4', '<i>n</i> = 7'], ext: ['<i>a</i> = 4', '<i>x</i> = 4'], exit: ['<i>x</i> = 6', '<i>n</i> = 18', '<i>k</i> = 9'] },
    }),

    lesson({
      code: '5.13', title: 'Equations and problem solving',
      li: ['write and solve equations to solve problems'],
      sc: ['choose a variable for the unknown', 'write an equation from the words', 'solve it and answer the question in a sentence'],
      terms: ['Unknown', 'Profit'],
      we: ['A number multiplied by 17 is 1003. Which equation: <i>N</i> + 17 = 1003, 1003 − <i>N</i> = 17, 17<i>N</i> = 1003 or 1003 + <i>N</i> = 17?', 'Solve 17<i>N</i> = 1003.', 'Raffle prizes cost $180 and tickets are $5. Write and solve an equation for the number of tickets to cover costs.', 'How many tickets must be sold to make a $2100 profit?', 'The perimeter of a square is 52 cm. Find the side length.', 'Three consecutive numbers add to 72. Find them.'],
      a: { text: 'Write an equation for each. Do not solve.', kind: 'short', items: ['A number plus 8 is 20.', 'Five times a number is 45.', 'A number minus 7 is 3.', 'Half a number is 16.', 'Double a number plus 1 is 15.', 'A number times 3, minus 4, is 11.'] },
      b: { text: 'Solve each equation.', kind: 'short', items: ['<i>n</i> + 8 = 20', '5<i>n</i> = 45', '<i>n</i> − 7 = 3', `${fa('n', '2')} = 16`, '2<i>n</i> + 1 = 15', '3<i>n</i> − 4 = 11'] },
      c: { text: 'Write an equation, solve it, and answer in a sentence.', kind: 'work', cols: 3, items: ['A pen and a $4 notebook cost $6.50. Find the price of the pen.', 'The perimeter of a square is 52 cm. Find the side length.', '6 friends share a bill equally and each pays $23. Find the bill.', 'Tom is 3 times as old as Kate. Tom is 36. How old is Kate?', 'A taxi charges $4 plus $2 per km. A trip cost $30. How far was it?', 'Movie tickets cost $15 each plus a $3 booking fee. The total was $78. How many tickets?'] },
      d: { text: 'Harder problems.', kind: 'work', items: ['Three consecutive numbers add to 72. Find them.', 'A rectangle is twice as long as it is wide. Its perimeter is 48 m. Find its length and width.', 'Raffle prizes cost $180 and tickets are $5. How many tickets to make a $2100 profit?', 'Ali has $50 more than Ben. Together they have $210. How much does Ben have?'] },
      ext: { q: 'A phone plan costs $20 plus 10c per text. Another costs $35 with free texts. How many texts make them cost the same?', steps: ['20 + 0.1t = 35', '0.1t = 15', 't = 150'], a: '150 texts', qs: ['A gym charges $60 to join plus $12 a week. Another charges $20 a week with no joining fee. After how many weeks do they cost the same?', 'The sum of two numbers is 50 and their difference is 14. Find the numbers.'] },
      summary: { steps: ['Choose a letter for the unknown.', 'Write an equation from the words.', 'Solve it step by step.', 'Answer the question in a sentence with units.'],
        worked: [['Number × 17 = 1003', ['17N = 1003', '÷ 17'], '<i>N</i> = 59'], ['Raffle: cover $180', ['5N = 180'], '36 tickets'], ['$2100 profit', ['5N − 180 = 2100', '5N = 2280'], '456 tickets'], ['Phone plans', ['20 + 0.1t = 35'], '150 texts']] },
      exit: { qs: ['A number plus 14 is 31. Write and solve an equation.', 'Four equal books cost $62. Find the cost of one book.', 'A number is doubled and 9 is added. The result is 41. Find the number.'] },
      ans: { we: ['C: 17<i>N</i> = 1003', '<i>N</i> = 59', '5<i>N</i> = 180, <i>N</i> = 36 tickets', '5<i>N</i> − 180 = 2100, <i>N</i> = 456 tickets', '4<i>s</i> = 52, <i>s</i> = 13 cm', '<i>n</i> + <i>n</i> + 1 + <i>n</i> + 2 = 72: 23, 24, 25'],
        a: ['<i>n</i> + 8 = 20', '5<i>n</i> = 45', '<i>n</i> − 7 = 3', '<i>n</i>/2 = 16', '2<i>n</i> + 1 = 15', '3<i>n</i> − 4 = 11'], b: ['12', '9', '10', '32', '7', '5'],
        c: ['$2.50', '13 cm', '$138', '12', '13 km', '5 tickets'], d: ['23, 24, 25', 'length 16 m, width 8 m', '456 tickets', '$80'], ext: ['7.5 weeks', '32 and 18'], exit: ['<i>n</i> + 14 = 31, <i>n</i> = 17', '4<i>b</i> = 62, <i>b</i> = $15.50', '2<i>n</i> + 9 = 41, <i>n</i> = 16'] },
    }),
  ],
};
