// Worksheet questions for Chapter 11 Probability (lib/worksheet.js). See ../ch01-integers/content.js.
const D = require('../../lib/diagrams');
const { F, simp, fmt, gcd } = require('../../lib/calc');

const Fr = (n, d) => { const [a, b] = simp([n, d]); return b === 1 ? String(a) : F(a, b); };
const word = (p) => (p === 0 ? 'impossible' : p === 1 ? 'certain' : p < 0.5 ? 'unlikely' : p === 0.5 ? 'even chance' : 'likely');
const COL = ['red', 'blue', 'green', 'yellow'];
const SP = { red: '#e8a3a3', blue: '#a8b8ec', green: '#a9d8b0', yellow: '#f3dd8a' };

module.exports = {
  '11.01': () => [
    [{ text: 'How many outcomes are in the sample space?', gen: (i) => { const X = [['tossing a coin', 2], ['rolling a die', 6], ['choosing a day of the week', 7], ['choosing a month', 12], ['choosing a card from a deck', 52], ['choosing a letter of the alphabet', 26], ['a spinner with 5 equal sectors', 5], ['choosing a suit of cards', 4], ['choosing a vowel', 5], ['choosing a digit 0–9', 10], ['choosing a letter from MATHS', 5], ['choosing a season', 4], ['rolling an 8-sided die', 8], ['choosing an even number 1–10', 5], ['choosing a colour of the rainbow', 7]]; return i >= X.length ? null : { q: X[i][0], a: String(X[i][1]) }; } }],
    [{ text: 'List the sample space, then count the outcomes.', gen: (i) => { const X = [['rolling a die', '1, 2, 3, 4, 5, 6'], ['choosing a letter from CAT', 'C, A, T'], ['choosing a suit', 'hearts, diamonds, clubs, spades'], ['an odd number less than 10', '1, 3, 5, 7, 9'], ['a weekend day', 'Saturday, Sunday'], ['a vowel', 'a, e, i, o, u'], ['a prime less than 12', '2, 3, 5, 7, 11'], ['a letter from BOOK', 'B, O, K'], ['a multiple of 5 up to 30', '5, 10, 15, 20, 25, 30'], ['a factor of 12', '1, 2, 3, 4, 6, 12']]; if (i >= X.length) return null; const [q, a] = X[i]; return { q, a, lines: [`{ ${a} }`, `${a.split(', ').length} outcomes`] }; } }],
    [{ text: 'Two things happen together. Multiply to count the outcomes, then list a few.', gen: (i) => { const X = [['toss a coin and roll a die', 2, 6, 'H1, H2, …, T6'], ['toss two coins', 2, 2, 'HH, HT, TH, TT'], ['roll two dice', 6, 6, '(1,1), (1,2), …, (6,6)'], ['choose a shirt (3) and pants (4)', 3, 4, 'S1P1, S1P2, …'], ['spin a 4-colour spinner and toss a coin', 4, 2, 'red-H, red-T, …'], ['choose a day of the week and toss a coin', 7, 2, 'Mon-H, Mon-T, …'], ['choose an entrée (2) and a main (5)', 2, 5, 'E1M1, E1M2, …']]; if (i >= X.length) return null; const [q, a, b, l] = X[i]; return { q, a: String(a * b), lines: [`${a} × ${b} = ${a * b}`, `e.g. ${l}`] }; } }],
  ],
  '11.02': ({ ri, pick }) => [
    [{ text: 'A fair die is rolled. Find the probability as a fraction.', gen: (i) => { const X = [['a 4', 1], ['an even number', 3], ['an odd number', 3], ['more than 4', 2], ['less than 3', 2], ['a 7', 0], ['a multiple of 3', 2], ['a prime', 3], ['not a 6', 5], ['at least 5', 2], ['a factor of 6', 4], ['a square number', 2], ['less than 10', 6], ['a 1 or a 2', 2]]; return i >= X.length ? null : { q: `P(${X[i][0]})`, a: Fr(X[i][1], 6) }; } }],
    [{ text: 'Count the favourable outcomes and the total, then simplify.', gen: () => { const a = ri(1, 9), b = ri(1, 9), c1 = pick(COL); let c2; do c2 = pick(COL); while (c2 === c1); return { q: `A bag has ${a} ${c1} and ${b} ${c2} counters. P(${c1})`, a: Fr(a, a + b), lines: [`${a} ${c1} out of ${a + b}`, `P = ${F(a, a + b)} = ${Fr(a, a + b)}`] }; } }],
    [{ text: 'Use the spinner (R = red, B = blue, G = green, Y = yellow). Each sector is the same size.', gen: () => { const k = pick([4, 5, 6, 8]), cols = Array.from({ length: k }, () => pick(COL)); const c = pick(cols), n = cols.filter((x) => x === c).length; return { q: `P(${c}), as a fraction and a percentage`, fig: D.spinner({ sectors: cols.map((x) => ({ label: x[0].toUpperCase(), size: 1, fill: SP[x] })), w: 30, h: 30 }), a: `${Fr(n, k)} = ${fmt((n / k) * 100, 1)}%`, lines: [`${n} of the ${k} sectors are ${c}`, `P = ${Fr(n, k)} = ${fmt((n / k) * 100, 1)}%`] }; } }],
  ],
  '11.03': ({ pick }) => [
    [{ text: 'Write the chance word: impossible, unlikely, even chance, likely or certain.', gen: () => { const p = pick([0, 0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 0.95, 1, 0.05]); return { q: pick([fmt(p), `${fmt(p * 100)}%`]), a: word(p) }; } }],
    [{ text: 'Write the probability as a fraction, then choose the chance word.', gen: () => { const r = pick([0, 1, 2, 3, 4, 5, 6]), b = pick([0, 1, 2, 3, 4, 5, 6]); if (r + b === 0) return { q: '' }; return { q: `${r} red and ${b} blue counters: P(red)`, a: `${Fr(r, r + b)}, ${word(r / (r + b))}`, lines: [`P(red) = ${F(r, r + b)}${r && r !== r + b ? ` = ${Fr(r, r + b)}` : ''}`, `${word(r / (r + b))}`] }; } }],
    [{ text: 'Which is more likely? Change both to decimals first.', gen: () => { const a = pick([[1, 4], [2, 5], [3, 8], [1, 3], [3, 5], [7, 10], [5, 8], [2, 3]]), p = pick([15, 30, 35, 45, 55, 65, 70, 85]); if (Math.abs(a[0] / a[1] - p / 100) < 1e-9) return { q: '' }; return { q: `${F(a[0], a[1])} or ${p}%?`, a: a[0] / a[1] > p / 100 ? F(a[0], a[1]) : `${p}%`, lines: [`${F(a[0], a[1])} = ${fmt(a[0] / a[1], 3)}, ${p}% = ${fmt(p / 100, 2)}`, `more likely: ${a[0] / a[1] > p / 100 ? F(a[0], a[1]) : `${p}%`}`] }; } }],
  ],
  '11.04': ({ ri, pick }) => [
    [{ text: 'Find the expected number: probability × number of trials.', gen: () => { const [e, d] = pick([['heads', 2], ['a 6 on a die', 6], ['an even number on a die', 2], ['a heart', 4], ['a 1 or 2 on a die', 3]]), t = d * ri(2, 30); return { q: `${e} in ${t} trials`, a: String(t / d) }; } }],
    [{ text: 'Find the experimental probability: times it happened ÷ trials. Simplify.', gen: () => { const t = pick([20, 30, 40, 50, 60, 100]), a = ri(1, t - 1); return { q: `${a} heads in ${t} tosses`, a: Fr(a, t), lines: [`${F(a, t)}`, `= ${Fr(a, t)}`] }; } }],
    [{ text: 'Compare the experiment with the theory. Show both probabilities as percentages.', gen: () => { const t = pick([30, 60, 120]), a = ri(Math.round(t / 6) - 4, Math.round(t / 6) + 6); return { q: `A 6 came up ${a} times in ${t} rolls. Is the die fair?`, a: `${fmt((a / t) * 100, 1)}% vs 16.7%`, lines: [`experiment: ${a} ÷ ${t} = ${fmt((a / t) * 100, 1)}%`, 'theory: 1 ÷ 6 = 16.7%', `${Math.abs(a / t - 1 / 6) < 0.05 ? 'close, so probably fair' : 'not close: roll more times to check'}`] }; } }],
  ],
  '11.05': ({ ri, pick }) => [
    [{ text: 'Find P(not E) = 1 − P(E).', gen: () => { const d = pick([2, 3, 4, 5, 6, 7, 8, 9, 10, 12]), n = ri(1, d - 1); if (gcd(n, d) > 1) return { q: '' }; return pick([0, 1]) ? { q: `P(E) = ${F(n, d)}`, a: F(d - n, d) } : { q: `P(E) = ${fmt(n / d, 2)}`, a: fmt(1 - n / d, 2) }; } }],
    [{ text: 'Describe the complementary event, then find its probability.', gen: (i) => { const X = [['rolling a 6', 'not rolling a 6', [5, 6]], ['tossing heads', 'tossing tails', [1, 2]], ['a red card', 'a black card', [1, 2]], ['an even number on a die', 'an odd number', [1, 2]], ['a heart', 'a club, diamond or spade', [3, 4]], ['rolling less than 3', 'rolling 3 or more', [2, 3]], ['a vowel from MATHS', 'a consonant', [4, 5]]]; if (i >= X.length) return null; const [e, c, [a, b]] = X[i]; return { q: e, a: `${c}, ${F(a, b)}`, lines: [`complement: ${c}`, `P = 1 − ${F(b - a, b)} = ${F(a, b)}`] }; } }],
    [{ text: 'Find P(not the colour given). Find the total first.', gen: () => { const a = ri(1, 9), b = ri(1, 9), c = ri(1, 9), t = a + b + c; const [nm, k] = pick([['red', a], ['blue', b], ['green', c]]); return { q: `${a} red, ${b} blue, ${c} green: P(not ${nm})`, a: Fr(t - k, t), lines: [`total: ${t}`, `not ${nm}: ${t} − ${k} = ${t - k}`, `P = ${F(t - k, t)}${Fr(t - k, t) !== F(t - k, t) ? ` = ${Fr(t - k, t)}` : ''}`] }; } }],
  ],
};
